- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
Esse PR:
- Remove a paginação do back para a lista de rateios de despesas.
A paginação será feira no front.
> feature/13075-lista-despesas-remove-paginacao 

- config/settings/base.py
- Retira SessionAuthentication
O objetivo é parar com o seguinte erro: {"detail":"CSRF Failed: CSRF token missing or incorrect."}
link para ideia da solução: https://stackoverflow.com/questions/39315443/using-django-with-postman-detailcsrf-failed-csrf-token-missing-or-incorrec/52347668
> Retira SessionAuthentication

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/api/views/especificacoes_viewset.py
- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
Removido o get_querysets de views que retornavam o queryset sem
modificação.
Isso provocava um efeito de cache nos resultados da API.
> fix(api): Corrige efeito de cache devido ao get_querysets de views da api

- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/despesas/tests/tests_despesas/test_despesa_calculo_status.py
Esse PR:
- Corrige o calculo do status dos rateios de despesa do tipo Capital.
O  método que calcula o status dos rateios de despesa do tipo capital estavam considerando
obrigatória a existência do campo tipo de custeio.
> fix(despesas): Corrige calculo status rateios tipo capital

- sme_ptrf_apps/core/models/fechamento_periodo.py
Corrige erro que ocorria o fechamento de prestação de contas quando
não havia um período anterior.
> fix(15110): Corrige fechamento prestação contas sem período anterior

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Corrige erro 500 quando se consultava uma data que não correspondia a nenhum período cadastrado.
Agora nesses casos a API retornará uma mensagem dizendo que o
período não foi encontrado.
> fix(15450): Erro 500 ao consultar um período não cadastrado

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/test_revisar_prestacao_de_contas_service.py
Ao revisar uma prestação os fechamentos não eram apagados e com nova conclusão da prestação eles eram duplicados.
Agora os fechamentos de uma prestação são apagados quando ela é revisada.
> fix(15110): Revisar prestacao não apagava os fechamentos

- sme_ptrf_apps/despesas/models/rateio_despesa.py
Ao montar a lista de especificações de despesas dava erro quando passava
por um rateio sem especificação
> fix(14337): Corrige erro na conclusão de uma prestação de contas

- sme_ptrf_apps/receitas/models/receita.py
- sme_ptrf_apps/receitas/models/tipo_receita.py
Esse PR:
- Ajusta a gravação de receitas para limpar o campo detalhe_outros caso o tipo de receita tenha detalhamentos.
> feat(17923): Limpa campo de detalhe_outros quando há detalhamentos

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_search_por_especificacao.py
Esse PR:
- Altera o filtro de despesas por especificação para desconsiderar caracteres acentuados.
- Corrige um problema na consulta de totais filtrados que não estava considerando filtros não definidos em filter_fields.
> feat(17929): Desconsidera acentos filtro despesas

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- Filtro nas informações para atas exibindo apenas ações que tenham lançamentos ou saldos anteriores
> Features/18890 exibir na ata apenas ações que tenham lançamentos ou saldo

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- Painel de associações exibe apenas acoes que tenham lançamentos e/ou saldo anterior
> Features/18898 painel associações exibir apenas ações que tenham valores vigentes

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_periodos_para_prestacao_contas.py
Esse PR:
- Cria novo endpoint que retorna os períodos para os cais dado associação pode editar ou criar uma prestação de contas.
> feat(19957): Prestação de contas apenas até o próximo período pendente

- sme_ptrf_apps/core/models/ata.py
- sme_ptrf_apps/core/tests/tests_api_atas_associacao/test_get_tabelas.py
Esse PR:
-Atualiza modelo e API para não ter mais opção de Ata provada com ressalvas.
> feat(22328): Remove opção de ata aprovada com ressalvas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Inclui no resultado da consulta de status do período o uuid da prestação de contas, caso ela já tenha sido gerada.
> feat(22699): Adiciona uuid da PC na consulta de status do período

- sme_ptrf_apps/core/api/serializers/devolucao_prestacao_conta_serializer.py
- sme_ptrf_apps/core/models/cobranca_prestacao_conta.py
Esse PR:
- Altera a regra de negócio para determinar a última devolução da PC para usar o id em vez da data da devolução.
> Feature(23678) Detalhe pc devolvidas cobrancas

- sme_ptrf_apps/core/services/periodo_associacao_services.py
Esse PR:
- Ajusta o serviço que retorna o status do período da associação que não estava considerando o status de aprovado com ressalvas.
> feat(23678): Ajusta serviço status para aprovado com ressalvas

- sme_ptrf_apps/core/api/serializers/tipo_devolucao_ao_tesouro_serializer.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_tipos_devolucao_ao_tesouro/test_tipos_devolucao_ao_tesouro_list.py
- sme_ptrf_apps/core/tests/tests_tipo_devolucao_ao_tesouro/test_tipo_devolucao_ao_tesouro_serializer.py
Esse PR:
- Altera o serializer de prestação de contas para incluir o uuid do tipo de devolução ao tesouro.
> feat(23815): Add uuid tipo devolução no json de PC

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_devolucoes_conta_relatorio_consolidado_dre.py
Esse PR:
Altera a regra de negócios para a consulta de devoluções
à conta do PTRF. Agora considera a data do crédito, antes
considerava o período de referência da devolução.
> feat(25499):Devoluções ao tesouro pela data do crédito

- sme_ptrf_apps/core/services/periodo_inicial.py
- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_totais.py
Esse PR:
- Corrige a consulta de totais de despesas que não aplicava o filtro por range de datas.
> feat(26292): Filtro por data em consulta de totais de rateio

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_salva_devolucoes_ao_tesouro.py
Esse PR:
-Alterar o endpoint de salvamento de devoluções ao tesouro de modo que ao passar uma lista de devoluções vazia o sistema apaga as devoluções existentes.
> feat(27047): Limpa devoluções tesouro ao salvar vazio

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_model.py
Esse PR:
- Ajusta o retorno para o dashboard da DRE de modo que o card Não Recebidas fique em primeiro.
> feat(26461): Dashboard card não recebido em primeiro

- sme_ptrf_apps/core/api/views/acoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acao_delete.py
Esse PR altera na API a exclusão de ações para retornar uma mensagem de erro ao tentar excluir ação
já usada.
> feat(29917): Valida exclusão de ações

- sme_ptrf_apps/core/api/views/periodos_viewset.py
- sme_ptrf_apps/core/models/periodo.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_delete.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_update.py
Esse PR faz ajustes na API necessários para resolver problemas encontrados no desenvolvimento do front:
- Atualização do campo período anterior
- Cálculo do campo ' editável'
- Tratamento de deleção de períodos referenciados na aplicação
> Feat(29908) Parametrização de Períodos (ajustes 2)

- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_delete.py
Ajustando texto de exclusão de associacao não permitida no teste test_delete_periodo_ja_usado
> Finalizando Feature 29886 - ajuste no texto do teste teste test_delete_periodo_ja_usado

- sme_ptrf_apps/core/services/carga_associacoes.py
Esse PR:
- Altera a carga de associações para aceitar a carga de associações com CNPJ vazio.
História [AB#31438](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31438)
> feat(31438): Aceitar cnpj vazio em carga associações

- sme_ptrf_apps/core/services/carga_associacoes.py
Esse PR:
- Corrige a comparação de títulos de cabeçalho com o modelo. A comparação quebrava quando os cabeçalhos usavam acentos.
> feat(29892): Comparação de cabeçalhos com acentos

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_tabela_valores_pendentes.py
Esse PR:
Altera o r resumo de conciliação que passa a ser por conta e a incluir informações de saldo anterior e posterior.
História [AB#34030](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34030)
> feat(34030): Altera api resumo conciliação

- sme_ptrf_apps/core/services/demonstrativo_financeiro_xlsx_service.py
Corrige a prévia de demonstrativos financeiros que não
estavam trazendo os saldos anteriores no bloco 3.
Bug [AB#37499](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/37499)
> Fix(37499) Saldo anterior previa d.financeiro

- sme_ptrf_apps/core/services/demonstrativo_financeiro_xlsx_service.py
Corrige cálculo dos saldos anteriores do
bloco 3 na versão final do demonstrativo
financeiro.
Fix [AB#37500](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/37500)
> fix(37500) Saldo anterior d.financeiro final

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/core/services/demonstrativo_financeiro_xlsx_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf.html
Esse PR ajusta os cálculos do bloco 3 do demonstrativo financeiro em PDF que
estava divergente do XLSX.
História [AB#34020](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34020)
> feat(34020): Ajusta calculos do bloco 3 do demonstrativo financeiro PDF

- sme_ptrf_apps/core/services/membro_associacao_service.py
- sme_ptrf_apps/core/services/unidade_service.py
- sme_ptrf_apps/users/services/sme_integracao_service.py
Esse PR troca a API de terceirizadas que consultava dados de unidades que tinha
problemas por não retornar informações de CEUs por uma nova que retornar
os dados de qualquer unidade.
História [AB#34052](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34052)
> feat(34052): Substitui API que consulta dados Unidade

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_user.py
Esse PR cria na api de usuários um filtro por unidade.
História [AB#37456](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/37456)
> feat(31436): Cria filtro por unidade na API User

- sme_ptrf_apps/users/services/sme_integracao_service.py
Esse PR altera a verificação de se um RF é ou não servidor na escola, para considerar que não é, caso a  não seja possível determinar pela API do EOL os cargos do RF ou os ocupantes desse cargo nas escola.
> feat(37456): Cargos do rf na escola vazio se não achar na API

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_usuarios_status.py
Esse PR Adiciona o id no retorna da consulta de status de um username.
> feat(37456): Add user id no retorno de user status

- sme_ptrf_apps/users/api/serializers/user.py
- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_update_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_usuarios_status.py
Esse PR:
- Altera put da API de usuários para não exigir unidade;
- Altera o retorno da consulta de status de um username para
retornar as associações que o usuário é membro mesmo quando
o username não existir ainda no SigEscola.
> Feature(37456) Criação usuários ajustes finais parte1

- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/sme_integracao_service.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_create_user.py
Esse PR altera a API de usuários para não exigir unidade na criação de usuário da visão SME.
> feat(37456): Criação de usuário SME não exige unidade

- sme_ptrf_apps/sme/tests/tests_api_saldos_bancarios/test_saldos_bancarios.py
- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/tests/test_api_user/conftest.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_create_vinculo_user_unidade.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_delete_vinculo_user_unidade.py
Esse PR traz a parte final das alterações necessárias na API de usuários para permitir o cadastro de usuários em várias visões a partir do perfil de acessos.
História [AB#39113](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39113)
> Feat(39113) Cadastro usuários em várias visões a partir do perfil de acessos (Parte 2) 

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_user.py
Esse PR:
- Inclui no filtro de usuários por nome a verificação também do username.
Complemento da história [AB#39113](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39113)
> feat(39113): Add username no filtro de usuarios por nome

- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
Esse PR complementa as alterações para atendimento da história [AB#39146](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39146). 
Altera o filtro de status dos rateios para serem feitos pelo status das despesas.
Isso porque, um rateio pode ter o status = COMPLETO, e porém ser parte de
uma despesa com status = INCOMPLETO.
> feat(39146): Filtro de status do rateio pela despesa - Parte 2

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_periodos_ate_agora_fora_implantacao.py
Esse PR cria um novo endpoint que retorna a lista de períodos a partir do período seguinte ao período de implantação da Associação até o período corrente.
História [AB#39524](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39524)
> Feat(39524) Seleção de períodos no resumo de recursos não exibir período de implantação

- sme_ptrf_apps/users/api/serializers/user.py
- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_create_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_visoes_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_update_user.py
Esse PR altera a API de usuários para:
- Retornar o id nos posts e puts
- Endpoint para retornar lista de visões cadastradas
História [AB#39113](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39113)
> Feat(39113) API de Usuários - Ajustes

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/services/unidade_service.py
Essa PR altera o comportamento da atualização de dados das unidades para não gravar nome vazio quando  o código eol não é encontrado pela API do EOL.
História [AB#39148](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39148)
> feat(39148): Não atualizar unidade com EOL inexistente

- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
- sme_ptrf_apps/receitas/services/carga_repasses_realizados.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_previstos.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_realizados.py
Esse PR altera as cargas de repasses previstos e realizados para não criarem mais tipos de contas e ações não cadastradas. Agora quando isso ocorrer será gerado um log de erro e o registro não será importado.
[AB#41223](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/41223)
> Feature(41223) Carga repasses passa a não criar ações e contas

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_com_filtros.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_api.py
Esse PR:
- Altera o serializer  DespesaListSerializer, para trazer campos necessários para exibição no front
História: [AB#42267](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42267)
> feat(42267): Créditos de recursos externos: permitir edição/exclusão a partir da entrada

- sme_ptrf_apps/core/services/membro_associacao_service.py
Esse PR corrige a forma que os retornos da API de membros são verificados e retornados ao front.
[AB#39282](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39282)
> feat(39282): Corrige validação código eol membro

- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas.py
Esse PR:
- Altera teste test_api_get_rateios_despesas para contemplar o campo receitas_saida_do_recurso
História: [AB#42276](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42276)
> test(42276): Gastos da escola: Na edição de saídas vinculadas a créditos de recursos externos usar formulário simplificado Parte 2

- sme_ptrf_apps/core/api/serializers/unidade_serializer.py
- sme_ptrf_apps/core/models/unidade.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acoes_list_associacoes_nao_vinculadas.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acoes_associacoes_list.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_associacoes.py
feat(34948): Adiciona nome da DRE ao retorno do endpoint
Esse PR:
- Adiciona property ao modelo Unidade que retorna o nome da DRE,
- Adiciona nome da DRE ao retorno do endpoint,
- Adiciona nome da DRE em resultado esperado nos testes.
História: [AB#34948](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34948)
> feat(34948) Adiciona nome da DRE ao retorno do endpoint

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_conclui_analise_prestacao_conta_como_devolvida.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_reabre_prestacao_conta.py
Esse PR:
- Bloqueia a reabertura ou devolução para ajustes de uma prestação de contas que tenha prestações de contas posteriores
- Retorna mensagens amigáveis para o Front
História: [AB#31424](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31424)
> feat(31424): [DRE] Não permite reabrir ou devolver para ajustes PC com PC´s posteriores

- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas.py
feat(23153): Adiciona filtro por tipo de conta
Esse PR:
- Adiciona tipo conta ao retorno da api,
- Adiciona filtro por tipo conta,
- Altera tests relacionados ao endpoint.
História: [AB#23153](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/23153)
> feat(23153) Adiciona filtro por tipo de conta

- sme_ptrf_apps/core/services/notificacao_services/notificacao_comentario_pc_service.py
Esse PR:
- Altera método notificar_comentario_pc, para também disparar email de nova notificação
Historia: [AB#34048](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34048)
> feat(34048): Envio de e-mail para informar entrada de nova notificação - Parte 4

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/templates/pdf/associacoes/exportarpdf/pdf.html
feat(43573): Preenche dados da unidade educacional
Esse PR:
- Atualiza modelo Unidade com o retorno da API do Sistema EOL, antes de gerar a ficha cadastral,
- Altera campo "email" da ficha cadastral, agora sendo preenchido pelo email cadastrado no modelo Associacao.
História: [AB#43573](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43573)
> feat(43573) Preenche dados da unidade educacional

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/models/observacao_conciliacao.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_salva_observacoes.py
feat(43735) Altera regra de cadastro de uma conciliação
Esse PR:
- Permite cadastrar concilição bancária por blocos (extrato bancário ou justificativas),
- Adiciona tests relacionados ao cadastro de conciliação bancária
História: [AB#43735](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43735)
> feat(43735) Altera regra de cadastro de uma conciliação

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/models/observacao_conciliacao.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_salva_observacoes.py
feat(43735) parte 2 aprimora cadastro de conciliacao por bloco
Esse PR:
- Aprimora condição para identificar se é um cadastro de extrato bancario ou justificativa
- Permite cadastro de justificativa vazia
História [AB#43735](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43735)
> feat(43735) parte 2 aprimora cadastro de conciliacao por bloco

- sme_ptrf_apps/despesas/models/despesa.py
feat(43985) parte 2 Ajusta CNPJ zerado sendo cadastrado em Fornecedores.
Esse PR:
- Não permite que um CNPJ zerado, seja cadastrado no modelo de Fornecedores
História: [AB#43985](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43985)
> feat(43985) parte 2 Ajusta CNPJ zerado sendo cadastrado em Fornecedores

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/api/views/relacao_bens_viewset.py
- sme_ptrf_apps/core/models/observacao_conciliacao.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
Esse PR:
- Altera o retrieve de Prestação de contas passa a incluir lista de arquivos de
referência Demonstrativo Financeiro, Relação de Bens e Comprovante de
extrato.
- Implementa novos endpoints para baixar esses documentos por UUID.
História: [AB#43799](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43799)
> feat(43799): Inclui arquivos de referência no retrieve de PC

- sme_ptrf_apps/core/api/views/membro_associacao_viewset.py
feat(42261)-parte-2 Ajuste endpoint que retorna membros
Esse PR:
- Adiciona uuid ao retorno do endpoint
- Adiciona cargo_associaco_value ao retorno do endpoint
História: [AB#42261](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42261)
> feat(42261)-parte-2 Ajuste endpoint que retorna membros

- sme_ptrf_apps/core/admin.py
feat(43961)-parte-2 Permite cadastro de arquivo pelo admin
Esse PR:
- Permite edição de usuario no admin do modelo ArquivoDownload
História: [AB#43961](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43961)
> feat(43961)-parte-2 Permite cadastro de arquivo pelo admin

- sme_ptrf_apps/users/services/carga_usuario_service.py
Esse PR corrige a carga de usuários que não estava atualizando o campo e_servidor.
História: [AB#47928](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/47928)
> fix(47928): Corrige carga usuário gravação e_servidor

- sme_ptrf_apps/users/admin.py
feat(48031)-parte-2 Remove campo admin
Esse PR:
- Remove a visualização do campo "visoes_log" do admin.
História: [AB#48031](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48031)
> feat(48031)-parte-2 Remove campo admin

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/conftest.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_list_analise_prestacao_contas.py
Esse PR:
- Cria o endpoint que retorna a lista de análises de prestação de contas que resultaram em devolução.
História [AB#43993](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43993)
> feat(43993): Cria endpoint que lista devoluções de PC

- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/conftest.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
Esse PR:
- Alterar a conclusão de PC para atualizar o registro da análise corrente;
- Inclui filtro por tipo de acerto na consulta de lançamentos com ajustes em uma análise de PC
História: [AB#43993](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43993)
> feat(43993): Cria endpoint que lista devoluções de PC - Pull Request 2

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_grupos_user.py
Esse PR:
- Altera retorno de grupos por visão
História: [AB#49747](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/49747)
> fix(49747): [Gestão de perfil] O filtro por grupo deveria exibir os grupos das unidades subordinadas

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta_nao_recebidas.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta_todos_os_status.py
Esse PR altera o comportamento de alguns endpoints de Prestação de Contas incluindo a possibilidade de filtro por múltiplos status.
O que foi feito:
[X] Novo filtro em /api/prestacoes-contas/nao-recebidas/
[X] Novo filtro em /api/prestacoes-contas/
[X] Novo filtro em /api/prestacoes-contas/todos-os-status/
Resolve o bug [AB#50224](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50224)
> bugfix(50224) Filtro de PCs por múltiplos status

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard.py
Esse PR altera o endpoint prestacoes-contas/dashboard/ para somar no card de PCs devolvidas os status de retornada após acertos e recebidas após acertos além do de devolvida para acertos.
O card de devolvidas passa a trazer também informação sobre a quantidade de PCs retornadas após acertos.
História: [AB#45684](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/45684)
> feat(45684): Devolução de PC - Parte 4

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_desfaz_recebimento_prestacao_conta_apos_acertos.py
Esse PR complementa a implementação o novo status de PC "Recebida após acertos""
O que foi feito:
[X] Criar endpoint para reverter recebimento
História: [AB#45655](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/45655)
> feat(45655): Cria status Recebido após acertos (continuação)

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_get_lancamentos.py
- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
Esse PR:
- Cria novo serializer que retorna receitas_saida_do_recurso
História: [AB#50753](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50753)
> fix(50753): Cria novo serializer que retorna receitas_saida_do_recurso

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_gerar_dados_demonstrativo_financeiro_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_gerar_dados_demonstrativo_financeiro_service/test_gerar_dados_demonstrativo_financeiro.py
Esse PR corrige o cálculo do demonstrativo financeiro em PDF que não estava
tratando corretamente os valores custeio negativos após uso de saldo de
livre aplicação.
Fix [AB#50979](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50979)
> fix(50979): Corrige cálculo do demonstrativo financeiro PDF

- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/models/periodo.py
fix(50221) Ordena filtro de periodo
Esse PR:
- Ordena lista de periodos por ordem decrescente
História: [AB#50221](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50221)
> fix(50221) Ordena filtro de periodo

- sme_ptrf_apps/users/api/views/login.py
O login não estava retornando os campos corretos para a identificação
de mensagens de devolução de PC pelo front. No caso de SME, esse
retorno deveria ser none sempre.
> feat(45693): Corrige retorno de pc devolvida quando SME

- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
feat(53365) Incluir campo no PDF
Esse PR:
- Adiciona campo detalhamento de acerto do documento ao PDF
História: [AB#53365](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53365)
> feat(53365) Incluir campo no PDF

- sme_ptrf_apps/core/api/views/presentes_ata_viewset.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/services/ata_dados_service.py
- sme_ptrf_apps/core/tests/tests_api_presentes_ata/test_api_presentes_ata.py
- sme_ptrf_apps/utils/remove_digitos_str.py
Esse PR:
- Altera a ordem das listas de presentes na ata. A lista de membros passa a ser ordenada pelo cargo e a de não membros pelo nome.
História: [AB#54223](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/54223)
> feat(54223): Altera ordem da lista presentes na ata

- sme_ptrf_apps/core/models/notificacao.py
- sme_ptrf_apps/core/tests/tests_notificacao/test_notificar_service.py
Esse PR corrige o serviço de geração de notificação para não criar a mesma notificação no mesmo dia.
Bug: [AB#55522](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55522)
> fix(55522): Corrige duplicação de notificações

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_model.py
Esse PR:
- Adiciona retorno de quantidade_nao_recebida de pcs ao endpoint prestacao_de_contas/dashboard
História: [AB#55954](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55954)
> feat(55954): 

- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR:
- Altera o texto de fechamento no PDF das atas conforme a existência ou não de comentários.
História: [AB#55187](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55187)
> feat(55187): Altera texto PDF ata conforme comentários

- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR:
- Altera o PDF da ata para exibir tópico "Retificações" apenas se houver retificações
- Altera o texto inicial conforme tipo da ata (Apresentação ou Retificação)
História: [AB#55188](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55188)
> feat(55188): Altera textos da ata de retificação

- sme_ptrf_apps/core/models/periodo.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_tabela_valores_pendentes.py
Altera os cálculos dos saldos de conciliação para que:
- Valores não conciliados de períodos anteriores quando conciliados em períodos futuros, não sejam considerados como conciliados em seu período original.
- A conciliação de lançamentos de períodos anteriores movimente a linha de saldo anterior no quadro resumo e não as linhas de débito ou crédito.
- Despesas sejam listadas como conciliadas apenas nos períodos onde foram efetivamente conciliados.
História: [AB#56099](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/56099)
> feat(56099): Altera cálculos de conciliação

- sme_ptrf_apps/core/templatetags/paracer_do_conselho.py
- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR corrige um erro que ocorria ao gerar as atas de prestação de contas.
O template não carregava o templatetag parecer_conselho.
O problema foi resolvido extraindo o código do tamplatetag para um arquivo próprio.
> feat(55187): Corrige erro geração das atas PC

- sme_ptrf_apps/templates/pdf/ata/pdf.html
Remove o bloco de devoluções ao tesouro da ata de retificação quando não
há devoluções.
> feat(55187): Altera PDF da ata de retificação

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_conclui_analise_prestacao_conta_como_devolvida.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_reabre_prestacao_conta.py
fix(57992): Mensagem não é possivel devolver PC
Esse PR:
- Altera mensagem de erro
História: [AB#57992](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57992)
> fix(57992): Mensagem não é possivel devolver PC

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
fix(57992)-parte-2: Mensagem não é possivel devolver PC
Esse PR:
- Adiciona method field "pode_reabrir" ao retrieve de prestacao de contas
História: [AB#57992](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57992)
> fix(57992)-parte-2: Mensagem não é possivel devolver PC

- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- sme_ptrf_apps/receitas/tests/conftest.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_api.py
Esse PR:
- Altera o create e update de créditos para atualizar o rateio estornado.
História: [AB#58666](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58666)
> feat(58666): Créditos referentes a estornos de gastos - parte 2

- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- sme_ptrf_apps/receitas/tests/conftest.py
Esse PR:
- Alterar o serializer de receita para aceitar gravação com rateio_estornado vazio.
História: [AB#58666](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58666)
> feat(58666): Créditos referentes a estornos de gastos - parte 3

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
Esse PR: 
- Altera a atualização de rateios para não mais apagar todos os rateios e regrava-los em uma atualização de
despesa. Agora os novos rateios são incluídos, os editados são atualizados e os apagados são excluídos.
Necessário para evitar que os registros de estorno sejam apagados quando uma despesa for alterada.
História: [AB#58666](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58666)
> feat(58666): Altera atualização de rateios da despesa

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
Esse PR
- Inclui Imposto retido na fonte inclui despesa imposto no DespesaListComRateiosSerializer, para ser usado na exibição da lista de gastos da escola
História: [AB#59496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59496)
> feat(59496): Gastos da Escola: Lançamento de imposto retido na fonte - Parte 02

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/static/css/pdf-demo-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(59671): Exibir informações de vínculo entre despesa e imposto
Esse PR:
- Adiciona informações de imposto ao serviço que gera os dados do PDF
- Adiciona novos campos ao template do PDF
- Altera função cadastro_completo do modelo de Despesa
> feat(59671): Exibir informações de vínculo entre despesa e imposto

- sme_ptrf_apps/core/services/info_por_acao_services.py
Esse PR altera a lógica de sumarização de despesas demonstradas e não demonstradas para considerar o período de conciliação da despesa.
Essa alteração foi feita apenas na apuração de prévias com valores ainda não fechados.
[AB#58642](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58642)
> feat(58642): Altera na ata o cálculo de despesas demonstradas/não demonstradas - Parte 1

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_transacoes_conciliacao.py
Esse PR:
- Cria ordenação, agrupamento por despesas impostos e exibe em conciliação bancária
História: [AB#61150](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61150)
> feat(61150): Exibir informações de retenção de imposto na conciliação bancária

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/core/tests/tests_dados_demo_financeiro_service/conftest.py
- sme_ptrf_apps/core/tests/tests_dados_demo_financeiro_service/test_api.py
- sme_ptrf_apps/core/tests/tests_dados_demo_financeiro_service/test_blocos_de_despesas.py
- sme_ptrf_apps/core/tests/tests_dados_demo_financeiro_service/test_resumo_por_acao.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
Esse PR:
- Altera a lógica de sumarização de despesas demonstradas e não demonstradas para considerar o período de conciliação da despesa.
No relatório Demonstrativo Financeiro (PDF)
História: [AB#58639](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58639)
> feat(58639): Altera Demo financ quanto a despesas demostradas

- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_ata_dados_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_ata_dados_service/test_informacoes_financeiras_para_atas_service.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- Conclui alterações nos cálculos de despesas demonstradas e não demonstradas nas tabelas de valores da ata de apresentação PDF ou Tela.
História: [AB#58642](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58642)
> feat(58642): Altera na ata o cálculo de despesas demonstradas/não demonstradas - Parte 2

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_associacoes_srarus_regularidade_ano.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_get_lancamentos.py
Esse PR:
- Inclui informações sobre impostos e permite ordenação dos gastos
História: [AB#61151](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61151)
> feat(61151): Exibir informações de retenção de imposto na análise de PC

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_get_lancamentos.py
Esse PR:
- Comenta teste defeituoso até a sua resolução
História: [AB#61151](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61151)
> feat(61151): Exibir informações de retenção de imposto na análise de PC - Parte 03

- sme_ptrf_apps/core/api/views/membro_associacao_viewset.py
- sme_ptrf_apps/core/services/membro_associacao_service.py
feat(60309): Seleção de cargo na educação do servidor
Esse PR:
- Altera regra que só permitia retornar 1 cargo para o servidor
História: [AB#60309](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60309)
> feat(60309): Seleção de cargo na educação do servidor

- sme_ptrf_apps/core/api/serializers/ata_serializer.py
- sme_ptrf_apps/core/models/ata.py
- sme_ptrf_apps/core/services/associacoes_service.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_repasses_pendentes.py
- sme_ptrf_apps/core/tests/tests_services/tests_associacoes_service/test_repasses_pendentes_periodo_ate_agora_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_associacoes_service/test_tem_repasses_pendentes_periodos_ate_agora_service.py
Esse PR altera o retorno de informações de atas para incluir informação se a ata está ou não completa conforme alguns critérios.
História: [AB#59547](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59547)
> feat(59547) Atas de PC add informação sobre se ata está completa 

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_salva_devolucoes_ao_tesouro.py
Corrige: [AB#63574](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63574)
> fix(63574): Corrige duplicação das devoluções ao tesouro

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
Corrige: [AB#65643](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/65643)
> fix(65643): O saldo das PCs 2022.1 e 2021.3 da DRE Ipiranga exibe os dados da PC 2021.2

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/__init__.py
- sme_ptrf_apps/users/services/encerrar_acesso_de_suporte_service.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_encerrar_acesso_suporte_unidade.py
- sme_ptrf_apps/users/tests/tests_unidades_em_suporte/conftest.py
- sme_ptrf_apps/users/tests/tests_unidades_em_suporte/test_encerrar_acesso_suporte_service.py
Esse PR:
História: [AB#62837](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62837)
> feat(62837): Suporte às Unidades: Encerrar acesso de suporte 

- sme_ptrf_apps/users/api/serializers/user.py
- sme_ptrf_apps/users/services/get_unidades_usuario_service.py
- sme_ptrf_apps/users/tests/test_api_user/conftest.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_user.py
Esse PR:
História: [AB#66363](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66363)
> feat(66363): Suporte às Unidades: Exibir ícone de acesso suporte

- sme_ptrf_apps/core/api/views/atas_viewset.py
- sme_ptrf_apps/core/api/views/presentes_ata_viewset.py
- sme_ptrf_apps/core/models/ata.py
- sme_ptrf_apps/core/services/ata_service.py
- sme_ptrf_apps/core/tests/tests_services/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_ata_service/test_ata_service.py
Esse PR:
História: [AB#66366](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66366)
> feat(66366): Ata de apresentação: Exibir mensagem com os campos que faltam

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_get_lancamentos.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_tags_informacoes.py
- sme_ptrf_apps/despesas/tests/tests_despesas/test_despesa_tags_informacoes.py
Esse PR:
História: [AB#66784](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66784)
> feat(66784) Acompanhamento PC: Conferência de lançamentos: Etiquetas informativas e legendas

- sme_ptrf_apps/dre/admin.py
Esse PR altera o Admin de Comissões para:
História: [AB#66764](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66764)
> feat(66764) Cria no Admin de  Comissões ação para definir comissão de exame de contas

- sme_ptrf_apps/core/api/views/tipos_acerto_lancamento_viewset.py
- sme_ptrf_apps/core/models/tipo_acerto_lancamento.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/tipos_acerto_lancamento_service.py
- sme_ptrf_apps/core/tests/tests_api_tipos_acerto_lancamento/test_tipos_acerto_lancamento_endpoint_tabelas.py
- sme_ptrf_apps/core/tests/tests_services/tests_tipos_acertos_lancamentos_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_tipos_acertos_lancamentos_service/test_tipos_acertos_lancamentos_agrupa_por_categoria.py
feat(57620) Agrupar tipos de acerto por categoria
Esse PR:
História: [AB#57620](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57620)
> feat(57620) Agrupar tipos de acerto por categoria

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Altera a view /relatorios-consolidados-dre/info-execucao-financeira/ para retornar também o uuid do tipo de conta da justificativa de diferença.
[AB#70107](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70107)
> feat(70107): Inclui uuid tipo conta em info_execucao_financeira

- sme_ptrf_apps/dre/api/serializers/membro_comissao_serializer.py
- sme_ptrf_apps/dre/models/membro_comissao.py
- sme_ptrf_apps/dre/tests/tests_api_membros_comissoes/test_membro_comissao_create.py
- sme_ptrf_apps/dre/tests/tests_api_membros_comissoes/test_membro_comissao_update.py
Esse PR:
- Adiciona regra para não permitir cadastrar um membro duplicado
História: [AB#71868](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/71868)
> fix(71868)-comissoes: Sistema permite cadastro duplicado

- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/periodo_services.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tasks.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_painel_acoes.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_painel_acoes_de_uma_conta.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
- sme_ptrf_apps/core/tests/tests_services/tests_painel_resumo_recursos_service/test_painel_resumo_recursos_servico_cria_objeto.py
- sme_ptrf_apps/core/tests/tests_services/tests_painel_resumo_recursos_service/test_painel_resumo_recursos_servico_retorna_json.py
Esse PR:
História: [AB#58005](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58005)
> feat(58005) Acompanhamento de PC: Devolução de PC: Apagar fechamentos e docs apenas se necessário 

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_reabre_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/test_resumo_recursos_soma_despesas.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/test_resumo_recursos_soma_receitas.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_devolucoes_ao_tesouro_relatorio_consolidado_dre.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
- Altera o serviço de resumo de recursos para ignorar receitas inativas
- Cria testes para confirmar que despesas inativas estão sendo ignoradas.
História: [AB#73236](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73236)
> feat(73236) Alterar Resumo de Recursos para ignorar lançamentos inativos

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_reabre_prestacao_conta.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_devolucoes_ao_tesouro_relatorio_consolidado_dre.py
Esse PR:
História: [AB#72442](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72442)
> fix(72442) Ajuste teste devolucao tesouro

- sme_ptrf_apps/receitas/models/receita.py
Esse PR altera os cálculos dos relatórios de prestação de contas para ignorar os créditos inativos.
Relatórios afetados:
História: [AB#73238](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73238)
> feat(73238): Alterar relatórios pc para ignorar inativos

- sme_ptrf_apps/receitas/api/views/receita_viewset.py
- sme_ptrf_apps/receitas/models/receita.py
- sme_ptrf_apps/receitas/tests/conftest.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_inativar_ou_excluir_receita.py
Esse PR: 
- Altera o método de inativação de um estorno para desfazer o vínculo com o rateio estornado. 
- Altera as regras de exclusão de estorno para permitir a exclusão.
História: [AB#67647](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67647)
> feat(67647): Altera inativação de receita estorno

- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/conftest.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
História: [AB#73291](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73291)
> Feat(73291) Exibir lançamento inativos back-end

- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
Esse PR:
História [AB#73291](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73291)
> feat(73291) Adiciona teste para caso de rateios_de_conta_associacao

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/tests/tests_despesas/test_despesa_tags_informacoes.py
- sme_ptrf_apps/receitas/api/views/receita_viewset.py
- sme_ptrf_apps/receitas/models/receita.py
- sme_ptrf_apps/receitas/tests/test_receita/test_receita_tags_informacoes.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_get_receitas_tags_informacoes.py
esse PR:
História [AB#73292](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73292)
> Feat(73292) dre lancamentos inativos

- sme_ptrf_apps/core/models/associacao.py
Esse PR:
- Alterar o método que retorna a lista de períodos para geração de PC para não considerarem devoluções como PCs entregues.
Corrige: [AB#74340](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74340)
> fix(74340): Corrige lista períodos para PC

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/services/conciliacao_services.py
esse PR:
História: [AB#73239](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73239)
> Feat(73239) Desconsidera creditos inativos em conciliação bancária

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/serializers/solicitacao_devolucao_ao_tesouro_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/conftest.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_apaga_devolucoes_ao_tesouro.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_get_lancamentos_solicitacoes_acerto.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_apagar_devolucoes_ao_tesouro.py
- sme_ptrf_apps/core/tests/tests_solicitacao_acerto_lancamento/test_solicitacao_acerto_lancamento_model.py
Esse PR:
[X] Altera a API que traz as informações da tabela de devolução ao tesouro para usar o novo modelo. 
[X] Altera o salvamento de devolução ao tesouro parta criar o registro de devolução
[X] Cria endpoint e serviço para desfazer o registro de uma  devolução ao tesouro
[X] Altera retorno da API para o relatório após acertos para usar informações da nova tabela
[X] Altera retorno da API para o relatório de acertos para usar informações da nova tabela
História: [AB#75777](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/75777)
> feat(75777) Registro de devoluções ao tesouro

- sme_ptrf_apps/core/admin.py
Esse PR alterar o admin 16.6) Análises de documentos de PC
> feat(55129): Altera admin de análises de docs de PC

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/associacoes_service.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_pode_editar_campos_extrato.py
fix(76087): Conciliação bancaria
Esse PR:
- Adiciona seviço para verificar se os campos relacionados ao saldo bancario podem ser editados
- Adiciona endpoint para o novo serviço
- Adiciona função  para verificar se há ajustes bancarios ao modelo de AnalisePrestacaoConta
História: [AB#76087](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76087)
> fix(76087): Conciliação bancaria

- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/pdf.html
Esse PR:
História: [AB#76333](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76333)
> Feat(76333): Padronização dados relatorio acertos back

- sme_ptrf_apps/core/admin.py
Esse PR:
-[x] Aplicar um filtro que exiba todos os registros de determinado tipo de unidade;
-[x] Aplica um filtro que exiba todos os registros de determinada DRE;
-[x] Busca (search) pelo nome da associação.
História: [AB#52178](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52178)
> Feat(52178) filtro dre buscar nome associacao

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
- sme_ptrf_apps/users/models.py
Esse PR:
1. Alterar o __str__ de user para exibir RF e nome do usuário. 
2. Altera a exportação de créditos que estava passando o usuário como parâmetro onde era esperado o username.
[AB#50157](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50157)
> feat(50157): Altera identificação de usuários no AuditLog

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
Em conversa com a PO foi solicitado alterar a classificação de despesas de data_transacao para data de documento. Isso torna essa mudança desnecessária.
> feat(78548): Desfaz alterações anteriores devido a mudança pela PO

- sme_ptrf_apps/core/services/prestacao_contas_services.py
Passa a classificar as despesas por data de documento e não mais por data de transação na lista de lançamentos exibida no acompanhamento de prestações de contas.
Corrige [AB#78548](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/78548)
> fix(78548) Corrige ordem de despesas em lançamentos no Acompanhamento de PC

- sme_ptrf_apps/core/services/prestacao_contas_services.py
A API não estava referenciando a solicitacao_devolucao_ao_tesouro de uma solicitação de lançamentos sem verificar se a relação existia.
> fix(78589): Corrige gravação solicitação acerto lançamento

- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
Agora quando as solicitações de ajuste em lançamentos são copiadas para uma nova análise, o campo de referência à devolução ao tesouro da solicitação da análise anterior não é copiado.
Corrige [AB#78926](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/78926)
> fix(78926): Corrige exclusão indevida de devolução ao tesouro

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
A conclusão antes não apagava prévias parciais de um consolidado único ou prévias únicas de um consolidado parcial.
Corrige [AB#79038](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79038)
> fix(79038): Corrige conclusão consolidado dre

- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
Agora caso ocorra alguma exceção na geração de uma prévia de relatório de acertos, o status volta para "NÃO GERADO" permitindo ao usuário uma nova geração da prévia.
Corrige [AB#79496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79496)
> fix(79496): Inclui tratamento de erro em prévia de relatório de acertos

- config/settings/production.py
Agora erros ocorridos em processos Celery também alimentarão o Sentry.
[AB#79496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79496)
> fix(79496): Configura integração Celery e Sentry

- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-sintese-execucao-financeira.html
Corrige deslocamento na tabela do bloco 2 quando há uma justificativa de diferença de repasses informada.
O problema era causado por uma divergência no colSpan.
Corrige [AB#79315](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79315)
> fix(79315): Corrige layout do consolidado DRE

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/services/processos_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta_nao_recebidas.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta_todos_os_status.py
Informações de técnico, data de recebimento, data de última análise e devolução ao tesouro não eram incluídas nas consultas de alguns status de PC.
Corrige [AB#79837](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79837)
> fix(79837): Corrige lista de pcs para acompanhamento de PC

- sme_ptrf_apps/core/services/carga_previsao_repasse.py
- sme_ptrf_apps/core/tests/carga_previsao_repasse/test_carga_previsao.py
Corrige a ordem das colunas de valores para custeio, capital e livre. Estava sendo feito capital, custeio e livre.
[AB#80251](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80251)
> fix(hf.80251): Corrige carga de previsão de repasses

- sme_ptrf_apps/core/models/analise_lancamento_prestacao_conta.py
fix(80956): Status realizacao dev. tesouro
Esse PR:
- Adiciona regra para alterar status realizacao ao desfazer devolução ao tesouro
História: [AB#80956](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80956)
> fix(80956): Status realizacao dev. tesouro

- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
fix(80937): Remove termo opcional
Esse PR:
- Remove termo "opcional" do PDF
História: [AB#80937](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80937)
> fix(80937): Remove termo opcional

- sme_ptrf_apps/core/services/solicitacao_acerto_documento_service.py
- sme_ptrf_apps/core/services/solicitacao_acerto_lancamento_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_solicitacao_acertos_documento_service/test_service_solicitacao_acerto_documento.py
- sme_ptrf_apps/core/tests/tests_services/tests_solicitacao_acertos_lancamento_service/test_service_solicitacao_acerto_lancamento.py
-[x] Ajusta texto do back-end para "Não é possível marcar a solicitação como realizada Não foi possível alterar o status da solicitação, pois os ajustes solicitados não foram realizados."
História [AB#80933](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80933)
> feat(80933) Altera texto no back end e testes

- sme_ptrf_apps/static/css/pdf-relatorio-apos-acertos.css
Corrige as cores das tags de realizado e justificado no PDF do relatório após acertos.
Corrige [AB#82839](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82839)
> fix(82839): Corrige cores de tags no PDF do relatório após acertos

- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tasks.py
Esse PR:
- Altera a devolução de PC para não mais apagar fechamentos e relatórios no ao da devolução. 
- Altera o fechamento de uma PC devolvida para apagar os fechamentos e relatórios caso haja solicitações de correção que impliquem em mudanças em lançamentos, mas apenas se essas tiverem sido realizadas.
[AB#83304](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83304)
> feat(r6.83304) Alterações em devoluções de PCs

- sme_ptrf_apps/core/services/solicitacao_acerto_documento_service.py
- sme_ptrf_apps/core/services/solicitacao_acerto_lancamento_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_solicitacao_acertos_documento_service/test_service_solicitacao_acerto_documento.py
- sme_ptrf_apps/core/tests/tests_services/tests_solicitacao_acertos_lancamento_service/test_service_solicitacao_acerto_lancamento.py
feat(83473): Nao permitir justificar
Esse PR:
- Adiciona regra nas solicitacoes de lancamentos para não permitir justificar acertos que ja tenham sido realizados
- Adiciona regra nas solicitacoes de documentos para não permitir justificar acertos que ja tenham sido realizados
- Adiciona regra para voltar para status pendente quando o usuario tentar marcar como realizado um acerto justificado da categoria solicitação de esclarecimento
História: [AB#83473](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83473)
> feat(83473): Nao permitir justificar

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_reabre_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_monitora_prestacao_de_contas_service.py
Esse PR:
- Implementa Monitoramento de PC - Reversão sem apagar arquivos
História: [AB#85660](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85660)
> fix(85660): Monitoramento de PCs: reversão de devoluções não pode apagar os arquivos, apenas alterar o status para devolvido

- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/conftest.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_verifica_saldo_antes_put.py
Esse PR alterar a forma de verificar a suficiência de saldo no ato da edição de uma despesa.
Agora a aplicação, ao encontrar um fechamento na verificação de saldos para edição de uma despesa, passa a voltar com o valor original da despesa para o saldo antes de checar a suficiência. Anteriormente isso só ocorria no caso de períodos abertos (sem fechamentos).
[AB#85017](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85017)
> fix(85017): Corrige verificação de saldo em despesas com períodos fechados

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/conftest.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_desfazer_retificacao_consolidado.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_permite_retificacao.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_retornar_ja_publicados.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_retornar_pcs_do_consolidado.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_retornar_pcs_em_retificacao.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_retornar_pcs_retificaveis.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_pcs_do_consolidado.py
feat(81495): Incluir novas retificações
Esse PR:
- Adiciona endpoint para retornar PCs do consolidado
- Adiciona regras para controles dos botões
- Adiciona propertys ao modelo ConsolidadoDre para utilização na API
História: [AB#81495](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/81495)
> feat(81495): Incluir novas retificações

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_retornar_pcs_do_consolidado.py
Esse PR:
Atende [AB#85658](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85658)
> feat(85658): Ajustes pós integração com develop

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
Esse PR:
- Altera retorno API gerar_consolidado_de_publicacoes_parciais - EM_PROCESSAMENTO
História: [AB#85715](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85715)
> fix(85715): Relatório consolidado: o loading não é exibido corretamente na solicitação de geração do demonstrativo - Parte 02

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela_consolidado_das_publicacoes_parciais.html
Esse PR:
- altera o layout/nome das PCs apresentadas no PDF do consolidado
- altera a ordenação das PCs no consoldiado
- adiciona a referência atual de qual consolidado a PC nos dados físico-financeiros
História: [AB#81196](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/81196)
> feat(81196): Altera layout PDF Relatório Consolidado

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
Esse PR:
- Adiciona o campo referencia_consolidado_dre_original no teste de prestacao de conta
História: [AB#84790](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/84790)
> feat(84790): Adiciona campo no teste retrieve prestacao conta

- sme_ptrf_apps/core/services/tipos_acerto_lancamento_service.py
Esse PR:
- Altera em tipos_acerto_lancamento_service o retorno de informações sobre os tipos de solicitação de acerto para incluir informações sobre as categorias de conciliação e desconciliação.
História [AB#85901](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85901)
> feat(85901): Add info categorias de acerto em conciliação

- sme_ptrf_apps/dre/services/lauda_service.py
- sme_ptrf_apps/utils/string_to_float.py
Esse PR:
- Altera o serviço lauda_service adicionando uma verificação para não adicionar linhas de contas com valores nulos.
- Altera o serviço lauda_service adicionando uma verificação para não gerar (remover) a lauda caso as contas estejam zeradas ou não exista uma conta vinculada a PC.
- Adiciona uma função para transformar números no formato de string para float.
História: [AB#86930](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86930)
> feat(86930): Gerar laudas não exibir conta zerada na lauda

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
Esse PR:
- Corrige a exibição do bloco de "Consolidação das Publicações" que estava sendo exibido indevidamente em consolidados que não eram um consolidado geral.
- Corrige também um erro que ocorria na geração do consolidado geral que tentava verificar indevidamente a propriedade eh_retificacao.
Corrige [AB#89650](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89650)
> fix(89650): Corrige consolidado DRE

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_pode_reabrir.py
Esse PR:
- Renomeia no modelo de PC a função "pode_reabrir" por "pode_devolver". Já que o papel dela estava sendo usado para tratar apenas da devolução de PCs.
- Adiciona a verificação de tipos de acertos de lancamentos e documentos que demandam exclusão de documentos e fechamentos.
- Adiciona testes para cada caso de tipo de acerto na devolução de PCs.
História: [AB#89033](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89033)
> feat(89033):Permite devolução pc anterior com período consecutivo

- sme_ptrf_apps/core/models/associacao.py
Esse PR:
- Refatora o método que define a listagem de períodos na página de geração de documentos, levando em consideração as prestações de contas com acertos que não demandam exclusões e fechametos.
História: [AB#89232](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89232)
> feat(89232): Altera listagem de periodos na geração de documentos

- sme_ptrf_apps/core/models/associacao.py
Esse PR:
- Remove elementos duplicados na listagem de periodos.
História: [AB#89232](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89232)
> feat(89232): Remove duplicidade na listagem de periodos devolvidos

- sme_ptrf_apps/core/api/serializers/solicitacao_acerto_documento_serializer.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/models/solicitacao_acerto_documento.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_documentos/test_get_documentos_solicitacoes_acerto.py
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/partials/tabela-acertos-em-documentos.html
Esse PR:
- Adiciona uma property na model de solicitação de acerto de documento para resgatar a observação de conciliação para quando o tipo de acerto é edição de informação.
- Modifica serializer e testes que usam a nova property.
- Adiciona ao PDF da associação pós acerto o campo de observação.
História: [AB#88024](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88024)
> feat(88024): Adiciona campo justificativa e informações adicionais

- sme_ptrf_apps/core/admin.py
Esse PR:
- Adiciona o filtro por dre e a pesquisa por nome de unidade no admin de falha de geração de PC.
História: [AB#89625](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89625)
> feat(89625): Adicionar filtros falha geração de PC

- sme_ptrf_apps/sme/services/exporta_devolucao_tesouro_prestacoes_conta.py
- sme_ptrf_apps/sme/tasks.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_devolucao_tesouro/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_devolucao_tesouro/test_exportacoes_devolucao_tesouro_pc.py
Esse PR:
- Modifica a entidade base para a extração de dados que era as devoluções ao tesouro para as solicitações de devoluções ao tesouro.
- Adiciona o campo de justificativa de não realização da devolução ao tesouro.
- Altera soft time das tasks de extração de dados.
- Adiciona e melhora testes da extração de dados de devoluções ao tesouro.
- Adiciona método que adiciona indicativo de arquivo em processo de download na central de download.
História: [AB#90620](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90620)
> feat(90620): Extração devoluções ao tesouro

- sme_ptrf_apps/core/models/transferencia_eol.py
- sme_ptrf_apps/core/tests/tests_transferencia_eol/conftest.py
- sme_ptrf_apps/core/tests/tests_transferencia_eol/test_copiar_receitas_associacao_do_tipo_transferido.py
- sme_ptrf_apps/receitas/admin.py
Esse PR:
Resolve [AB#92293](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92293)
> fix(92293): Corrige cópia de entradas na transferência de EOL

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/models/transferencia_eol.py
- sme_ptrf_apps/core/tests/tests_transferencia_eol/conftest.py
- sme_ptrf_apps/core/tests/tests_transferencia_eol/test_copiar_receitas_associacao_do_tipo_transferido.py
- sme_ptrf_apps/receitas/admin.py
- sme_ptrf_apps/users/api/serializers/senha_serializer.py
- sme_ptrf_apps/users/api/views/senha_viewset.py
* Hotfix 7.1.1
Altera versão.
* fix(91941): Redefinição de senha (#1948)
Agora a redefinição de senha ira ocorrer sem erros
* fix(92293): transf eol (#1949)
* fix(92293): Corrige gravação de ação receita em transferência de EOL
Na transferência de eol a ação da receita copiada não estava sendo atualizado e ficava apontando para a da associação histórico.
* fix(92293): Melhora performance do admin de receitas
* fix(92293): Inclui testes para a cópia da ação e conta da entrada
---------
---------
> Hotfix/7.1.1 (#1951)

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_associacao/test_associacao_model.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_model.py
Esse PR:
- Altera `api/prestacoes-contas/dashboard` para ignorar associações encerradas conforme o período consultado
- Altera `api/prestacoes-contas/dashboard` para ignorar associações não iniciadas conforme o período consultado, se o parâmetro `desconsiderar não iniciadas` estiver ativo
Atende [AB#91685](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91685)
> feat(91685): Acomp PC cards ignorando encerradas e não iniciadas

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
Esse PR altera o bloco 3 (Execução Física) do consolidado físico financeiro para ignorar associações encerradas ou não iniciadas.
Atende [AB#91750](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91750)
> feat(91750): Consolidado físico-fin ignorando encerradas e não iniciadas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_associacao/test_associacao_model.py
Esse PR:
- Adiciona a verificação de associações sem o período inicial no modelo de associações.
- Adiciona nos testes de associação a verificação de associações não iniciadas.
- Modifica as tabelas de resumo geral do período e das dres e resumo por dre e unidade educacional.
História: [AB#91273](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91273)
> Feature(91273): Acompanhamento de PCs: Exibir associações correspondente ao período vigente

- sme_ptrf_apps/sme/api/views/saldos_bancarios_sme_detalhes_associacoes_viewset.py
- sme_ptrf_apps/sme/api/views/saldos_bancarios_sme_viewset.py
- sme_ptrf_apps/sme/services/saldo_bancario_service.py
Esse PR:
- Altera cálculo para desconsiderar associações não iniciadas e encerradas, conforme período da consulta na Exibição por Tipo de Unidade x Diretor, Unidade e Diretoria.
História: [AB#91686](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91686)
> Feature(91686): Exibir associações ativas na consulta de saldos

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_periodos_para_prestacao_contas.py
feat(91768): Exibir períodos que estejam sem encerramento da associação
Esse PR:
- Filtra periodos ate data de encerramento associacao
História: [AB#91768](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91768)
> feat(91768): Exibir períodos que estejam sem encerramento da associação

- Dockerfile
- requirements/base.txt
- requirements/local.txt
- requirements/production.txt
Esse PR:
- Atualiza no Dockerfile a versão do python para 3.9
- Atualiza a versão do pacote Pillow para 9.4.0
- Atualiza a versão do pacote psycopg2 para 2.9.5
Atende [AB#92877](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92877)
> build(92877): Atualiza Python para 3.9

- sme_ptrf_apps/receitas/services/carga_repasses_realizados.py
Esse PR:
- Valida se o período do repasse é válido de acordo com o período inicial da associação
- Valida se o período do repasse é válido de acordo com a data de encerramento da associação
História: [AB#93163](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93163)
> feat(93163): Valida data encerramento e periodo inicial da associacao na carga de repasses realizados

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_previstos.py
Esse PR:
- Valida se associação está encerrada
História: [AB#93197](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93197)
> feat(93197): Valida associações na carga de repasses previstos

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
Esse PR: 
- Corrige caso de prévias não apagadas e gerando documentos zerados
História: [AB#91797](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91797)
> fix(91797): Consolidado das PCs: Geração do Consolidado DRE - Caso de prévia não apagada e que causa erro na geração do bloco 2

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/serializers/unidade_serializer.py
- sme_ptrf_apps/core/models/unidade.py
- sme_ptrf_apps/core/tests/tests_api_unidades/test_list_unidades.py
feat(92322): Altera retorno da API de Unidades
Esse PR:
- Adiciona property ao modelo de Unidade para tooltip de associação encerrada
- Adiciona informações de encerramento da associação a API de unidades
História: [AB#92322](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92322)
> feat(92322): Altera retorno da API de Unidades

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta.py
Esse PR:
- Refatora alguns testes que apresentavam resultados que variavam a ordem de listas de execução para execução.
Atende [AB#92035](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92035)
> test(92035): Refatora testes unitários

- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_creditos.py/test_exportacoes_dados_creditos.py
Esse PR:
- Refatora o teste de exportação de créditos para "mockar" o serviço de exportação e testar apenas a chamada do endpoint.
Atende [AB#91110](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91110)
> test(9110): Refatora teste de exportação de créditos

- sme_ptrf_apps/core/services/carga_devolucoes_tesouro_service.py
- sme_ptrf_apps/core/tests/tests_devolucao_ao_tesouro/test_carrega_devolucoes_tesouro.py
Esse PR:
- Valida se o período da prestação de contas é válido de acordo com o período inicial da associação
- Valida se o período da prestação de contas é válido de acordo com a data de encerramento da associação
- Implementa testes
História: [AB#93200](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93200)
> feat(93200): Valida data encerramento e periodo inicial da associação na carga de devolução tesouro

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_com_filtros.py
Esse PR:
- Adiciona os filtros de tags de informação.
- Adiciona os filtros de tags de vínculo de atividades de rateios
- Adiciona ao serializer de despesas o campo informações com as tags de cada rateio, para a apresentação na listagem de despesas da associação.
História: [AB#89762](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89762)
> feat(89762): Tags informativas gastos escolas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/associacao.py
Esse PR:
- Corrige filtro de periodo seguinte na prestação de contas.
- Remove parâmetro sem uso em conftest.
História: [AB#91768](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91768)
> fix(91768): Corrige filtro de periodo seguinte na prestação de contas

- sme_ptrf_apps/core/api/serializers/acao_associacao_serializer.py
- sme_ptrf_apps/core/api/serializers/associacao_serializer.py
- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acoes_list_associacoes_nao_vinculadas.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acoes_associacoes_list.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_associacoes.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_associacoes_status_regularidade_ano.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_filtros.py
Esse PR:
- Adiciona informação sobre associação encerrada no retorno de ações da associação.
- Implementa filtro por informações
- Atualiza testes
- Implementa testes do filtro
História: [AB#93756](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93756)
> feat(93756): Não permitir selecionar associação encerrada

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/tests/tests_despesas/test_despesa_tags_informacoes.py
Esse PR:
- Adiciona as etiquetas de despesas não reconhecidas e sem comprovação fiscal.
História: [AB#94326](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94326)
> feat(94326): Adiciona etiquetas nos gastos da escola

- sme_ptrf_apps/core/api/views/acoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_acoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acoes_list_associacoes_nao_vinculadas.py
Esse PR:
- Implementa filtro por informações 
- Adiciona testes
Históia: [AB#92324](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92324)
> feat(92324): Adicionar filtro por informações nas rotas de associações não vinculadas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Implementa métodos para validar os cadastros e altera a rota de 'status-periodo' para retornar informação
- Modifica e adiciona testes
História: [AB#89001](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95819)
> feat(89001): Validar pendências de cadastro em concluir acerto/concluir período

- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/criar_acesso_de_suporte_service.py
- sme_ptrf_apps/users/services/encerrar_acesso_de_suporte_service.py
- A forma de criação dos acessos de suporte foi alterada para checar se o acesso de suporte já existia.
- Foram incluídos logs das operações
- Foram criados novos métodos de classe para a criação e remoção dos acessos
- O modelo de Unidades em Suporte passa a registrar suas mudanças no AuditLog
Resolve [AB#93404](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93404)
> fix(93404): Altera criação/remoção de acessos de suporte

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_cadastro.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Implementa rota para retorno de status do cadastro(dados da associação, membros e contas)
- Implementa testes
História: [AB#95557](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95557)
> feat(95557): Implementa rota status-cadastro

- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR:
- Modifia layout do pdf da ata de pcs para adicionar as informações de membros ausentes.
História: [AB#95845](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95845)
> feat(95845): Adiciona membros ausentes pdf ata de pcs

- sme_ptrf_apps/core/api/views/presentes_ata_viewset.py
- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR:
- Modifica o viewset de participantes na ata para apresentar os presentes em atas legados.
- Adiciona no PDF da ata o indicativo de ausência no conselho fiscal.
História: [AB#95653](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95653)
> feat(95653): Adiciona indicativo de membros conselho fiscal ausentes

- sme_ptrf_apps/dre/services/notificacao_service/class_notificacao_comentario_de_analise_consolidado_dre.py
Esse PR:
-  Resolve notificação enviada apenas para um técnico em Relatório Consolidado das DREs
História: [AB#91168](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91168)
> fix(91168): SME - Relatório Consolidado das DREs - Notificação só é enviada para um técnico DRE

- Dockerfile
- requirements/local.txt
Esse PR:
- Atualiza Dockerfile para usar a versão 3.10
- Atualiza dependências impactadas: mypy, django-stubs, pytest, pytest-django e pytest-sugar
AB#96048
> Feature/96046 Update python para 3.10.*

- requirements/base.txt
Esse PR:
- Atualiza a versão do Celery para 5.1.2. Requerido pela Python 3.10
Atende [AB#96046](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96046)
> build(96046): Atualiza Celery para 5.1.2

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Corrige Retificação do Consolidado PC ata não acompanha a retificação
História: [AB#97031](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/97031)
> fix(97031): Retificação do Consolidado PC: ata não acompanha a retificação

- sme_ptrf_apps/dre/services/dados_relatorio_devolucao_acertos_sme_service.py
- sme_ptrf_apps/static/css/pdf-relatorio-devolucao-acertos-sme.css
- sme_ptrf_apps/templates/pdf/relatorio_devolucao_acertos_sme/pdf.html
Esse PR:
- Adiciona marca d'água na prévia de devoluções para acertos
História: [AB#96965](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96965)
> feat(96965): Adiciona marca d'água na prévia de devoluções para acertos

- sme_ptrf_apps/core/services/relacao_bens_dados_service.py
- sme_ptrf_apps/static/css/relacao-de-bens-pdf.css
- sme_ptrf_apps/templates/pdf/relacao_de_bens/pdf.html
Esse PR:
- Adiciona a marca d'agua na prévia de relação de bens.
- Remove bloco de autenticação quando é uma prévia.
História: [AB#96758](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96758)
> feat(96758): Adiciona marca dagua na prévia de relação bens

- sme_ptrf_apps/core/models/associacao.py
O e-mail da unidade deixa de ser obrigatório para a geração de PCs.
> feat(97983): Remove obrigatoriedade do e-mail de unidades para PCs

- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_devolver_consolidado_dre.py
Esse PR:
- Corrige um teste que estava quebrando o build 8.4.0
O teste usava uma data fixa que passou a quebrar o teste em 01/07/2023. Foi feita a correção mais simples, jogar a data de teste para um futuro que não será atingido.
[AB#97748](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/97748)
> test(97748): Corrige teste que estava quebrando o deploy

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/analise_conta_prestacao_conta_viewset.py
Esse PR:
- Ajusta recebimento paramentros AnaliseContaPC e implementa raw_id_fields em admin de AnaliseContaPC
História: [AB#97899](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/97899)
> feat(97899): Acompanhamento de PC: Incluir acerto para o Comprovante do Saldo da Conta

- sme_ptrf_apps/sme/tasks.py
Esse PR:
- Adiciona um filtro para remover as solicitações da mesma despesa que se repetem nas devoluções subsequentes da prestação de conta.
História: [AB#95910](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95910)
> feat(95910): Remove solicitações antigas da extração de devolução

- sme_ptrf_apps/core/api/serializers/motivo_rejeicao_encerramento_conta_associacao_serializer.py
Esse PR:
- Adiciona o id para apresentação no modal de edição do motivo de rejeição do encerramento da conta.
História: [AB#87224](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/87224)
> feat(87224): Adiciona parametrizacao motivos rejeicao encerramento conta

- sme_ptrf_apps/sme/services/exporta_status_prestacoes_conta_service.py
Esse PR:
- Concatena motivos de reprovacao e aprovacao com resalva na extração de dados da PC, modificando a forma em que os dados no serviço de exportação são montados.
História: [AB#99079](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99079)
> feat(99079): Concatena motivos de reprovacao e aprovacao com resalva

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/tests/tests_associacao/test_associacao_viewset.py
Esse PR:
-  Implementa managers para contas ativas e encerradas e adiciona rota de contas encerradas
História: [AB#99318](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99318)
> feat(99318): Histórico de contas encerradas

- sme_ptrf_apps/core/models/prestacao_conta.py
Esse PR:
- Implementa uma modificação no status da análise para "devolvida" antes de salvar a referência da analise_atual.  Removendo qualquer possibilidade de conflitos de referências utilizadas em um eventual rollback.
História: [AB#93854](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93854)
> fix(93854): Adiciona atribuição status análise dentro da transaction

- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/conftest.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_delete_despesas.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_post_despesas.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_put_despesas.py
Esse PR:
- Valida rateios com conta inativa
- Valida deletar despesa
- Atualiza testes 
História: AB#48770
> feat(48770): Tratamento contas encerradas em gastos

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/services/filtra_despesas_por_tags.py
Esse PR:
- Adiciona a etiqueta de imposto a ser pago nas despesas da unidade e na conferência de lançamento da DRE.
- Refatora filtro de tags para unificar em um único método, remove iterações desnecessárias.
História: AB#101135
> feat(101135): Adiciona etiqueta de imposto a ser pago

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
feat(48776): Acompanhamento PC, tratamento de contas encerradas
Esse PR:
- Adiciona função ao modelo de PC para retornar contas ativas no periodo dessa PC
- Altera função get_contas_com_movimento para não retornar contas inativas no periodo dessa PC
História: AB#48776
> feat(48776): Acompanhamento PC, tratamento de contas encerradas

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tasks.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_associacoes_endpoint.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_contas_ativas_no_periodo.py
feat(48775): Encerramento conta, geração de documentos PC
Esse PR:
- Adiciona endpoint para retornar contas ativas no periodo
- Altera método de concluir prestação de contas para não considerar contas inativas anterior ao periodo
História: AB#48775
> feat(48775): Encerramento conta, geração de documentos PC

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/serializers/solicitacao_encerramento_conta_associacao_serializer.py
- sme_ptrf_apps/core/models/conta_associacao.py
feat(101137): Encerramento conta, valores reprogramados
Esse PR:
- Adiciona funções para validar valores reprogramados ao solicitar encerramento de conta
- Adiciona validação ao serializer da API de encerramento de conta
- Adiciona mensagem de sucesso a API de encerramento de conta
História: AB#101137
> feat(101137): Encerramento conta, valores reprogramados

- sme_ptrf_apps/core/models/notificacao.py
- sme_ptrf_apps/core/tests/tests_notificacoes_services/test_notificacoes_envia_email.py
Esse PR:
- Adiciona uma verificação para apenas enviar e-mails quando estiver em ambiente de produção.
História: AB#100876
> feat(100876): Bloqueia o envio de emails fora do ambiente producao

- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/pdf.html
Esse PR:
- Modifica no downlaod da ata a data da assinatura para a data de preenchimento da reunião.
História: AB#100076
> feat(100076): Utiliza a data da reunião na assinatura da ata

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
Esse PR:
- Alterar o retorno de informações de extrato para incluir as informações de encerramento da conta sem sobrepor a data e saldo do extrato informados.
Atende AB#103003
> feat(103003): Altera informações de extrato retornadas pela API

- sme_ptrf_apps/core/tests/tests_conta_associacao/test_conta_associacao_conta_criada_no_periodo_ou_periodo_anteriores_metodo.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
feat(102525): Incluir info pcs retificadas ao consolidado geral
Esse PR:
- Altera calculo para definir quantidade de pc publicadas anteriormente quando for consolidado geral
- Adiciona testes para a função de validar data de inicio da conta
História: AB#102525
> feat(102525): Incluir info pcs retificadas ao consolidado geral

- sme_ptrf_apps/core/api/views/solicitacao_encerramento_conta_associacao_viewset.py
- sme_ptrf_apps/core/tests/tests_api_solicitacao_encerramento_conta_associacao/test_solicitacao_encerramento_update.py
Esse PR:
- Ativa novamente a conta quando a solicitação de encerramento é rejeitada.
- Adiciona teste.
> feat(101655): Ativa conta na solicitacao encerramento rejeitada

- config/settings/base.py
- requirements/base.txt
- requirements/local.txt
- sme_ptrf_apps/users/forms.py
- sme_ptrf_apps/users/models.py
Esse PR:
- Atualiza a versão do Django para o último patch de segurança (3.2.21)
- Atualiza a versão de vários pacotes em preparação para a atualização para o Django 4.1.
- Altera usos da lib django.utils.translation deprecados no Django 3 e removidos no Django 4.
Atende AB#101828
> feat(101828): Atualização para Django 3.2.21 e preparação para Django 4.1

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Adiciona informação de conta encerrada com saldo no retorno de status período
História: AB#104193
> feat(104193): Adiciona informação de conta encerrada com saldo no retorno de status período

- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
Esse PR:
- Adiciona a validação para não permitir adicionar créditos em contas que não foram iniciadas ainda.
História: AB#103823
> feat(103823): Tratamento data inicial conta no crédito da escola

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Adiciona o retorno dos tipos de contas que estão encerradas e com saldos diferentes de zero.
História: AB#104192
> feat(104192): Não permite concluir analise pc com conta não zerada

- config/settings/base.py
- requirements/base.txt
- requirements/local.txt
- requirements/production.txt
- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/tests/conftest.py
- sme_ptrf_apps/jwt_middleware.py
- sme_ptrf_apps/receitas/tests/conftest.py
- sme_ptrf_apps/users/api/views/login.py
Esse PR:
- Instala e configura o pacote djangorestframework-simplejwt
- Remove dos requirements o pacote djangorestframework-jwt
- Altera o middleware que injeta o usuário na requisição para que passe a usar a nova lib
- Altera a view de login para que passe a usar a nova lib
- Faz reorganização dos arquivos de requirements
Atende AB#104709
> feat(104709): Substitui a lib de autenticação JWT por outra compatível com Django 4

- requirements/local.txt
Esse PR:
- Adiciona o pytest-factoryboy que facilita a combinação da abordagem de factories para a configuração de testes com a injeção de dependência, que é o cerne das fixtures do pytest.
> test: Adiciona library pytest-factoryboy

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_put_despesas.py
Esse PR:
- Valida data_transacao da depesa de acordo com o período da pc devolvida
- Ajusta update de despesa para registrar logs corretamente
- Adiciona teste de validação de data_transacao
História: AB#106328
> fix(106328): Valida data_transacao da depesa de acordo com o período da pc devolvida

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-execucao-fisica.html
Esse PR:
- Adiciona no relatório consolidado de publicações parciais o número de unidades que tiveram uma pc pelo menos uma vez retificada.
- Modifica a nota explicativa do relatório.
- Cria serviço para verificar quando o relatório é consolidado de publicações parciais.
História: AB#105498
> feat(105498): Adicionar no relatorio consolidado unidades retificadas

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/fixtures/factories/tipo_conta_factory.py
- sme_ptrf_apps/core/tests/test_api_contas/test_get_contas.py
Esse PR:
- Remove contas sem data de inicio do retorno da API.
- Corrige factory de tipos de contas.
- Adiciona teste relacionado.
HIstória: AB#106214
> fix(106214): Remove contas sem data de inicio do retorno da API

- sme_ptrf_apps/dre/services/valores_reprogramados_dre_service.py
Esse PR:
- Altera o método que retorna a estrutura dos valores reprogramados para desconsiderar contas ainda não iniciadas. 
Resolve AB#107380
> fix(107380): Ignora contas não iniciadas para valores reprogramados

- requirements/base.txt
- requirements/local.txt
- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/models/fechamento_periodo.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_implantacao_saldos.py
Esse PR:
- Atualiza o Django para a versão 4.2.7
- Ajusta o código do método de implantação de saldo para se adequar a nova versão
- Atualiza o pacote Werkzeug para resolver vulnerabilidade
- Remove bloco de código comentado
Atende AB#103306
> feat(103306): Atualiza Django para  4.2.7

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/fixtures/factories/acao_associacao_factory.py
- sme_ptrf_apps/core/fixtures/factories/acao_factory.py
- sme_ptrf_apps/core/fixtures/factories/arquivo_factory.py
- sme_ptrf_apps/core/fixtures/factories/periodo_factory.py
- sme_ptrf_apps/core/fixtures/factories/solicitacao_encerramento_conta_associacao_factory.py
- sme_ptrf_apps/core/fixtures/providers/arquivo_provider.py
- sme_ptrf_apps/core/fixtures/providers/solicitacao_encerramento_conta_associacao_provider.py
- sme_ptrf_apps/receitas/services/carga_repasses_realizados.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_realizados.py
Esse PR:
- Adiciona a verificação de conta encerrada para arquivos de carga de repasses realizados.
- Adiciona teste e factories relacionadas.
História: AB#108932
> feat(108932): Não permitir carga repasse realizados conta encerrada

- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
Esse PR:
- Adiciona a verificação de conta encerrada para arquivos de carga de repasses previstos.
História: AB#108933
> feat(108933): Nao permitir carga repasse previso em contas encerradas

- sme_ptrf_apps/core/models/conta_associacao.py
Esse PR:
- Adiciona a validação de quando os status de valores reprogramados forem corretos, a primeira PC não existe e não existe nenhum campo de valor reprogramado preenchido a conta da associação pode ser encerrada.
História: AB#108777
> fix(108777): Corrige validacao primeira PC com valores corretos

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/fixtures/factories/acao_associacao_factory.py
- sme_ptrf_apps/core/fixtures/factories/acao_factory.py
- sme_ptrf_apps/core/fixtures/factories/fechamento_periodo_factory.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_info_por_acao_services/test_saldos_insuficientes_para_rateios.py
- sme_ptrf_apps/despesas/fixtures/factories/despesa_factory.py
- sme_ptrf_apps/despesas/fixtures/factories/rateio_despesa_factory.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_verifica_saldo_antes_post.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_verifica_saldo_antes_put.py
Esse PR:
- Adiciona a verificação por ação e aplicação dentro de cada conta no momento de cadastro de uma despesa.
- Modifica serviço saldos_insuficientes_para_rateios para contemplar contas.
- Adiciona factories e testes relacionados.
História: AB#109692
> feat(109692): Adiciona verificacao conta quando saldo insuficiente

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/proccessos_associacao.py
- sme_ptrf_apps/core/services/processos_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_recebe_prestacao_conta.py
Esse PR:
- Adiciona o serviço para tratar o processo SEI ao receber PCS.
- Altera view de recebimento de PC.
- Altera ordenação resgate de processos SEI.
História: AB#108442
> feat(108442): Adiciona servico tratar processo ser receber PC

- sme_ptrf_apps/core/tests/tests_carga_associacoes_service/test_carga_associacoes_service.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_gestao_usuario.py
Remove testes que passaram a quebrar após mudanças na API SME Integração. Os testes deveriam estar mocando essa API, mas isso não está sendo feito.
Serão abertos débitos técnicos para ajuste.
AB#110537
> test(110537): Retira testes quebrando após mudança SMEIntegração

- sme_ptrf_apps/core/services/falha_geracao_pc_service.py
- sme_ptrf_apps/core/services/prestacao_conta_service.py
- sme_ptrf_apps/core/tasks/calcular_prestacao_de_contas.py
- sme_ptrf_apps/core/tasks/gerar_demonstrativo_financeiro.py
- sme_ptrf_apps/core/tasks/gerar_relacao_de_bens.py
Esse PR:
- Altera o novo processo de PC para só gerar os PDFs de demonstrativos financeiros e relações de bens se for necessário.
- Ajusta a task de término de PC para não considerar falha a inexistência de relações de bens.
- Faz algumas refatorações para melhorar legibilidade do código.  
Atende AB#111777
> feat(111777) Geração de PDFs dos documentos de PC apenas quando necessário

- sme_ptrf_apps/users/tests/test_user_v2/test_service_gestao_usuario.py
Esse PR:
- Refaz mocks test_retorna_lista_unidades_servidor_com_direito_sme
História: AB#111100
> tec(111100): Rever mocks da API SMEIntegração no teste test_retorna_lista_unidades_servidor_com_direito_sme

- sme_ptrf_apps/logging/handlers.py
Esse PR:
- Alterar o ContextualLogger para usar "SigEscola.API" como valor padrão do campo "aplicacao", caso um valor não seja informado.
Atende AB#112526
> feat(112526): Define aplicação padrão no ContextualLogger

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
Esse PR:
- Adiciona a possibilidade de filtro por código EOL no acompanhamento de PCs das visões DRE e SME.
Atende AB#112851 e AB#112852
> feat(112851): Filtro por código EOL no acompanhamento de PC (DRE e SME)

- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_previstos.py
Esse PR alterar a carga de repasses previsto:
- Valida a existência de PC para a associação no período e não cria o repasse previsto se existir a PC.
Atende AB#116372
> feat(116372): Valida existência de PC em carga de repasse

- sme_ptrf_apps/receitas/services/carga_repasses_realizados.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_realizados.py
Esse PR alterar a carga de repasses realizados:
- Valida a existência de PC para a associação no período e não cria o repasse realizado caso exista uma PC
Atende AB#116380
> feat(116380): Valida existência de PC em carga de repasse

- sme_ptrf_apps/core/admin.py
Esse PR:
- Adiciona filtro por dre nas previsões de repasse;
- Troca campos para raw_id otimizando carregamento e busca;
- Adiciona codigo_eol na listagem do admin.
História: AB#116402
> feat(116402): Adiciona filtro dre previsoes repasses

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/fixtures/factories/prestacao_conta_factory.py
- sme_ptrf_apps/core/fixtures/factories/solicitacao_acerto_lancamento_factory.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_dados_relatorio_acertos.py
Esse PR:
- Adiciona teste relacionado com os dados das despesas de periodos anteriores no relatorio de acertos.
História: AB#101267
> feat(101267): Adiciona teste dados despesas periodos anteriores

- sme_ptrf_apps/core/api/views/tipos_acerto_lancamento_viewset.py
- sme_ptrf_apps/core/models/tipo_acerto_lancamento.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/services/tipos_acerto_lancamento_service.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/core/tests/tests_services/tests_tipos_acertos_lancamentos_service/test_service_endpoint_tabelas_lancamentos.py
feat(117548): Conferencia de lancamentos
Esse PR:
- Altera serviço de agrupar por categoria para ignorar categorias dependendo do parametro
- Adiciona campo "is_repasse" ao serializer de analise_lancamento
História: AB#117548
> feat(117548): Conferencia de lancamentos

- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_previstos.py
Esse PR:
- Alterar a carga de repasses previstos para recusar a carga caso já exista alguma PC no período do repasse.
Atende AB#116372
> feat(116372): Carga de repasses previstos valida pc

- sme_ptrf_apps/receitas/services/carga_repasses_realizados.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_realizados.py
Esse PR:
- Altera a carga de repasses realizados para recusar a carga caso exista
alguma linha com período que tenha PC.
Atende AB#116380
> feat(116380): Carga de repasses realizados validando pc

- sme_ptrf_apps/sme/services/exporta_documentos_despesas.py
Esse PR corrige um erro não exportação de despesas que quebrava o arquivo CSV quando algum dos campos exportados possuía em seu conteúdo algum ponto-e-virgula.
Resolve [AB#119102](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119102)
> fix(119102): Quebra do CSV de despesas quando contém ";"

- sme_ptrf_apps/core/api/serializers/processo_associacao_serializer.py
- sme_ptrf_apps/core/fixtures/factories/unidade_factory.py
- sme_ptrf_apps/core/tests/tests_api_processos_associacoes/test_processo_associacao_create.py
- sme_ptrf_apps/core/tests/tests_api_processos_associacoes/test_processo_associacao_update.py
Esse PR:
- Adicione validação para evitar o cadastro de processos SEI com o mesmo número no mesmo ano.
História: [AB#118811](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118811)
> feat(118811): Nao permitir mesmo numero processo sei no mesmo ano

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/tasks/__init__.py
- sme_ptrf_apps/core/tasks/migra_campos_presidente_secretario_atas.py
Esse PR:
- Implementa tarefa assíncrona que migra os antigos campos texto de presidente secretário para os novos campos que são FK de participantes da ata.
Resolve [AB#119271](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119271)
> feat(119271): Migração presidentes secretários de atas

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/tasks/migra_campos_presidente_secretario_atas.py
Esse PR:
- Altera a migração de presidentes e secretários das
atas para na busca ignorar a diferença entre maiúsculas
e minúsculas e também acentuação.
- Inclui no admin de atas as colunas  presidente e secretário
[AB#119271](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119271)
> feat(119271): Migração atas ignorar acentos e case

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/tasks/migra_campos_presidente_secretario_atas.py
Esse PR:
- Altera a migração  de presidente secretário de ata para que a migração seja  feita mesmo que falte apenas um dos cargos.
- A flag "**rever**" passa a ser reavaliada antes do início do processo para todas as atas que tem a flag.
- Altera o admin de participantes de atas incluindo um filtro por tipo de ata.
[AB#119271](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119271)
> feat(119271): Altera migração presidente secretário atas

- sme_ptrf_apps/core/services/persistencia_dados_demo_financeiro_service.py
Esse PR:
- Corrige a persistência de dados do demonstrativo financeiro, criando uma condição que evita tentar transformar uma data inexistente de uma despesa do tipo imposto.
História: [AB#120372](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120372)
> fix(120372): Corrige persistencia imposto sem data no demo financeiro

- sme_ptrf_apps/receitas/admin.py
Esse PR:
- Corrige a verificação da quantidade de unidades cadastradas que já possuem uma receita do tipo de receita cadastrado e estão sendo removidas da lista de unidades do tipo de receita pelo admin.
História: [AB#120329](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120329)
> fix(120329): Corrige validacao unidades faltantes com tipo receita cadastrado

- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/services/despesa_service.py
Esse PR implementa a migração dos novos campos que marcam despesas de períodos anteriores.
Obs: Esse PR corrige o código de um PR anterior que tinha um erro de lógica.
AB#122906
> fix(122906): Despesa periodo anterior editável

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
Esse PR:
- Comenta regra de mostrar despesas de períodos anteriores no cenário de primeiro período ativo da associação.
História: AB#122998
> fix(122998): Comenta regra de mostrar despesas de periodos anteriores no cenário de primeiro período ativo da associação.

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- Corrige valor parâmetro incluir_inativas em rateios_da_conta_associacao_em_periodos_anteriores de acordo com a regra de negócio correta
História: [AB#123089](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/123089)
> fix(123089): Corrige filtro de rateios de períodos anteriores

- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_unidades/test_exportacoes_unidades.py
Inclusão de acentuação no cabeçalho dos testes unitários em relação ao valor esperado do CSV gerado
> Inclusão de acento nos testes unitários

- sme_ptrf_apps/core/services/carga_previsao_repasse.py
- sme_ptrf_apps/core/tests/carga_previsao_repasse/test_carga_previsao.py
- Agrupa dados por eol, conta e período, para somar valores de uma mesma conta e não duplicar durante a criação de registros de repasses.
- Atualiza testes
AB#125001
> fix(125001): Corrige regra na importação de carga de repasses previstos

- sme_ptrf_apps/core/services/carga_contas_associacoes_service.py
Esse PR:
Inclui o campo número de cartão, adicionado posteriormente conforme o modelo de carga atualizado na história.
História AB#124991
> feat(124991): carga contas associacoes inclui cartao - develop

- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acoes_associacoes_list.py
Esse PR:
Atualiza os testes unitários de Ações Associações devido à atualização de serializer para retorno de receitas previstas PAA
História AB#124771
> test(124771): inclusão de receitas previstas paa nos testes de acoes associações

- sme_ptrf_apps/core/api/views/categorias_pdde_viewset.py
Esse PR:
-Ajustes na regra de adição e edição de categoria pdde para não permitir nomes repetidos case sensitive
História: AB#126749
> feat(126749): Ajuste na regra de nome duplicado na criação e edição de categoria pdde

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/tests/tests_acoes_pdde/conftest.py
- sme_ptrf_apps/core/tests/tests_acoes_pdde/test_acoes_pdde_model.py
- sme_ptrf_apps/core/tests/tests_categoria_pdde/conftest.py
- sme_ptrf_apps/core/tests/tests_categoria_pdde/test_categoria_pdde_viewset.py
Esse PR:
- Adição de testes unitários para os novos cenários de exclusão de categoria pdde;
- Aumento na cobertura de testes
- Correção de conflito de merge
História: AB#126749
> feat(126749): Adição de testes unitários para os novos cenários de exclusão de categoria pdde

- sme_ptrf_apps/core/admin.py
Esse PR:
-Ajuste na classe LogEntryAdmin para evitar erro de localtime/timezone ao exibir a listagem no admin devido à atualização da lib
História: AB#127758
> feat(127758): Ajustes no LogEntryAdmin

- sme_ptrf_apps/despesas/api/serializers/especificacao_material_servico_serializer.py
- sme_ptrf_apps/despesas/api/serializers/tipo_custeio_serializer.py
- sme_ptrf_apps/despesas/models/especificacao_material_servico.py
- sme_ptrf_apps/paa/admin.py
- sme_ptrf_apps/paa/api/serializers/__init__.py
- sme_ptrf_apps/paa/api/serializers/acao_pdde_serializer.py
- sme_ptrf_apps/paa/api/serializers/prioridade_paa_serializer.py
- sme_ptrf_apps/paa/api/serializers/programa_pdde_serializer.py
- sme_ptrf_apps/paa/api/views/prioridade_paa_viewset.py
- sme_ptrf_apps/paa/models/prioridade_paa.py
- sme_ptrf_apps/paa/querysets.py
Esse PR:
- Adiciona filtros de queryset e ordenação customizada. 
- Ordenação reutilizada no django admin.
- Inclusão de Serializers simplificados para compor o Serializer de listagem de Prioridades
História [AB#127464](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127464)
> feat(127464): Listagem e ordenação de Prioridade PAA

- sme_ptrf_apps/despesas/api/serializers/especificacao_material_servico_serializer.py
- sme_ptrf_apps/despesas/api/serializers/tipo_custeio_serializer.py
- sme_ptrf_apps/despesas/models/especificacao_material_servico.py
- sme_ptrf_apps/paa/admin.py
- sme_ptrf_apps/paa/api/serializers/__init__.py
- sme_ptrf_apps/paa/api/serializers/acao_pdde_serializer.py
- sme_ptrf_apps/paa/api/serializers/prioridade_paa_serializer.py
- sme_ptrf_apps/paa/api/serializers/programa_pdde_serializer.py
- sme_ptrf_apps/paa/api/views/prioridade_paa_viewset.py
- sme_ptrf_apps/paa/models/prioridade_paa.py
- sme_ptrf_apps/paa/querysets.py
Esse PR:
- Adiciona filtros de queryset e ordenação customizada. 
- Ordenação reutilizada no django admin.
- Inclusão de Serializers simplificados para compor o Serializer de listagem de Prioridades
História [AB#127464](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127464)
> feat(127464): Listagem e ordenação de Prioridade PAA - Homolog

- sme_ptrf_apps/paa/api/serializers/__init__.py
- sme_ptrf_apps/paa/api/serializers/prioridade_paa_serializer.py
- sme_ptrf_apps/paa/api/views/prioridade_paa_viewset.py
Esse PR:
- Refatora e reaproveita o Serializer de criação para alteração(também)
- Inclui novos campos de objeto para separação de campos referentes à chaves estrangeiras para exclusividade no form de edição
História [AB#127466](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127466)
> feat(127466): Refatoração de Serializer para implementação de edição - develop

- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_e_adquirido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/tests/viewsets/test_bem_produzido_viewset.py
Esse PR:
- Adiciona o uuid de despesas para roteamento no front-end em situação patrimonial;
- Altera listagem de bens para retornar todos os rateios, mesmo os que não estão sendo utilizados no bem.
História: [AB#129379](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129379)
> feat(129379): Adiciona visualização despesa em situação patrimonial

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_observacoes.py
- Corrige cenário em que a DRE não solicita acerto para todas as contas e os campos da conciliação ficam desabilitados, impossibilitando a UE de gerar documentos.
[AB#131974](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/131974)
> feat(131974): Corrige cenário de acerto em extrato

- sme_ptrf_apps/paa/services/resumo_prioridades_service.py
- sme_ptrf_apps/paa/tests/services/conftest.py
- sme_ptrf_apps/paa/tests/services/test_resumo_prioridades.py
Esse PR:
Adiciona o cálculo de Livre aplicação para Ações PDDE no Resumo de Recursos de PAA
Historia [AB#127462](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127462)
> feature(127462): Inclusão de Livre aplicação de Acoes PDDE -homolog

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/ajuste_services.py
- sme_ptrf_apps/core/tests/services/test_ajuste_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_recebe_prestacao_conta_apos_acertos.py
Esse PR:
- Adiciona um ajuste que permite o recebimento de PC após acerto quando possui apenas ajuste externo e/ou solicitação de esclarecimento.
História: AB#134733
> hotfix(134733): Ajuste no recebimento após acerto

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/fixtures/factories/__init__.py
- sme_ptrf_apps/core/fixtures/factories/analise_conta_prestacao_conta_factory.py
- sme_ptrf_apps/core/fixtures/factories/pdf_factory.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
- sme_ptrf_apps/core/tests/services/test_analise_prestacao_conta_service.py
- sme_ptrf_apps/core/tests/tests_analise_prestacao_conta/test_analise_prestacao_conta_model.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_conclui_analise_prestacao_conta_como_devolvida.py
Esse PR:
- Atualiza retrieve de prestação de contas com informações sobre acertos que podem alterar saldo da conciliação e contas com pendência sem solicitação de acerto
- Implementa função para criar solicitação de acerto em cenários de PCs devolvidas com pendências
- Implementa testes unitários para os novos métodos da class de análise da prestação de conta e service
[AB#134188](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/134188)
> feat(134188): Acompanhamento de PC: Incluir alerta sobre a inclusão de acertos que podem alterar a conciliação bancária

- sme_ptrf_apps/core/services/prestacao_conta_service.py
- sme_ptrf_apps/core/services/resumo_rescursos_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_prestacao_de_contas_service.py
- Comenta retorno de contas pendentes para inibir validação até que as regras de acertos sejam revisadas
[AB#134189](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/134189)
> feat(134189): Comentar: Concluir acerto: Validar se houve alteração no saldo bancário e não permitir a conclusão dos acertos
