prefeiturasp/SME-PTRF-BackEnd

- sme_ptrf_apps/core/services/solicitacao_acerto_documento_service.py
feat(83473): Nao permitir justificar
Esse PR:
- Realiza ajuste no serviço de justificar documento
História: [AB#83473](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83473)
> feat(83473): Nao permitir justificar

- sme_ptrf_apps/dre/api/serializers/validation_serializers/consolidado_dre_editar_motivo_retificacao.py
- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_update_motivo_retificacao.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_update_motivo_retificacao.py
Esse PR:
- Adiciona action update motivo
- Adiciona testes de validação do motivo
- Adiciona serviço para atualizar o motivo
História: [AB#80011](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80011)
> feat(80011) retificacao editar motivo

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
feat(80031): Retificacao relatorio fisico financeiro
Esse PR:
- Altera serviço que retorna informações de execucao fisico financeiras, para considerar retificacoes
História: [AB#80031](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80031)
> feat(80031): Retificacao relatorio fisico financeiro

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
[AB#85049](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85049)
> Update homolog 03 fev23 10h27m

- sme_ptrf_apps/despesas/admin.py
fix(85204): Conciliacao reabertura seletiva
Esse PR:
- Adiciona auto complete ao admin de Despesas e rateios
História: [AB#85204](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85204)
> fix(85204): Conciliacao reabertura seletiva

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/tests/tests_services/conftest.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_trilha_de_status.py
[AB#85049](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85049)
> Update homolog 06 fev23 10h35m

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tasks.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_cria_documentos_relatorios_fisicos_financeiros.py
feat(80606): Gerar documentos retificacao
Esse PR:
- Altera serviço de publicar consolidado para considerar uma retificação
- Altera serviços relacionados a publicacao para considerarem uma retificacao
- Altera regras para estado dos botões
História: [AB#80606](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80606)
> feat(80606): Gerar documentos retificacao

- sme_ptrf_apps/dre/services/lauda_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
feat(74495): Retificação lauda
Esse PR:
- Altera serviço de geração da lauda para considerar uma retificação
História: [AB#74495](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74495)
> feat(74495): Retificação lauda

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/lauda_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tasks.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_cria_documentos_relatorios_fisicos_financeiros.py
[AB#85049](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85049)
> Update homolog 09 fev23 07h00m

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/tests/tests_services/tests_acompanhamento_de_relatorios_consolidados_sme/test_listagem_de_relatorios_consolidados_sme_com_filtros.py
Esse PR:
- Implementa controle quantitativo de pcs em SME
História: [AB#82943](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82943)
> feat(82943): Relatórios Consolidados das DREs: Controlar o quantitativo de PCs em cada publicação

- hotfixes.md
- sme_ptrf_apps/despesas/admin.py
Merge do bug 85204 na branch de hotifx 6.0.1
> Merge bug 85204 na branch hotifx 6.0.1

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
feat(74496): Retificacao gerar demonstrativo
Esse PR:
- Remove comentarios não utilizados
História: [AB#74496](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74496)
> feat(74496): Retificacao gerar demonstrativo

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/partials/dados-sobre-a-reuniao.html
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/pdf.html
[AB#85049](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85049)
> Update homolog 13 fev23 13h15m

- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
Agora, caso ocorra alguma falha o relatório não ficará em processamento infinitamente.
Resolve [AB#86076](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86076)
> fix(86076): Altera geração prévia relatório após acertos

- sme_ptrf_apps/core/services/ata_dados_service.py
Agora os membros do conselho fiscal aparecem na lista de presentes do PDF da ata
> fix(86319): Lista de presentes ata associacao

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
- sme_ptrf_apps/core/services/ata_dados_service.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/conftest.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_verifica_saldo_antes_put.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_status_consolidado_dre.py
Esse PR:
- Corrige Loading em Relatório Consolidado
História: [AB#85715](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85715)
> fix(85715): Relatório consolidado: o loading não é exibido corretamente na solicitação de geração do demonstrativo

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_desfazer_retificacao_consolidado.py
feat(85370): Altera tooltip
Esse PR:
- Altera tooltip
História: [AB#85370](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85370)
> feat(85370): Altera tooltip

- sme_ptrf_apps/dre/api/serializers/ata_parecer_tecnico_serializer.py
Esse PR:
Atende [AB#85372](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85372)
> feat(85372): Desobriga motivo retificação consolidado

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/dre/api/serializers/ata_parecer_tecnico_serializer.py
- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/conftest.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_retornar_pcs_do_consolidado.py
feat(85105): Retificação da retificação
Esse PR:
- Altera regra para retornar pcs do consolidado
- Altera vinculação da retificacao a retificacao
- Altera regra para retornar quantidade de pcs vinculadas ao consolidado de acordo com o campo many to many
História: [AB#85105](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85105)
> feat(85105): Retificação da retificação

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
Esse PR:
- Adiciona um novo campo no serializer da prestacao de conta, que identifica qual o consolidado origem da PC
História [AB#84790](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/84790)
> feat(84790): Adiciona referência da publicação na pc retificada

- sme_ptrf_apps/dre/api/serializers/validation_serializers/consolidado_dre_desfazer_retificacao.py
- sme_ptrf_apps/dre/api/serializers/validation_serializers/consolidado_dre_editar_motivo_retificacao.py
- sme_ptrf_apps/dre/api/serializers/validation_serializers/consolidado_dre_retificacao.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/conftest.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_desfazer_retificacao_consolidado.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_retificar_consolidado_dre.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_update_motivo_retificacao.py
- sme_ptrf_apps/dre/services/tests/tests_consolidado_dre_service/test_update_retificacao_consolidado.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/conftest.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_desfazer_retificacao.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_retificar.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_update_motivo_retificacao.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_update_retificacao.py
Esse PR:
-  Retira obrigatoriedade campo motivo
História: [AB#86610](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86610)
> feat(86610): Retificação do Consolidado das PCs: Inclusão/Edição da Retificação : Retirar obrigatoriedade do campo Motivo

- sme_ptrf_apps/dre/api/serializers/ata_parecer_tecnico_serializer.py
Esse PR:
- Corrige obrigatoriedade motivo retificacao ata
> feat(85372): Corrige obrigatoriedade motivo retificacao ata

- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/partials/tabela-acertos-em-lancamentos.html
Esse PR:
- Altera o campo demonstrado para uma coluna na tabela
História: [AB#86718](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86718)
> feat(86718): Altera o campo demonstrado para uma coluna

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
Esse PR:
- Modifica o serviço de consolidados, adicionando no retorno o campo do motivo de retificação
História: [AB#85993](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85993)
> feat(85993):Validar preenchimento Motivo da Retificação na geração da publicação de retificação

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard_sme.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- altera o texto das faixas de apresentação do período na página de resumo geral da SME.
- ajusta testes para identificar os novos textos.
História: [AB#84793](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/84793)
> feat(84793): Ajustar Resumo Geral do Período e Detalhamento por DRE

- sme_ptrf_apps/core/api/views/notificacao_viewset.py
- sme_ptrf_apps/dre/services/notificacao_service/class_notificacao_comentario_de_analise_consolidado_dre.py
Esse PR:
- Modifica o viewset e o serviço de notificação para indicar se a mensagem foi enviada com sucesso ou não.
História: [AB#86761](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86761)
> feat(86761): Exibir modal verificando a não possibilidade de notificar a DRE

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_materiais_e_servicos_service.py
- sme_ptrf_apps/sme/tasks.py
Esse PR:
- Adiciona view, service e task de exportação de especificações de materiais e serviços.
História: [AB#86738](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86738)
> feat(86738): Exportação de materiais e serviços

- sme_ptrf_apps/sme/services/exporta_materiais_e_servicos_service.py
Esse PR:
- Altera a variavel de identificação do filtro utilizado para filtrar o periodo dos dados apresentados no csv gerado.
História: [AB#86738](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/86738)
> feat(86738): Modifica campo do filtro por data da extração

- sme_ptrf_apps/contrib/scripts_diversos/dev_tesouro.sql
- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/tasks.py
Esse PR:
- Move ação de criar e vincular solicitações de devolução ao tesouro para tarefas assincronas
História: [AB#88450](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88450)
> Fix/88450 acertos lancamento nao carrega-parte-2

- sme_ptrf_apps/despesas/services/carga_materiais_servicos_service.py
Esse PR:
- Adiciona a coluna de Nome do tipo de custeio no arquivo de carga.
- Adiciona a verificação da coluna Aplicação.
História: [AB#47927](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/47927)
> feat(47927): Adiciona verificação e coluna no upload

- requirements/base.txt
Esse PR:
Resolve história: [AB#89255](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89255)
> feat(89255): Atualiza Django para 2.2.28

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
feat(88259): Acompanhamento de PC
Esse PR:
- Adiciona metodo ao modelo de PC para retornar mensagem de status de acordo com o consolidado vinculado
História: [AB#88259](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88259)
> feat(88259): Acompanhamento de PC

- sme_ptrf_apps/core/admin.py
Melhoria no admin de devolução ao tesouro para vincular despesa
História:[AB#88217](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88217)
> Melhoria no admin de devolução ao tesouro para vincular despesa

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta_nao_recebidas.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta_todos_os_status.py
Esse PR:
- Altera o list de pcs não apresentadas para incluir informações sobre associação.
Corrige [AB#89842](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89842)
> fix(89842): Add associacao no list de pcs não apresentadas

- sme_ptrf_apps/core/services/solicitacao_acerto_documento_service.py
feat(88047) Analise DRE, edição informação
Esse PR:
- Realiza ajuste no metodo de edição informação
História: [AB#88047](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88047)
> feat(88047) Analise DRE, edição informação

- sme_ptrf_apps/static/css/pdf-relatorio-dos-acertos.css
Esse PR:
- Corrige o layout do check-box que indica conciliação de um lançamento.
Resolve [AB#89874](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89874)
> fix(89874): Layout errado de conciliado em relatório de acertos

- sme_ptrf_apps/static/css/pdf-relatorio-dos-acertos.css
[AB#88422](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88422)
> Update homolog 28 mar1607h

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/contrib/scripts_diversos/dev_tesouro.sql
- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/models/transferencia_eol.py
Atualiza Hom2 com a posição de Mater
> Mater -> Homolog-r2

- sme_ptrf_apps/dre/services/analise_documento_consolidado_dre_service.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_como_correto.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_como_nao_conferido.py
Esse PR:
-  Ajusta mensagens de sucesso
História: [AB#88281](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88281)
> feat(88281): Ajustar as mensagens de sucesso

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
Esse PR:
- Utiliza data de transacao, quando data documento não existe
História: [AB#90066](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90066)
> fix(90066) Conferencia lançamento não carrega

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_create_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_update_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_usuarios_status.py
Necessário para preparação da Release 7.
[AB#88666](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88666)
> Atualiza hotfixes 6.0.5 e 6.0.6

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-execucao-fisico-financeira.html
feat(90880): Demonstrativo financeiro/consolidado
Esse PR:
- Altera template do PDF para exibir o valor de devolução ao tesouro mesclado entre as contas
História: [AB#90880](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90880)
> feat(90880): Demonstrativo financeiro/consolidado

- README.md
- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_create_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_update_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_usuarios_status.py
Esse PR atualiza a release 7 no ambiente develop.
[AB#88667](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/88667)
> Release 7 -> Develop

- Dockerfile
Esse PR atualiza a versão do Python no Dockerfile.
[AB#89620](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89620)
> feat(89620): Atualiza versão do Python para 3.8.*

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_saldo_final_periodo_pc_service.py
- sme_ptrf_apps/sme/tasks.py
- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_saldos_finais_periodos/test_exportacoes_dados_saldos_finais_periodos.py
- sme_ptrf_apps/sme/tests/tests_services/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_saldos_finais_periodo.py
feat(90617): Extração de dados saldos finais periodo
Esse PR:
- Adiciona serviço para extrair dados
- Adiciona task assincrona para extrair dados
- Adiciona endpoint para extrair dados
- Adiciona testes relacionados a extração de dados
História: [AB#90617](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90617)
> feat(90617): Extração de dados saldos finais periodo

- hotfixes.md
- sme_ptrf_apps/__init__.py
Esse PR:
- Faz o merge de Master em Homolog2
> Merge master em homolog2

- sme_ptrf_apps/despesas/models/despesa.py
Esse PR:
- Corrige impossível deletar despesa rascunho
História:[AB#89801](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89801)
> fix(89801): Impossível deletar despesa rascunho

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_rateios_service.py
- sme_ptrf_apps/sme/services/exporta_saldo_final_periodo_pc_service.py
- sme_ptrf_apps/sme/tasks.py
- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_rateios/test_exportacoes_dados_rateios.py
- sme_ptrf_apps/sme/tests/tests_services/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_rateios.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_saldos_finais_periodo.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_relacao_bens.py
feat(90626): Extração de dados rateios
Esse PR:
- Adiciona serviço para extração de dados de rateios
- Adiciona endpoint para extração de dados de rateios
- Adiciona task assincrona para extração de dados de rateios
- Refatora serviço ExportacoesDadosRelacaoBensService
- Refatora serviço ExportacoesDadosSaldosFinaisPeriodoService
- Altera soft time das tasks de extração de dados
- Adiciona testes para extração de dados de rateios
- Altera testes relacionados a refatoração
História: [AB#90626](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90626)
> feat(90626): Extração de dados rateios

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_atas_service.py
- sme_ptrf_apps/sme/tasks.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_atas/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_atas/test_exportacoes_atas.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_devolucao_tesouro/test_exportacoes_devolucao_tesouro_pc.py
Esse PR:
- Adiciona rota para extração assíncrona das atas.
- Cria task assíncrona de extração das atas.
- Cria testes relacionados a extração de dados das atas.
História: [AB#90623](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90623)
> feat(90623): Exportação de dados das atas

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_demonstrativos_financeiros_service.py
- sme_ptrf_apps/sme/tasks.py
- sme_ptrf_apps/sme/tests/tests_services/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_status_prestacoes_conta/test_exportacoes_demonstrativos_financeiros.py
Esse PR:
- Implementa Extração de Dados PCs Demonstrativos
História: [AB#90621](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90621)
> feat(90621): Extração de dados de Prestações de Contas: Demonstrativos

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_demonstrativos_financeiros_service.py
- sme_ptrf_apps/sme/tasks.py
- sme_ptrf_apps/sme/tests/tests_services/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_status_prestacoes_conta/test_exportacoes_demonstrativos_financeiros.py
História: [AB#90170](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90170)
> feat(90170): Posição em Develop 14/04/2023 às 11:03

- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_create_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_update_user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_usuarios_status.py
feat(90650): Refatoração testes
Este PR:
- Refatora testes
História: [AB#90650](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90650)
> feat(90650): Refatoração testes

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_documentos_despesas.py
- sme_ptrf_apps/sme/tasks.py
- sme_ptrf_apps/sme/tests/test_api_exportacoes_dados_despesas/test_exportacoes_dados_despesas.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_atas/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_atas/test_exportacoes_atas.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_despesas/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_despesas/test_exportacoes_despesas.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_devolucao_tesouro/conftest.py
Esse PR:
- Adiciona rota para extração assíncrona das despesas.
- Cria task assíncrona de extração das despesas.
- Cria testes relacionados a extração de dados das despesas.
- Adiciona campos de secretários na exportação de atas.
- Remove imports não utilizados.
História: [AB#90471](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90471)
> feat(90471): Exportação dados despesas

- sme_ptrf_apps/users/api/serializers/senha_serializer.py
- sme_ptrf_apps/users/api/views/senha_viewset.py
fix(91941): Redefinição de senha
Esse PR:
- Altera retorno do update da API de redefinição de senha
História: [AB#91941](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91941)
> fix(91941): Redefinição de senha

- sme_ptrf_apps/core/models/transferencia_eol.py
- sme_ptrf_apps/core/tests/tests_transferencia_eol/conftest.py
- sme_ptrf_apps/core/tests/tests_transferencia_eol/test_copiar_receitas_associacao_do_tipo_transferido.py
- sme_ptrf_apps/receitas/admin.py
Corrige o bug: [AB#92293](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92293)
> fix(92293): transf eol

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/models/transferencia_eol.py
- sme_ptrf_apps/core/tests/tests_transferencia_eol/conftest.py
- sme_ptrf_apps/core/tests/tests_transferencia_eol/test_copiar_receitas_associacao_do_tipo_transferido.py
- sme_ptrf_apps/receitas/admin.py
- sme_ptrf_apps/users/api/serializers/senha_serializer.py
- sme_ptrf_apps/users/api/views/senha_viewset.py
Corrige os bugs: [AB#91941](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91941), [AB#92293](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92293)
> Merge master em develop

- sme_ptrf_apps/core/api/serializers/associacao_serializer.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/services/associacoes_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_associacoes_service/test_valida_data_encerramento.py
- sme_ptrf_apps/core/tests/tests_services/tests_associacoes_service/test_valida_se_pode_editar_periodo_inicial.py
Esse PR: 
- Atualiza História 91682 em Homologação.
> feat(91682): Merge develop em homolog

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
feat(91747): Encerramento associação nos consolidados PCs
Esse PR:
- Altera totalizador de associações
- Altera totalizador de associações na trilha de status
História: [AB#91747](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91747)
> feat(91747): Encerramento associação nos consolidados PCs

- sme_ptrf_apps/sme/services/saldo_bancario_service.py
Esse PR:
- Adiciona a verificação de Associação ativa nas queries dos serviços de saldos por dre e unidade.
História: [AB#91686](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91686)
> feat(91686): Adiciona filtro em saldos

- sme_ptrf_apps/core/services/associacoes_service.py
Esse PR:
-  Remove de ValidaDataDeEncerramento Pcs e Fechamentos
História: [AB#91682](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91682)
> feat(91682): Parametrizações/Core 07.0: Associações: Incluir data de encerramento da associação e validação no Período inicial

- config/settings/base.py
- config/urls.py
- requirements/base.txt
Esse PR:
- Instala e configura o componente drf-spectacular
- Refatora o settings/base.py
- Remove endpoint auth-token que não era usado
- Remove classe de autenticação TokenAuthentication que não era usada
Atende [AB#91171](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91171)
> feat(91171): Instala e configura swagger e redocs

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_periodos_para_prestacao_contas.py
feat(91768):  Parte 2 ajuste exibir períodos que estejam sem encerramento da associação
Esse PR:
- Ajusta validação
> feat(91768): Parte 2 ajuste exibir períodos que estejam sem encerramento da associação

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/serializers/associacao_serializer.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_proccessos_associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_retrieve_associacao.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_previa/test_previa_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_processos_associacoes/test_processo_associacao_retrieve.py
- sme_ptrf_apps/core/tests/tests_membro_associacao/test_membro_associacao_api.py
feat(92320): Valida associacao encerrada pode editar dados
Esse PR:
- Adiciona validação se associação pode editar dados
História: [AB#92320](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92320)
> feat(92320): Valida associacao encerrada pode editar dados

- sme_ptrf_apps/core/services/periodo_inicial.py
Esse PR:
- Valida se o período do repasse é válido de acordo com o período inicial da associação
- Valida se o período do repasse é válido de acordo com a data de encerramento da associação
História: [AB#93196](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93196)
> feat(93196): Valida data encerramento e periodo inicial da associacao na carga de periodo inicial

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/services/carga_associacoes_service.py
- sme_ptrf_apps/core/tests/tests_carga_associacoes_service/test_carga_associacoes_service.py
Esse PR:
- Valida se associação está encerrada
História: [AB#93198](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93198)
> feat(93198): Valida carga de associações

- README.md
Atende [AB#92643](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92643)
> docs(92643): Altera link para a documentação no readme

- sme_ptrf_apps/core/services/carga_previsao_repasse.py
- sme_ptrf_apps/core/tests/carga_previsao_repasse/test_carga_previsao.py
Esse PR:
- Valida se o período do repasse é válido de acordo com o período inicial da associação
- Valida se o período do repasse é válido de acordo com a data de encerramento da associação
História: [AB#93199](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93199)
> feat(93199): Valida data encerramento e periodo inicial da associacao na carga de repasses previstos sme

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Ajusta verificacao se consolidado é versao final para passá-lo como paramentro
História: [AB#93018](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93018)
> fix(93018): Consolidados das PCs: o bloco de publicação parcial não é exibido no Front - Parte 02

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/associacao.py
Esse PR:
- Adiciona filtro em periodos para prestação de contas.
História: [AB#93760](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93760)
> fix(93760): Implementa filtro em periodos de prestacao de contas

- sme_ptrf_apps/core/api/serializers/tag_serializer.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/core/tests/tests_tag/test_serializers.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_tabelas.py
Esse PR:
- Adiciona id da Tag em Serializer
> feat(89762): Gastos da escola: Exibir tags informativas/legenda relacionadas com as despesas

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
Esse PR:
- Adiciona no calculo do valor total de despesas o filtro por vinculo de atividades e informações.
História: [AB#89762](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/89762)
> feat(89762): Altera calculo total despesas

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/tests/tests_ata_parecer_tecnico_service.py/conftest.py
- sme_ptrf_apps/dre/services/tests/tests_ata_parecer_tecnico_service.py/test_ordenacao_unidades_ata.py
Esse PR:
- Altera o serviço de informacoes de pcs no consolidado para ordenar as unidades nas atas.
- Adiciona teste de ordenação de unidades.
História: [AB#94325](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94325)
> Merge feature 94325 em develop

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
Esse PR:
- Adiciona retorno da devolução atual da prestação de contas 
- Atualiza testes
História [AB#93859](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93859)
> feat(93859): Adiciona retorno da devolucao atual da prestacao de contas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/dre/api/views/analises_documentos_consolidado_dre_viewset.py
- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_download_documento.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_acerto.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_como_correto.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_como_nao_conferido.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_alterar_status_sme.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_consolidado_dre_detalhamento.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_consolidado_dre_detalhamento_conferencia_documentos.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_devolver_consolidado_dre.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_reabrir_consolidado_dre.py
fix(94711): Ajuste permissões API
Esse PR:
- Ajusta permissões da API do consolidado
História: AB#94711
> fix(94711): Ajuste permissões API

- sme_ptrf_apps/users/services/sme_integracao_service.py
fix(93666): Converte RF para string
Esse PR:
- Remove conversão de RF para int
História: [AB#93666](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93666)
> fix(93666): Converte RF para string

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/dre/api/views/analises_documentos_consolidado_dre_viewset.py
- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_download_documento.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_acerto.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_como_correto.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_como_nao_conferido.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_alterar_status_sme.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_consolidado_dre_detalhamento.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_consolidado_dre_detalhamento_conferencia_documentos.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_devolver_consolidado_dre.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_reabrir_consolidado_dre.py
Corrige os bugs: [AB#94711](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94711), [AB#91272](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91272)
> Merge hotfix 8.1.1 em develop

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/dre/api/views/analises_documentos_consolidado_dre_viewset.py
- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_download_documento.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_acerto.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_como_correto.py
- sme_ptrf_apps/dre/tests/tests_api_analise_documento_consolidado_dre/test_action_analise_documento_consolidado_dre_gravar_como_nao_conferido.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_alterar_status_sme.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_consolidado_dre_detalhamento.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_consolidado_dre_detalhamento_conferencia_documentos.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_devolver_consolidado_dre.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_reabrir_consolidado_dre.py
História: [AB#94221](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94221)
> Posição em develop 26/05/2023 ás 08:45

- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_transacoes_conciliacao.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_com_filtros.py
- sme_ptrf_apps/despesas/tests/tests_despesas/test_despesa_tags_informacoes.py
Esse PR:
- Implementa Tags Conciliado e Não Conciliado
História: [AB#71056](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/71056)
> feat(71056): Conciliação Bancária:  Coluna de etiquetas informativas e modal de legendas

- sme_ptrf_apps/sme/services/saldo_bancario_service.py
- sme_ptrf_apps/sme/tests/tests_api_saldos_bancarios/test_saldos_bancarios.py
Esse PR:
- Altera exibição em SME Consulta de Saldos Bancários
História: [AB#92326](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/92326)
> feat(92326): Consulta de saldos bancários - Exibir nome completo da DRE e da unidade educacional

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/users/services/sme_integracao_service.py
[AB#95780](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95780)
> Release 8.2 -> Develop

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/models/analise_lancamento_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_analise_lancamento_prestacao_conta/test_analise_lancamento_prestacao_conta_model.py
- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/criar_acesso_de_suporte_service.py
- sme_ptrf_apps/users/services/encerrar_acesso_de_suporte_service.py
Esse PR atualiza em develop o hotfix 8.2.1 que resolve os bugs:
- [AB#93404](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93404)
- [AB#95108](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95108)
> Update hotfix/8.2.1 em dev

- sme_ptrf_apps/core/services/periodo_inicial.py
- sme_ptrf_apps/core/tests/tests_carga_periodo/test_carga.py
Esse PR:
- Adiciona validação na carga de período inicial
- Adiciona e atualiza testes
História: [AB#95815](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95815)
> feat(95815): Adiciona validação na carga de período inicial

- sme_ptrf_apps/dre/services/notificacao_service/class_notificacao_comentario_de_analise_consolidado_dre.py
Esse PR:
- Merge fix 91168 em homolog
> Merge fix 91168 em homolog

- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/despesas/models/despesa.py
Esse PR:
- Altera o id da tag encerrada em associações.
- Remove lógica do front-end da tag de não conciliada e adiciona no back para integrar todas as tabelas do sistema.
História: [AB#96956](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96956)
> Fix(96956): Corrige layout e informações tags

- sme_ptrf_apps/__init__.py
Esse PR atualiza Develop com a posição de master após release 8.3.0.
[AB#96421](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96421)
> 8.3.0 -> Develop

- Dockerfile
- requirements/local.txt
[AB#96046](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96046)
> build(96046): Revertendo devido a erro no Jenkins

- Dockerfile
- Jenkinsfile
- requirements/local.txt
Esse PR: 
- Atualiza a imagem docker do Python para a versão 3.10
- Atualiza para a última versão os pacotes mypy, django-stubs, pytest, pytest-django e pytest-sugar.
Atende [AB#96046](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96046)
> build(96046): Reaplica atualização Python 3.10

- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
Esse PR:
- Refatora os testes de tag de informação.
> Refatora testes tag informação

- Jenkinsfile
- requirements/local.txt
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
História: [AB#96413](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96413)
> Posição em Develop 26/06/2023 às 09:12h

- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR:
- Modifica textos totais.
História: [AB#95904](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/95904)
> feat(95904): Modifica textos totais

- sme_ptrf_apps/core/api/serializers/comentario_analise_prestacao_serializer.py
Foi feito um ajuste para que todos os parâmetros possam receber null, mas que ao mesmo tempo haja uma validação no patch.
> feat(96783); Parte 2 ajusta validação para envio de parâmetros null

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tasks.py
Esse PR:
- Implementa recálculo do fechamento na conclusão do acerto
História: [AB#91365](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/91365)
> feat(91365): Geração de documentos: Efetuar recálculo do fechamento na conclusão do acerto

- requirements/base.txt
Esse PR:
- Reverte a atualização da biblioteca WeasyPrint.
> fix(95805): Reverte a atualizacao da biblioteca weasyprint

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/dre/services/demo_execucao_fisico_financeiro_pdf_service.py
- sme_ptrf_apps/static/css/pdf-demo-execucao-fisico-financeiro-horizontal.css
- sme_ptrf_apps/static/css/pdf-demo-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/pdf-horizontal.html
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
Esse PR:
- Implementa marca d'água na prévia do Demonstrativo da Execução Físico-Financeira.
- Remove Bloco 5 - Autenticação
História [AB#96964](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96964)
> feat(96964): Adiciona marca d' água na prévia do Demonstrativo da Execução Físico-Financeira.

- sme_ptrf_apps/core/services/dados_relatorio_acertos_service.py
- sme_ptrf_apps/static/css/pdf-relatorio-dos-acertos.css
- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
Esse PR:
- Adiciona a marca d'agua nos relatórios dos acertos.
História: [AB#96963](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96963)
> feat(96963): Adiciona marca d'agua relatórios dos acertos

- sme_ptrf_apps/core/services/dados_relatorio_apos_acertos_service.py
- sme_ptrf_apps/static/css/pdf-relatorio-apos-acertos.css
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/pdf.html
Esse PR:
- Adiciona a marca d'agua nos relatórios após acertos.
História: [AB#96962](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96962)
> feat(96962): Adiciona marca d'agua relatório após acerto

- sme_ptrf_apps/core/api/views/comentarios_analises_prestacoes_viewset.py
Esse PR: 
- Corrige ordenamento comentários
História: [AB#96783](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96783)
> feat(96783): Acompanhamento de PC: Inserir Comentários da Análise e Notificar a Associação no status de PC Não apresentada

- sme_ptrf_apps/core/models/associacao.py
Esse PR:
- Altera validação conciliação por saldo reprogramado
História: [AB#97895](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/97895)
> feat(97895): Altera validação conciliação por saldo reprogramado

- sme_ptrf_apps/core/tests/tests_api_arquivos/test_arquivo_processar.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_conclui_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_concluir_prestacao_de_contas_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_monitora_prestacao_de_contas_service.py
Esse PR:
- Inativa testes que precisam ser revisados devido a mudança de versão do Celery.
Esses testes serão revisados em débito técnico a ser planejado na próxima sprint.
[AB#96046](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96046)
> test(96046): Testes afetados pelo celery 5.1.2

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/models/associacao.py
Esse PR:
- Merge release 8.0.4 em develop
História: [AB#97749](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/97749)
> feat(97749): Deploy Homolog2 e Develop

- sme_ptrf_apps/core/api/serializers/validation_serializers/prestacoes_contas_lancamentos_validate_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_conferencia.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
- Implementa filtros por informações(tags) e por conferência em Conferência de Lançamentos
História: [AB#90870](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90870)
> feat(90870): Acompanhamento de PC: Conferência de Lançamentos:  Acrescentar filtros de pesquisa

- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_ordenar_despesas.py
Esse PR:
- Corrige Testes e Fixture
História: [AB#90870](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/90870)
> feat(90870): Acompanhamento de PC: Conferência de Lançamentos:  Acrescentar filtros de pesquisa - Parte 02

- sme_ptrf_apps/core/api/serializers/validation_serializers/prestacoes_contas_lancamentos_validate_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_conferencia.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_lancamentos_tags_informacoes.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_ordenar_despesas.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
- Atualiza homologação com posição de develop 12/07/2023 às 17:23h
> Posição em Develop 12/07/2023 às 17:23h

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/receitas/models/receita.py
História: [AB#94329](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/94329)
> feat(94329): Adiciona string de informações concatenadas e ordenadas no retorno de lançamentos

- sme_ptrf_apps/__init__.py
Esse PR:
- Realiza o deploy da sprint 69 em develop
História: [AB#99260](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/99260)
> feat(99260): Deploy Homolog2/Develop

- config/settings/base.py
- sme_ptrf_apps/users/api/serializers/__init__.py
- sme_ptrf_apps/users/api/serializers/usuario_serializer.py
- sme_ptrf_apps/users/api/views/usuarios_viewset.py
- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/sme_integracao_service.py
Esse PR:
- Implementa a criação e atualização de usuários (ainda sem grupos e unidades de acesso)
- Cria endpoint que valida o acesso de um usuário considerando sua lotação e exercício
- Faz algumas refatorações removendo código não usado.
Obs: Foram deixados alguns "TODOs" que serão objeto de atenção durante a implementação da vinculação de unidades de acesso.
Atende: [AB#85381](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85381)
> feat(85381): Gestão de Usuários: Inclusão e Edição

- sme_ptrf_apps/users/api/serializers/usuario_serializer.py
- sme_ptrf_apps/users/api/views/usuarios_viewset.py
Esse PR:
- Faz ajustes nas regras de negócio de validação de usuários
[AB#85381](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/85381)
> feat(85381): Ajusta validação de mebresia associação

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard_sme.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Modifica a apresentação do acompanhamento de PCs na visão SME.
História: [AB#96405](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/96405)
> feat(96405): Modifica exibição acompanhamento PCs

- sme_ptrf_apps/__init__.py
Esse PR:
- Atualiza develop com posição em master 04/08/2023
> Merge master em develop 04 08

- sme_ptrf_apps/core/api/serializers/solicitacao_encerramento_conta_associacao_serializer.py
Esse PR: 
- Retorna motivos rejeição do cancelamento de conta serializados
História: [AB#98370](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/98370)
> feat(98370): Retorna motivos rejeição do cancelamento de conta

- Dockerfile
- Jenkinsfile
- requirements/base.txt
- requirements/local.txt
Branch utilizada para testar atualização do python 3.9 -> 3.10 em ambiente remoto e realizar ajustes necessários.
> Merge atualizarpython em develop

- sme_ptrf_apps/core/models/prestacao_conta.py
Corrige bug: [AB#93854](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/93854)
> fix(93854): Adiciona atribuição status análise na transaction atomic

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/serializers/conta_associacao_serializer.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/tests/tests_associacao/test_associacao_viewset.py
Esse PR:
- Altera rota de contas para filtrar por período
História: AB#48773
> feat(48773): Tratamento de contas encerradas em conciliação

- sme_ptrf_apps/core/api/serializers/solicitacao_encerramento_conta_associacao_serializer.py
- sme_ptrf_apps/core/api/views/solicitacao_encerramento_conta_associacao_viewset.py
- sme_ptrf_apps/core/tests/tests_api_solicitacao_encerramento_conta_associacao/conftest.py
- sme_ptrf_apps/core/tests/tests_api_solicitacao_encerramento_conta_associacao/test_solicitacao_encerramento_update.py
Esse PR:
- Corrige rota de reenviar solicitação para salvar nova data, se enviada.
> feat(46181): Ajusta rota reenviar solicitação

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tasks.py
Esse PR:
- Resolve Demonstrativo Financeiro não atualiza date e valor do extrato
História: AB#99664
> fix(99664): Demonstrativo não atualiza data do extrato e valor após acertos

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/dre/admin.py
> fix(100138): Consolidado pcs

- sme_ptrf_apps/core/admin.py
> fix(99711): Devolução de PC não exibida

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/analise_prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tasks.py
> fix(99664): Resolve Demonstrativo Financeiro não atualiza date e valor

- config/settings/base.py
- requirements/base.txt
- sme_ptrf_apps/core/tests/tests_associacao/test_associacao_viewset.py
- sme_ptrf_apps/templates/admin/base.html
Esse PR:
- Atualiza a versão do Django no requirements
- Altera settings para desligar warning decorrente da atualização
- Altera template do admin para desligar dark mode automático
- Corrige alguns testes que tinham resultados variáveis
AB#97602
> feat(97602): Atualiza Django para 3.2.20

- sme_ptrf_apps/core/models/prestacao_conta.py
fix(100511): Desfazer conclusão analise
Esse PR:
- Mantém vinculo com o consolidado ao desfazer conclusão da analise
História: AB#100511
> fix(100511): Desfazer conclusão analise

- sme_ptrf_apps/mandatos/api/serializers/__init__.py
- sme_ptrf_apps/mandatos/api/serializers/mandato_serializer.py
- sme_ptrf_apps/mandatos/api/views/mandatos_viewset.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandato_vigente.py
Esse PR:
-  Implementa Mandato Vigente com Composições Anteriores
História: AB#99164
> feat(99164): Dados da associação: Membros: Consultar Mandato vigente com composições anteriores

- Jenkinsfile
> Posição em Develop 23/08/2023 às 09:30h

- sme_ptrf_apps/users/api/views/usuarios_viewset.py
- sme_ptrf_apps/users/models.py
Esse PR:
- Implementa a remoção de acessos a unidade e subordinadas
- Implementa endpoint para a remoção de acessos a unidade e subordinadas
AB#97020
> feat(97020): Implementa remoção de acessos

- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/static/css/pdf-demo-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(100078): Encerramento conta, demonstrativo financeiro
Esse PR:
- Adiciona informação de encerramento de conta ao demonstrativo financeiro
História: AB#100078
> feat(100078): Encerramento conta, demonstrativo financeiro

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/choices/__init__.py
- sme_ptrf_apps/core/choices/filtro_informacoes_associacao_dre.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_associacoes_tabelas.py
Esse PR:
- Separa filtro de associação das Dres de outras tabelas de associações do sistema.
- Modifica tags.
- Adiciona teste relacionado a nova filtragem.
História: AB#87223
> feature(87223): Altera filtro consulta associações Dre

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/models/conta_associacao.py
feat(101564): Encerramento conta, conciliacao
Esse PR:
- Altera retorno da API de observacoes conciliacao
História: AB#101564
> feat(101564): Encerramento conta, conciliacao

- sme_ptrf_apps/core/models/notificacao.py
- sme_ptrf_apps/core/tests/tests_notificacoes_services/test_notificacoes_envia_email.py
Esse PR:
- Adiciona mock de variável de ambiente para verificar se o server_name é o de produção.
História: AB#100876
> feat(100876): Adiciona mock de variavel de ambiente

- sme_ptrf_apps/dre/tests/tests_services/tests_notificacoes_services/test_notificacoes_prazo_para_acerto_antes_vencimento_service.py
- sme_ptrf_apps/dre/tests/tests_services/tests_notificacoes_services/test_notificacoes_prazo_para_acerto_apos_vencimento_service.py
Esse PR:
- Adiciona o mock da variavel SERVE_NAME em dois testes de envio de e-mails.
História: AB#100876
> feat(100876): Adiciona mock variavel SERVER_NAME

- sme_ptrf_apps/core/api/serializers/conta_associacao_serializer.py
feat(101655): Adiciona campo API conta
Esse PR:
- Adiciona status ao retorno da API
História: AB#101655
> feat(101655): Adiciona campo API conta

- Jenkinsfile
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-execucao-fisico-financeira.html
Esse PR:
-  Alterar info conta inativa Relatório Consolidado
História: AB#102973
> feat(102973): Consolidado das PCs: Relatório Consolidado: Alterar informação de "Não houve movimentação financeira" para "Conta inativa"

- sme_ptrf_apps/users/api/views/login.py
Esse PR:
- Altera o método de verificação de feature flags no login.
AB#102442
> feat(102442): Ajusta verificação de flags no login

- Jenkinsfile
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-execucao-fisico-financeira.html
- sme_ptrf_apps/users/tests/test_api_user/test_api_delete_vinculo_user_unidade.py
Esse PR:
- Atualiza hotfix 8.8.1 em Develop
> Merge hot fix 8 8 1 em develop

- Jenkinsfile
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-execucao-fisico-financeira.html
- sme_ptrf_apps/users/tests/test_api_user/test_api_delete_vinculo_user_unidade.py
Esse PR:
- Atualiza Homologação com Posição em Develop 06/09/2023 às 11:20
História: AB#102573
> Posição em Develop 06/09/2023 às 11:20

- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_previstos.py
Esse PR:
- Implementa arquivo de carga de repasse previsto criar conta conforme período
História: AB#102820
> feat(102820): Arquivos de carga: Repasses previstos: Criar a conta conforme o período informado na carga

- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_previstos.py
Esse PR:
- Implementa arquivo de carga de repasse previsto criar conta conforme período em Homologação
> feat(102820):  Arquivos de carga: Repasses previstos: Criar a conta conforme o período informado na carga

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_ata_dados_service/conftest.py
Esse PR:
- Merge develop em homolog 14/09/2023
História: AB#102573
> Posição em Develop 14/09/2023 às 12:18h

- sme_ptrf_apps/receitas/services/carga_repasses_realizados.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_realizados.py
Esse PR: 
- Arquivo de carga do tipo repasses realizados cria conta
Historia: AB#102877
> feat(102877): Arquivos de carga: Repasses realizados: Criar a conta conforme o período informado na carga

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/models/participante.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
- sme_ptrf_apps/core/services/ata_dados_service.py
- sme_ptrf_apps/core/services/membro_associacao_service.py
Esse PR atualiza a release 8.9.0 em develop.
AB#103565
> Release 8.9.0 -> Develop

- sme_ptrf_apps/core/services/prestacao_contas_services.py
fix(104230): Falha geração de PC
Esse PR:
- Altera import da função revoke do celery
História: AB#104230
> fix(104230): Falha geração de PC

- sme_ptrf_apps/core/models/prestacao_conta.py
fix(104701): Devolução PC
Esse PR:
- Adiciona acertos de extratos bancarios a validação de devolução da pc
História: AB#104701
> fix(104701): Devolução PC

- sme_ptrf_apps/core/api/views/presentes_ata_viewset.py
fix(104810): Edição ata em branco
Esse PR:
- Realiza ajuste na API de lista de presentes
História: AB#104810
> fix(104810): Edição ata em branco

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
fix(104690): Resumo demonstrativo financeiro
Esse PR:
- Altera forma de acessar conta associacao
História: AB#104690
> fix(104690): Resumo demonstrativo financeiro

- sme_ptrf_apps/core/api/serializers/conta_associacao_serializer.py
- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_despesa_validacao_conta_associacao.py
Esse PR:
- Valida data de início da conta no payload de rateios 
- Implementa testes
História: AB#103824
> feat(103824): Valida data início conta em gastos da escola

- sme_ptrf_apps/mandatos/api/views/mandatos_viewset.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_delete.py
Esse PR:
- Valida exclusão de mandato
- Implementa testes
História: AB#99081
> feat(99081): Valida exclusão de mandato

- Jenkinsfile
- sme_ptrf_apps/core/services/notificacao_services/enviar_email_notificacao.py
- sme_ptrf_apps/core/tests/tests_notificacoes_services/conftest.py
- sme_ptrf_apps/core/tests/tests_notificacoes_services/test_notificacoes_envia_email.py
> fix(105706): Devolução PC

- sme_ptrf_apps/mandatos/admin.py
- sme_ptrf_apps/mandatos/api/serializers/__init__.py
- sme_ptrf_apps/mandatos/api/serializers/cargo_composicao_serializer.py
- sme_ptrf_apps/mandatos/api/serializers/composicao_serializer.py
- sme_ptrf_apps/mandatos/api/serializers/mandato_serializer.py
- sme_ptrf_apps/mandatos/api/serializers/validation_serializers/mandato_validate_serializer.py
- sme_ptrf_apps/mandatos/api/views/mandatos_viewset.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/conftest.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandato_anterior.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandato_vigente.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandatos_anteriores.py
Esse PR:
- Merge feat 99165 em develop
História: AB#99165
> feat(99165): Dados da associação: Membros: Consultar Mandatos anteriores

- sme_ptrf_apps/core/tests/tests_api_acoes/test_acoes_list_associacoes_nao_vinculadas.py
- sme_ptrf_apps/sme/services/saldo_bancario_service.py
- sme_ptrf_apps/sme/tests/tests_api_saldos_bancarios/test_saldos_bancarios_por_dre.py
Esse PR:
- Implementa ordem alfabetica e altera nome da DREs em Consulta de Saldos Bancarios
História: AB#105503
> feat(105503): Consulta de saldos bancários: Exibição por Diretoria: Exibir as DREs em ordem alfabética e alterar o nome de exibição da DRE

- sme_ptrf_apps/core/models/analise_documento_prestacao_conta.py
- sme_ptrf_apps/core/models/analise_lancamento_prestacao_conta.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
> fix(104961): Corrige tratamento lançamentos sem solicitação de acerto

- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
> fix(105942): Corrige retorno conta encerrada com saldo

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_execucao_financeira_relatorio_consolidado_dre.py
> fix(105253): Retorna tipos de conta com pelo menos uma conta criada no período ou anterior

- Jenkinsfile
- sme_ptrf_apps/core/tasks/concluir_prestacao_de_contas.py
> fix(105575):  Concluir acerto

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/fixtures/factories/associacao_factory.py
- sme_ptrf_apps/core/fixtures/factories/conta_associacao_factory.py
- sme_ptrf_apps/core/fixtures/factories/observacao_conciliacao_factory.py
- sme_ptrf_apps/core/fixtures/factories/periodo_factory.py
- sme_ptrf_apps/core/fixtures/factories/prestacao_conta_factory.py
- sme_ptrf_apps/core/fixtures/factories/tipo_conta_factory.py
- sme_ptrf_apps/core/fixtures/factories/unidade_factory.py
- sme_ptrf_apps/core/fixtures/providers/conta_associacao_provider.py
- sme_ptrf_apps/core/fixtures/providers/unidade_provider.py
- sme_ptrf_apps/core/tests/tests_conciliacao_services/test_permite_editar_campos_extrato.py
- sme_ptrf_apps/fixtures/__init__.py
- sme_ptrf_apps/fixtures/periodo_fixtures.py
Esse PR:
- Adiciona factories para auxiliar na criação de testes.
> test: Adiciona factories para auxiliar nos testes

- sme_ptrf_apps/users/api/validations/usuario_validations.py
- sme_ptrf_apps/users/api/views/usuarios_viewset.py
- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/__init__.py
- sme_ptrf_apps/users/services/gestao_usuario_service.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_unidades_do_usuario.py
- sme_ptrf_apps/users/tests/test_user_v2/conftest.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_gestao_usuario.py
feat(87153): Lista de unidades em gestão de usuários
Esse PR:
- Adiciona serviço para gerenciar lista de unidades do usuario
- Adiciona serializer para validar endpoints
- Adiciona endpoint para retornar lista de unidades
- Adiciona endpoint para habilitar acesso
- Adiciona endpoint para desabilitar acesso
História: AB#87153
> feat(87153): Lista de unidades em gestão de usuários

- sme_ptrf_apps/mandatos/api/serializers/mandato_serializer.py
- sme_ptrf_apps/mandatos/api/views/mandatos_viewset.py
- sme_ptrf_apps/mandatos/services/__init__.py
- sme_ptrf_apps/mandatos/services/mandato_service.py
- sme_ptrf_apps/mandatos/tests/conftest.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/conftest.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandato_mais_recente.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_create.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_delete.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_update.py
- sme_ptrf_apps/mandatos/tests/tests_services/test_mandato_service.py
Esse PR:
- Implementa períodos de mandato não permitir sobreposições
História: AB#102539
> feat(102539): Parametrizações do sistema: Períodos de mandato: Não permitir sobreposição de períodos e edição apenas no último período cadastrado

- sme_ptrf_apps/core/models/conta_associacao.py
fix(105962): Exibição conta encerrada
Esse PR:
- Ajusta condição do metoodo ativa_no_periodo do modelo de ContaAssociacao
História: AB#105962
> fix(105962): Exibição conta encerrada

- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
Esse PR:
- Corrige edição do crédito não exibe conta encerrada
História: AB#105959
> fix(105959):  Edição do crédito: Após a confirmação de encerramento da conta, a conta deixou de ser exibida na edição de crédito

- requirements/base.txt
- requirements/local.txt
- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/users/views.py
Esse PR:
1. Atualiza a versão do Django e de outros pacotes impactados pela mudança de versão:
- `django==4.1.12`
- `djangorestframework==3.14.0`
- `django-debug-toolbar==4.2.0`
2. Atualiza versão de alguns pacotes que tinham vulnerabilidades detectadas pelo pip-audit:
- `Pillow==10.0.1`
- `Werkzeug==2.2.3`
- `sentry-sdk==1.14.0`
- `celery==5.2.2`
Atende história: AB#104707
> feat(104707): Update Django 4.1

- config/settings/base.py
Esse PR:
- Resolve erro de Origin checking failed devido a mudanças no Django 4.
AB#104707
> fix(104707): Resolve problema de Origin checking failed

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
Esse PR:
- Resolve um problema de repetição de despesas na paginação. Ocorria de alguns registros serem exibidos em duas páginas.
Corrige AB#107091
> fix(107091): Resolve repetição de despesas na paginação

- Jenkinsfile
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-autenticacao.html
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/pdf-horizontal.html
fix(107046) Demo execucao fisica financeira
Esse PR:
- Ajusta template do PDF para exibir bloco
História: AB#107046
> fix(107046) Demo execucao fisica financeira

- sme_ptrf_apps/sme/services/exporta_saldo_final_periodo_pc_service.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_saldos_finais_periodo.py
Esse PR:
- Adiciona o nome da DRE na extração de dados dos saldos finais.
História: AB#106055
> feat(106055): Adiciona nome da DRE na extracao saldo final

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
Esse PR:
- Adiciona nome da DRE na extração de créditos.
- Modifica a coluna de outros motivos de estorno para receber os estornos e os outros motivos de estorno.
História: AB#106390
> feat(106390): Modifica dados da extracao de creditos

- sme_ptrf_apps/mandatos/admin.py
- sme_ptrf_apps/mandatos/api/views/cargos_composicoes_viewset.py
- sme_ptrf_apps/mandatos/api/views/composicoes_viewset.py
- sme_ptrf_apps/mandatos/api/views/mandatos_viewset.py
- sme_ptrf_apps/mandatos/api/views/ocupantes_cargos_viewset.py
- sme_ptrf_apps/mandatos/tests/tests_api_cargo_composicao/test_cargo_composicao_list.py
- sme_ptrf_apps/mandatos/tests/tests_api_composicao/test_composicao_list.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandato_anterior.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandato_mais_recente.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandato_vigente.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_action_mandatos_anteriores.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_create.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_delete.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_list.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_update.py
- sme_ptrf_apps/mandatos/tests/tests_api_ocupante_cargo/test_ocupante_cargo_list.py
- sme_ptrf_apps/mandatos/tests/tests_cargo_composicao/test_cargo_composicao_viewset.py
- sme_ptrf_apps/mandatos/tests/tests_composicao/test_composicao_viewset.py
- sme_ptrf_apps/mandatos/tests/tests_mandato/test_mandato_viewset.py
- sme_ptrf_apps/mandatos/tests/tests_ocupante_cargo/test_ocupante_cargo_viewset.py
Esse PR:
- Implementa feature flags em histórico de membros
História: AB#106375
> feat(106375): Usar Feature Flag na funcionalidade de Histórico de Membros

- sme_ptrf_apps/users/api/views/usuarios_viewset.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_unidades_do_usuario.py
- sme_ptrf_apps/users/tests/test_api_usuarios/test_usuarios_endpoints.py
Esse PR:
- Adiciona a feature flag de gestao de usuarios na viewset de usuarios.
- Testes relacionados.
História: AB#106378
> tec(106378): Adiciona feature flag na gestao de usuarios

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
Esse PR: 
- Atualiza hotfix 8.11.2 em develop
> Merge hotfix 8.11.2 em develop

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/models/relacao_bens.py
- sme_ptrf_apps/core/models/relatorio_relacao_bens.py
- sme_ptrf_apps/core/services/relacao_bens.py
- sme_ptrf_apps/core/services/relacao_bens_dados_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_relacao_bens_service/test_relacao_bens_service.py
Esse PR:
- Implementa método para retornar dados persistidos formatados
- Adiciona action no admin para gerar arquivo dos dados persistidos
- Atualiza e adiciona testes
História AB#104042
> feat(104042): Fluxo para utilizar dados persistidos da relação de bens

- sme_ptrf_apps/core/api/serializers/conta_associacao_serializer.py
- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
Esse PR:
- Adiciona informação de período no retorno da conta associação e prestação de conta.
História: AB#107654
> feat(107654): Permitir incluir acertos quando houver solicitação de encerramento de conta

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/services/conta_associacao_service.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
- sme_ptrf_apps/core/tests/tests_notificacoes_services/conftest.py
Esse PR:
-  Ajusta retorno de informação conta encerrada com saldo em status período
História: AB#107758
> fix(107758): Ajusta retorno de informação conta encerrada com saldo em status período

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_execucao_financeira_relatorio_consolidado_dre.py
Esse PR:
- Corrige filtro para retorno conforme período inicial e encerramento da conta.
História: AB#106058, AB#107878
> fix(106058,107878): Corrige filtro para retorno conforme período inicial e encerramento da conta

- sme_ptrf_apps/despesas/models/despesa.py
Esse PR:
- Ajusta atribuição de data documento para despesa imposto
História: AB#107889
> fix(107889): Ajusta atribuição de data documento para despesa imposto

- sme_ptrf_apps/core/models/analise_lancamento_prestacao_conta.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_get_lancamentos_solicitacoes_acerto.py
- sme_ptrf_apps/despesas/admin.py
fix(106974): Analise lancamento
Esse PR:
- Adiciona signal pre-save ao modelo de AnaliseLancamentoPrestacaoConta
História: AB#106974
> fix(106974): Analise lancamento

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_execucao_financeira_relatorio_consolidado_dre.py
Esse PR:
- Ajusta filtro de contas para período em aberto na info de demonstrativo financeiro.
- Ajusta teste 
História: AB#106058, AB#107878
> feat(106058, 107878): Ajusta filtro de contas para período em aberto na info de demonstrativo financeiro.

- sme_ptrf_apps/users/api/validations/grupos_acesso_validations.py
- sme_ptrf_apps/users/api/views/grupos_viewset.py
- sme_ptrf_apps/users/api/views/usuarios_viewset.py
- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/gestao_usuario_service.py
Esse PR:
- Adiciona endpoint para resgatar grupos acessos permitidos na gestão de usuários dependendo da visão e dos tipos de unidades que o usuário tem acesso;
- Adiciona endpoint de habilitar e desabilitar grupos de acesso;
- Adiciona serviços e serializers relacionados;
História: AB#98106
> feat(98106): Adiciona grupos de acesso na gestão de usuários

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/users/fixtures/factories/grupo_acesso_factory.py
- sme_ptrf_apps/users/fixtures/factories/usuario_factory.py
- sme_ptrf_apps/users/fixtures/factories/visao_factory.py
- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_grupos_acesso.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_grupos_acesso.py
Esse PR:
- Adiciona testes unitários para os grupos de acesso da gestão de usuários
História: AB#98106
> feat(98106): Adiciona testes grupos acesso

- sme_ptrf_apps/core/api/serializers/conta_associacao_serializer.py
- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/analise_lancamento_prestacao_conta.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
- sme_ptrf_apps/core/services/conta_associacao_service.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_get_lancamentos_solicitacoes_acerto.py
- sme_ptrf_apps/core/tests/tests_notificacoes_services/conftest.py
- sme_ptrf_apps/despesas/admin.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_execucao_financeira_relatorio_consolidado_dre.py
- sme_ptrf_apps/sme/services/saldo_bancario_service.py
Esse PR faz merge com as seguintes histórias:
AB#107890, AB#106974, AB#104812, AB#107889, AB#106058, AB#107878, AB#107758 e AB#107654.
História: AB#108929
> Merge hotfixes sprint 77

- sme_ptrf_apps/core/models/conta_associacao.py
Esse PR:
- Altera a forma de obter o saldo exibido em dados da conta para usar o mesmo serviço usado na consulta de recursos financeiros.
Resolve AB#108880
> fix(108880): Corrige saldo exibido em dados da conta

- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Corrige a exibição do saldo nos dados da conta.
Corrige AB#108880
> fix(108880): Corrige exibição de saldo em dados da conta

- .gitignore
Esse PR:
- Apenas adiciona o .env referente a nova versão do python no gitignore
Obs: As atualizações de versão no dockerfile e arquivos jekins serão feitas em outro PR.
> feat(107228): Update Python 3.11

- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_previstos.py
- sme_ptrf_apps/receitas/tests/test_repasse/test_carga_repasse_realizados.py
Esse PR:
- Adiciona teste e corrige o identificador da carga de repasses realizados.
História: AB#108932
> fix(108932): Corrige identificador dos testes de carga

- sme_ptrf_apps/mandatos/admin.py
- sme_ptrf_apps/mandatos/api/serializers/__init__.py
- sme_ptrf_apps/mandatos/api/serializers/cargo_composicao_serializer.py
- sme_ptrf_apps/mandatos/api/serializers/ocupante_cargo_serializer.py
- sme_ptrf_apps/mandatos/api/views/cargos_composicoes_viewset.py
- sme_ptrf_apps/mandatos/api/views/ocupantes_cargos_viewset.py
- sme_ptrf_apps/mandatos/services/__init__.py
- sme_ptrf_apps/mandatos/services/cargo_composicao_service.py
- sme_ptrf_apps/mandatos/tests/conftest.py
- sme_ptrf_apps/mandatos/tests/tests_api_cargo_composicao/test_action_cargos_da_diretoria_executiva.py
- sme_ptrf_apps/mandatos/tests/tests_api_cargo_composicao/test_cargo_composicao_create.py
- sme_ptrf_apps/mandatos/tests/tests_api_cargo_composicao/test_cargo_composicao_update.py
- sme_ptrf_apps/mandatos/tests/tests_services/test_cargo_composicao_service.py
- sme_ptrf_apps/users/services/sme_integracao_service.py
- sme_ptrf_apps/users/tests/test_sme_integracao_service/test_consulta_info_estudante.py
Esse PR:
-  Implementa inclusão de novo membro no histórico de membros - Em Homologação
> feat(106047): Dados da Associação: Membros: Incluir novo membro no cargo vago (primeira composição do mandato vigente)

- sme_ptrf_apps/receitas/admin.py
- Adiciona validação no admin para atribuição de unidades
História: AB#108781
> feat(108781): Melhoria em tipos de receita por unidade

- sme_ptrf_apps/users/api/views/usuarios_viewset.py
- sme_ptrf_apps/users/services/__init__.py
- sme_ptrf_apps/users/services/gestao_usuario_service.py
- sme_ptrf_apps/users/services/verificar_unidades_usuarios_service.py
- sme_ptrf_apps/users/tasks/__init__.py
- sme_ptrf_apps/users/tasks/verificar_unidades_usuarios.py
- sme_ptrf_apps/users/tests/test_user_v2/conftest.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_grupos_acesso.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_verificacao_unidades_usuario.py
feat(98744): Rotina para validar unidades usuarios
Esse PR:
- Adiciona serviço para validar unidades
- Adiciona task assyncrona para executar o novo serviço
História: AB#98744
> feat(98744): Rotina para validar unidades usuarios

- sme_ptrf_apps/mandatos/api/serializers/cargo_composicao_serializer.py
- sme_ptrf_apps/mandatos/services/cargo_composicao_service.py
Esse PR:
-  Implementa edição de Membro no Histórico de Membros
História: AB#106054
> feat(106054): Dados da associação: Editar membro no cargo preenchido (primeira composição do mandato vigente)

- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/sme/services/exporta_dados_contas_service.py
Esse PR:
- Alterar a exportação de dados de contas de associação adicionando um rodapé com informações de ambiente e data/hora de geração do arquivo e corrige o título da coluna de motivo de rejeição de encerramento.
Atende: AB#108439
> feat(108439): Faz ajustes na exportação de contas de associação

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
Esse PR:
- Implementa verificar membros última composição na geração do demonstrativo financeiro
História: AB#105406
> feat(105406): Geração de documentos: Demonstrativo financeiro: Verificar lista de membros na última composição do mandato vigente para assinaturas

- requirements/local.txt
Esse PR:
- Atualiza versão do mypy
- Atualiza versão do flake8
- Atualiza versão do pylint-django
Atende AB#110217
> feat(110217): Atualização de pacotes

- sme_ptrf_apps/core/services/persistencia_dados_demo_financeiro_service.py
Esse PR:
- Resolve warnings celery geração de PC
História: AB#110267
> fix(110267): Investigar e resolver mensagens anormais nos logs de celery

- sme_ptrf_apps/core/api/serializers/processo_associacao_serializer.py
- sme_ptrf_apps/core/api/views/processos_associacao_viewset.py
- sme_ptrf_apps/core/fixtures/factories/__init__.py
- sme_ptrf_apps/core/fixtures/factories/prestacao_conta_factory.py
- sme_ptrf_apps/core/fixtures/factories/processo_associacao_factory.py
- sme_ptrf_apps/core/models/proccessos_associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_proccessos_associacao.py
- sme_ptrf_apps/core/tests/tests_api_processos_associacoes/test_processo_associacao_delete.py
- sme_ptrf_apps/core/tests/tests_api_processos_associacoes/test_processo_associacao_retrieve.py
Esse PR:
- Adiciona retorno sobre permissão de exclusão e mensagem tooltip
- Validação exclusão 
- Adiciona testes utilizando factories
História: AB#110070
> feat(110070): Adiciona retorno de instruções sobre exclusão de processo associação

- sme_ptrf_apps/mandatos/api/serializers/cargo_composicao_serializer.py
- sme_ptrf_apps/mandatos/api/serializers/composicao_serializer.py
- sme_ptrf_apps/mandatos/services/cargo_composicao_service.py
- sme_ptrf_apps/mandatos/services/composicao_service.py
- sme_ptrf_apps/mandatos/tests/conftest.py
feat(36588): Cria nova composição
Esse PR:
- Adiciona função ao serviço de composição para criar uma nova composição a partir de uma edição
- Adiciona validações ao serializer
- Adiciona função ao serviço de composição para encontrar uma composição anterior do mesmo mandado
História: AB#36588
> feat(36588): Cria nova composição

- sme_ptrf_apps/mandatos/services/composicao_service.py
feat(36588): Remove validacao composicao existente
Esse PR:
- Remove validação de composição existente
História: AB#36588
> feat(36588): Remove validacao composicao existente

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/fixtures/factories/membro_associacao_factory.py
- sme_ptrf_apps/users/api/validations/usuario_validations.py
- sme_ptrf_apps/users/api/views/grupos_viewset.py
- sme_ptrf_apps/users/api/views/usuarios_viewset.py
- sme_ptrf_apps/users/fixtures/factories/acesso_concedido_sme_factory.py
- sme_ptrf_apps/users/fixtures/factories/usuario_factory.py
- sme_ptrf_apps/users/services/gestao_usuario_service.py
- sme_ptrf_apps/users/services/login_usuario_service.py
- sme_ptrf_apps/users/services/verificar_unidades_usuarios_service.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_grupos_acesso.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_unidades_do_usuario.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_grupos_acesso.py
Esse PR:
- Corrige listagem de unidades na qual os grupos de acesso usavam como base.
- Adapta inclusão e exclusão dos grupos conforme nova listagem.
- Corrige visao dos grupos SME.
- Adapta testes relacionados.
História: AB#109200
> fix(109200): Corrige apresentacao e edicao unidades gestao usauarios

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_recebe_prestacao_conta.py
- Adiciona informação pendência ata de apresentação no retorno de pc
- Valida se existe ata no recebimento
História: AB#110831
> feat(110831): Adiciona informação pendência ata de apresentação no retorno de pc

- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/services/encerramento_conta_associacao_service.py
- sme_ptrf_apps/core/tests/tests_api_solicitacao_encerramento_conta_associacao/test_solicitacao_encerramento_create.py
Esse PR:
- Adiciona a verificação por conta nas despesas e receitas no momento de encerrar a conta.
História: AB#110800
> fix(110800): Adiciona verificacao conta despesas receitas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/fixtures/factories/membro_associacao_factory.py
- sme_ptrf_apps/users/api/validations/usuario_validations.py
- sme_ptrf_apps/users/api/views/grupos_viewset.py
- sme_ptrf_apps/users/api/views/usuarios_viewset.py
- sme_ptrf_apps/users/fixtures/factories/acesso_concedido_sme_factory.py
- sme_ptrf_apps/users/fixtures/factories/usuario_factory.py
- sme_ptrf_apps/users/services/gestao_usuario_service.py
- sme_ptrf_apps/users/services/login_usuario_service.py
- sme_ptrf_apps/users/services/verificar_unidades_usuarios_service.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_grupos_acesso.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_unidades_do_usuario.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_grupos_acesso.py
> fix(109200): Apresentacao grupos acesso gestao unidades

- sme_ptrf_apps/mandatos/api/serializers/cargo_composicao_serializer.py
- sme_ptrf_apps/mandatos/services/composicao_service.py
- Corrige retorno de composição criada
- Corrige retorno de composição anterior
História: AB#105420
> feat(105420): Corrige retorno de composições

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/ata.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_recebe_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_serializer.py
- Corrige validação de ata gerada para checar status do pdf
História: AB#110831
> feat(110831): Corrige validação de ata gerada para checar status do pdf

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- Corrige condição de checagem de pendência de geração de ata
História: AB#110895
> feat(110895): Corrige condição de checagem de pendência de geração de ata

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- Corrige condição de checagem de pendência de geração de  ata
História: AB#110895
> Merge ajuste 110895 em homolog

- sme_ptrf_apps/core/services/notificacao_services/notificacao_pendencia_geracao_ata.py
- sme_ptrf_apps/dre/tests/tests_services/tests_notificacoes_services/test_notificacoes_pendencia_geracao_ata_apresentacao.py
- Ajusta mensagem da notificação
História: AB#110895
> feat(110895): Ajusta mensagem da notificação

- sme_ptrf_apps/core/models/unidade.py
- sme_ptrf_apps/core/services/notificacao_services/notificacao_pendencia_geracao_ata.py
- sme_ptrf_apps/dre/tests/tests_services/tests_notificacoes_services/test_notificacoes_pendencia_geracao_ata_apresentacao.py
- Ajusta mensagem para utilizar o nome da DRE reduzido.
História: AB#110895
> feat(110895): Ajusta mensagem da notificação v2

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- Corrige serialização de dados em despesas
História: AB#110828
> fix(110828): Corrige serialização de dados em despesas

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/core/models/acao_associacao.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_create.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_update.py
- Adiciona validação para não permitir ação associação iguais
- Adiciona testes
- Algumas mudanças de formatação automática pep8.
História: AB#111951
> fix(111951): Adiciona validação para não permitir ação associação iguais

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/serializers/acao_associacao_serializer.py
- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/core/models/acao_associacao.py
- sme_ptrf_apps/core/services/acoes_associacoes_service.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_create.py
- Muda estratégia de validação de ação associação para não impactar nos testes
História: AB#111951
> fix(111951): Muda estratégia de validação de ação associação para não impactar nos testes

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/tasks/concluir_consolidado_dre.py
- Corrige queryset de associações no fluxo de consolidado dre
Obs: Algumas mudanças automáticas de formatação usando pep8
História: AB#111217
> fix(111217): Corrige queryset de associações no fluxo de consolidado dre

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/tasks/concluir_consolidado_dre.py
-  Corrige mais pontos de busca de associações
História: AB#111217
> fix(111217): Corrige mais pontos de busca de associações

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- Descomenta linha que ordenava lista de informaçoes por conta nos dados necessário para mostrar valor de devolução ao tesouro em alguns cenários.
História: AB#111893
> fix(111893): Descomenta linha que ordenava lista de informaçoes por conta nos dados

- sme_ptrf_apps/core/services/relacao_bens_dados_service.py
Esse PR:
- Adiciona no bloco de assinatura o presidente da composição vigente. (Incluindo no caso de persistência de dados da nova geração de PC)
História: AB#105405
> feat(105405): Adiciona assinatura presidente composicao vigente

- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/mandatos/services/__init__.py
- sme_ptrf_apps/mandatos/services/cargo_composicao_service.py
- sme_ptrf_apps/mandatos/tests/tests_services/test_cargo_composicao_service.py
Esse PR:
- Insere validação para exibição de ícone de pendência no Histórico de Membros
História: AB#108697
> feat(108697): Histórico de Membros - Inserir ícone de membro faltante no mandato vigente

- sme_ptrf_apps/dre/services/valores_reprogramados_dre_service.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_filtros.py
fix(111683): Exibicao contas conforme parametro dre
Esse PR:
- Adiciona nome das contas ao retorno da API
História: AB#111683
> fix(111683): Exibicao contas conforme parametro dre

- sme_ptrf_apps/dre/services/valores_reprogramados_dre_service.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_filtros.py
> fix(111683): Exibição contas de acordo com parametro

- sme_ptrf_apps/despesas/models/despesa.py
fix(111237) Cadastro despesa
Esse PR:
- Adiciona validação de data a property de periodo_da_despesa
História: AB#111237
> fix(111237) Cadastro despesa

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_encerrar_acesso_suporte_unidade.py
- Implementa rota encerrar suporte em lote
- Implementa teste
História: AB#110945
> feat(110945): Encerrar suporte em lote

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_get_prestacoes_contas_tabelas.py
- Adiciona retorno de status selecionáveis para conclusão PC
- Atualiza teste
História: AB#111928
> tec(111928): Novo retorno de status selecionáveis conclusão PC

- sme_ptrf_apps/core/services/relacao_bens.py
- sme_ptrf_apps/core/services/relacao_bens_dados_service.py
feat(104121) Ajuste novo processo PC
Esse PR:
- Realiza ajuste na prévia do relatório de relação de bens
História: AB#104121
> feat(104121) Ajuste novo processo PC

- sme_ptrf_apps/core/api/serializers/conta_associacao_serializer.py
- sme_ptrf_apps/core/fixtures/factories/solicitacao_encerramento_conta_associacao_factory.py
- sme_ptrf_apps/core/tests/tests_services/tests_valores_reprogramados_service/test_valores_reprogramados_services.py
- sme_ptrf_apps/dre/services/valores_reprogramados_dre_service.py
- Adiciona retorno para bloquear campo em valores reprogramados
- Adiciona retorno para mudar mensagem na solicitação de encerramento de conta
História: AB#109691
> feat(109691): Adiciona retornos para bloquear campo e mudar mensagem em valores reprogramados

- sme_ptrf_apps/core/tests/tests_services/tests_valores_reprogramados_service/test_valores_reprogramados_services.py
> feat(109691): Corrige teste

- sme_ptrf_apps/users/tests/test_api_user/test_api_update_user.py
Esse PR:
- Corrige ordenamento das visões no teste test_api_update_user.py
História: AB#110668
> feat(110668): Corrige ordenamento do teste

- sme_ptrf_apps/core/services/falha_geracao_pc_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_falha_geracao_pc_service/test_falha_geracao_service.py
Esse PR:
- Remove mensagens de falha de geração de PC do backend para serem tratadas no frontend;
História: AB#112558
> feat(112558): Remove mensagens falha geracao PC

- sme_ptrf_apps/core/api/serializers/conta_associacao_serializer.py
- sme_ptrf_apps/core/tests/test_api_contas/test_get_contas.py
- Corrige retorno do campo mostrar_alerta_valores_reprogramados_ao_solicitar
- Adiciona testes
História: AB#109691
> feat(109691): Corrige retorno contas

- requirements/base.txt
feat(113140) Atualiza versão django
Esse PR:
- Atualiza django para versão 4.2.9
História: AB#113140
> feat(113140) Atualiza versão django

- sme_ptrf_apps/users/api/serializers/usuario_serializer.py
feat(113377) Inclui tag acesso sme
Esse PR:
- Adiciona informação de acesso concedido sme ao endpoint
História: AB#113377
> feat(113377) Inclui tag acesso sme

- sme_ptrf_apps/mandatos/api/serializers/cargo_composicao_serializer.py
- sme_ptrf_apps/mandatos/api/serializers/composicao_serializer.py
- sme_ptrf_apps/mandatos/services/composicao_service.py
- sme_ptrf_apps/mandatos/tests/conftest.py
- sme_ptrf_apps/mandatos/tests/tests_api_cargo_composicao/test_cargo_composicao_update.py
- sme_ptrf_apps/mandatos/tests/tests_services/test_composicao_service.py
Esse PR:
- Implementa saída do membro no cargo no histórico de membros
História: AB#112659
> feat(112659): Dados da Associação: Histórico de membros: Informar saída do membro no cargo

- sme_ptrf_apps/logging/loggers.py
Esse PR:
- Remove prints e imports não usados
> feat(113127): Remove prints e imports não usados

- sme_ptrf_apps/mandatos/api/serializers/mandato_serializer.py
- sme_ptrf_apps/mandatos/models/cargo_composicao.py
- sme_ptrf_apps/mandatos/models/composicao.py
- sme_ptrf_apps/mandatos/models/mandato.py
- sme_ptrf_apps/mandatos/tests/tests_api_mandato/test_mandato_update.py
feat(108553) Parametrizacoes mandatos
Esse PR:
- Altera validações serializer mandatos
- Adiciona método para atualizar composicoes e seus cargos de um mandato
História: AB#108553
> feat(108553) Parametrizacoes mandatos

- sme_ptrf_apps/mandatos/api/serializers/cargo_composicao_serializer.py
- sme_ptrf_apps/mandatos/models/cargo_composicao.py
- sme_ptrf_apps/mandatos/services/composicao_service.py
- Modifica lógica de saída do membro
História: AB#112659
> feat(112659): Ajuste fluxo saída do membro

- requirements/base.txt
Esse PR:
- Atualiza a versão do Django para a 4.2.10 resolvendo vulnerabilidades.
Atende AB#115142
> feat(115142): Atualiza a versão do Django para a 4.2.10

- requirements/base.txt
Esse PR:
- Atualiza versão do Pillow para a 10.2.0 que resolve vulnerabilidades.
Atende AB#115144
> feat(115144): Atualiza versão do Pillow

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/fixtures/factories/associacao_factory.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_cadastro.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
- sme_ptrf_apps/mandatos/fixtures/factories/__init__.py
- sme_ptrf_apps/mandatos/fixtures/factories/composicao_factory.py
- sme_ptrf_apps/mandatos/fixtures/factories/mandato_factory.py
- sme_ptrf_apps/mandatos/services/mandato_service.py
- Adiciona pendência de novo mandado em pendências cadastrais
História: AB#102526
> feat(102526): Adiciona pendência novo mandado em pendências cadastrais

- sme_ptrf_apps/core/api/views/presentes_ata_viewset.py
- sme_ptrf_apps/mandatos/services/cargo_composicao_service.py
Esse PR:
- Adiciona o resgate de membros pelo identificador caso exista uma composição na ata;
História: AB#105234
> feat(105234): Adiciona resgate membros por identificador

- sme_ptrf_apps/core/services/exporta_associacao.py
feat(113475): Exportar dados associacao
Esse PR:
- Altera serviço de extração de dados associação para considerar novo cadastro de membros
- Adiciona condicional por feature flag (historico-de-membros)
Historia: AB#113475
> feat(113475): Exportar dados associacao

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_associacao/test_associacao_model.py
- sme_ptrf_apps/mandatos/fixtures/factories/__init__.py
- sme_ptrf_apps/mandatos/fixtures/factories/cargo_composicao_factory.py
- sme_ptrf_apps/mandatos/fixtures/factories/ocupante_cargo_factory.py
- sme_ptrf_apps/mandatos/fixtures/providers/cargo_composicao_provider.py
- sme_ptrf_apps/mandatos/fixtures/providers/ocupante_cargo_provider.py
- sme_ptrf_apps/templates/pdf/associacoes/exportarpdf/pdf.html
feat(113476): Exportar ficha associacao
Esse PR:
- Altera serviço de extração de ficha para considerar novo cadastro de membros
- Adiciona factory para o modelo OcupanteCargo
- Adiciona factory para o modelo CargoAssociacao
- Adiciona função ao modelo de Associacao para retornar dados do presidente
História: AB#113476
> feat(113476): Exportar ficha associacao

- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/mandatos/services/mandato_service.py
- Ajusta método checar pendencia mandato
-
História: AB#102526
> feat(102526): Ajusta método checar pendência mandato

- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- Reutiliza método lancamentos_da_prestacao para retornar listagem de despesas de períodos anteriores, com ajuste e contas dessas despesas.
História: AB#101259
> feat(101259): Seção despesas de períodos anteriores

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
Esse PR:
- Corrige a criação do arquivo em processamento na central de downloads.
História: AB#116161
> fix(116161): Corrige extracao de dados de creditos

- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_creditos.py
Esse PR:
- Corrige os testes da exportação dos dados de créditos.
História: AB#116161
> fix(116161): Corrige teste de exportacao dados de credito

- sme_ptrf_apps/dre/admin.py
Esse PR altera o admin de atribuições de técnicos DRE:
- Inclui filtros por DRE e período.
- Inclui busca por EOL e nome unidade
- Inclui busca por técnico (tf e nome)
Atende AB#116407
> feat(116407): Altera admin de atribuição

- sme_ptrf_apps/dre/admin.py
Esse PR altera o admin de presentes da ata DRE:
- Inclui filtros por DRE e período.
- Inclui busca por presente (RF e nome)
- Inclui busca por nome da DRE
Atende AB#116408
> feat(116408): Altera admin de presentes ata DRE

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/tipos_acerto_lancamento_viewset.py
- sme_ptrf_apps/core/fixtures/factories/__init__.py
- sme_ptrf_apps/core/fixtures/factories/tipo_acerto_lancamento_factory.py
- sme_ptrf_apps/core/models/tipo_acerto_lancamento.py
- sme_ptrf_apps/core/tests/tests_api_tipos_acerto_lancamento/test_tipos_acerto_lancamento_endpoint_tabelas.py
- Adiciona filtro tabela tipos de acerto
História: AB#114584
> feat(114584): Adiciona filtro tabela tipos de acerto

- sme_ptrf_apps/users/api/views/grupos_viewset.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_grupos_acesso.py
fix(116606): Corrige mensagem grupo de acesso
Esse PR:
- Corrige mensagem ao desabilitar grupo de acesso
- Corrige mensagem ao habilitar grupo de acesso
História: AB#116606
> fix(116606): Corrige mensagem grupo de acesso

- sme_ptrf_apps/sme/services/exporta_saldo_final_periodo_pc_service.py
fix(117155): Extração de dados de saldo periodo
Esse PR:
- Adiciona validação de existencia do FechamentoPeriodo a extração
História: AB#117155
> fix(117155): Extração de dados de saldo periodo

- sme_ptrf_apps/users/api/views/usuarios_viewset.py
Esse PR:
- Altera a forma de determinar se o usuário é ou não membro da diretoria da associação passando a
considerar o novo histórico de membros.
Atende AB#116411
> feat(116411): Altera consulta de status do usuário

- sme_ptrf_apps/core/admin.py
Esse PR:
- Adiciona filtro por dre nas solicitações de encerramento de conta;
- Adiciona codigo_eol da unidade na listagem de solicitação de encerramento de conta;
História: AB#116397
> feat(116397): Adiciona filtro dre solicitacao encerramento conta

- sme_ptrf_apps/core/admin.py
Esse PR:
- Adiciona o filtro por Dre no admin dos dados do demonstrativo financeiro;
História: AB#116398
> feat(116398): Adiciona filtro Dre dados demonstrativo financeiro

- sme_ptrf_apps/core/admin.py
Esse PR:
- Adiciona o filtro por Dre no admin de atas;
- Adiciona busca por codigo_eol Dre no admin;
- Adiciona raw_id para melhorar performance de carregamento da página,
História: AB#116339
> feat(116339): Adiciona filtro dre no admin de atas

- requirements/base.txt
Esse PR atualiza as versões dos pacotes:
- celery
- redis
- django-redis
- django-celery-beat
- flower
> build(113164): Atualiza pacotes relacionados ao celery e redis

- sme_ptrf_apps/core/admin.py
Essa hIstória:
- Adiciona filtro por dre no admin de analise de contas de pc;
- Adiciona a coluna de id da unidade no admin de analise de contas.
HIstória: AB#116400
> feat(116400): Adiciona filtro de dre na analise de contas pc

- sme_ptrf_apps/core/admin.py
Esse PR:
- Troca o filtro de referência de período para o período.
- Troca campo para raw_id otimizando carregamento e busca.
HIstória: AB#116405
> feat(116405): Troca filtro referencia por periodo ata

- sme_ptrf_apps/core/admin.py
Esse PR:
- Troca o filtro de referência de período para período;
- Troca campos para raw_id otimizando carregamento e busca.
História: AB#116404
> feat(116404): Troca filtro referencia por periodo

- sme_ptrf_apps/core/admin.py
Esse PR:
- Troca o filtro de referência pelo filtro de período.
História: AB#116403
> feat(116403): Adiciona filtro periodo solicitacoes acertos

- sme_ptrf_apps/users/tests/test_user_v2/test_service_gestao_usuario.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_login_usuario.py
- sme_ptrf_apps/users/tests/test_user_v2/test_service_verificacao_unidades_usuario.py
feat(116403): Ajuste testes
Esse PR:
- Adiciona mock que estava faltando a alguns testes
História: AB#116403
> feat(116403): Ajuste testes

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/fixtures/factories/__init__.py
- sme_ptrf_apps/core/fixtures/factories/analise_lancamento_prestacao_conta_factory.py
- sme_ptrf_apps/core/fixtures/factories/analise_prestacao_conta_factory.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_contas_com_acertos_em_despesas_periodos_anteriores.py
- Adiciona rota contas com acertos em despesas períodos anteriores
- Adiciona teste usando factory 
História: AB#114585
> feat(114585): Adiciona rota contas com acertos em despesas períodos anteriores

- sme_ptrf_apps/core/admin.py
Esse PR:
- Troca o filtro de conta para tipo de conta no admin de previsão de repases da sme;
História: AB#116402
> feat(116402): Troca filtro de conta para tipo de conta

- sme_ptrf_apps/users/api/serializers/usuario_serializer.py
fix(117181): Corrige vinculo visao sme
Esse PR:
- Adiciona validação ao create e update
História: AB#117181
> fix(117181): Corrige vinculo visao sme

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- Ajusta busca de rateios para conciliação no período
História: AB#101266
> feat(101266): Ajusta busca de rateios para conciliação no período

- sme_ptrf_apps/core/services/dados_relatorio_apos_acertos_service.py
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/partials/tabela-acertos-em-despesas-periodos-anteriores.html
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/pdf.html
- Adiciona seção despesas anteriores no relatório após acerto
História: AB#101268
> feat(101268): Adiciona seção despesas anteriores no relatório após acerto

- sme_ptrf_apps/sme/services/exporta_dados_contas_service.py
fix(117469): Extração dados contas
Esse PR:
- Altera serviço de extração para criar o registro na central de downloads antes de percorrer todos os dados
História: AB#117469
> fix(117469): Extração dados contas

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- Ajusta retorno contas com ajustes
História: AB#114585
> feat(114585): Ajusta retorno contas com ajustes

- requirements/base.txt
Esse PR:
- Atualiza a versão do Django para a 4.2.11
Atende AB#117204
> build(117204): Atualiza versão do Django

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
Esse PR:
- Corrige o layout da extração de créditos que transia conteúdo não relacionado às colunas.
Corrige AB#118285
> fix(118285): Corrige layout extração créditos

- sme_ptrf_apps/receitas/admin.py
- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_repasses_service.py
- sme_ptrf_apps/sme/tasks/__init__.py
- sme_ptrf_apps/sme/tasks/exportar_repasses.py
- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_repasses/test_exportacoes_dados_repasses.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_repasses/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_repasses/test_exportacoes_repasses.py
feat(117716): Extração dados repasse
Esse PR:
- Adiciona tarefa assincrona para extrair dados repasse
- Adiciona endpoint para extrair dados repasse
- Adiciona serviço para extrair dados repasse
História: AB#117716
> feat(117716): Extração dados repasse

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/proccessos_associacao.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/services/processos_services.py
Esse PR altera o acompanhamento de PC para que passe a considerar o período em:
- Lista de PCs não recebidas e não apresentadas
- Lista de PCs por status
- Lista de todas as PCs
- Retrieve de associação
- Atualização do processo
Atende AB#117542
> feat(117542) Processos por período no acompanhamento de PC

- sme_ptrf_apps/sme/services/exporta_relacao_bens_pc.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_relacoes_bens/test_exportacoes_relacao_bens.py
feat(117731): Extração dados relação bens
Esse PR:
- Adiciona informacao de filtro utilizado ao serviço de extração
História: AB#117731
> feat(117731): Extração dados relação bens

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_creditos.py
Esse PR alterar a extração de créditos:
- Passa a enviar informações de filtro para a central de download
- Inclui um rodapé com informações sobre a extração.
Atende AB#117729
> feat(117729) Alterações da extração de créditos

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_creditos.py
Esse PR:
- Altera os textos do filtro no campo informações da central de download.
> feat(117729): Ajuste em textos na exportação de créditos

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_creditos.py
Altera os textos do filtro no campo informações
da central de download.
Remove bloco comentado.
> feat(117729): Ajuste em textos

- sme_ptrf_apps/despesas/admin.py
- sme_ptrf_apps/sme/services/exporta_rateios_service.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_rateios/test_exportacoes_dados_rateios.py
feat(117734): Extração dados rateios
Esse PR:
- Adiciona informação de filtros utilizados na extração
História: AB#117734
> feat(117734): Extração dados rateios

- sme_ptrf_apps/sme/services/exporta_relacao_bens_pc.py
- sme_ptrf_apps/sme/services/exporta_repasses_service.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_repasses/test_exportacoes_repasses.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_relacoes_bens/test_exportacoes_relacao_bens.py
feat(117731): Extração dados
Esse PR:
- Realiza ajuste texto
História: AB#117731
> feat(117731): Extração dados

- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/tasks/__init__.py
- sme_ptrf_apps/core/tasks/gerar_previa_relatorio_apos_acertos_v2.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_regerar_previa_relatorio_apos_acertos.py
- Adiciona rota para regerar prévia relatório após acerto
História: AB#117529
> fix(117529): Adiciona rota para regerar prévia relatório após acerto

- sme_ptrf_apps/sme/services/exporta_status_prestacoes_conta_service.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_status_prestacoes_conta/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_status_prestacoes_conta/test_exportacoes_status_prestacoes_conta.py
Esse PR:
- Adiciona coluna DRE no csv de extracao;
- Corrige apresentacao na central de download;
- Modifica rodape;
- Adiciona PCs nao apresentadas na extracao de status de pc;
História: AB#117426
> feat(117426): Adiciona pcs nao apresentadas extracao status pcs

- sme_ptrf_apps/mandatos/services/cargo_composicao_service.py
- sme_ptrf_apps/mandatos/tests/tests_api_cargo_composicao/test_cargo_composicao_list.py
- sme_ptrf_apps/mandatos/tests/tests_services/test_cargo_composicao_service.py
- Adiciona retorno campo extra de data fim para composições passadas
História: AB#118297
> fix(118297): Adiciona retorno campo extra de data fim para composições passadas

- sme_ptrf_apps/sme/services/exporta_demonstrativos_financeiros_service.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_status_prestacoes_conta/test_exportacoes_demonstrativos_financeiros.py
feat(117735): Extração dados demonstrativo financeiro
Esse PR:
- Adiciona informação de filtros utilizados na extração
História: AB#117735
> feat(117735): Extração dados demonstrativo financeiro

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_dados_membros_apm_service.py
- sme_ptrf_apps/sme/tasks/__init__.py
- sme_ptrf_apps/sme/tasks/exportar_membros_apm.py
- sme_ptrf_apps/sme/tests/test_api_exportacoes_dados_membros_apm/test_exportacoes_dados_membros_apm.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_membros_apm/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_membros_apm/test_exportacoes_membros_apm.py
Esse PR:
- Adiciona a extracao de dados dos membros apm.
História: AB#117565
> feat(117565): Adiciona extracao de dados membros apm

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_status_prestacoes_conta_service.py
- sme_ptrf_apps/sme/tasks/exportar_status_prestacoes_contas.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_status_prestacoes_conta/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_status_prestacoes_conta/test_exportacoes_status_prestacoes_conta.py
Esse PR:
- Implementa extração de dados Status PC na visão DRE
História: AB#117454
> feat(117454): Extração de dados: Incluir extração de dados de Prestações de contas: Status

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_dados_processos_sei_regularidade_service.py
- sme_ptrf_apps/sme/tasks/__init__.py
- sme_ptrf_apps/sme/tasks/exportar_processos_sei_regularidade.py
- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_processos_sei_regularidade/test_exportacoes_dados_processos_sei_regularidade.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacoes_dados_processos_sei_regularidade/test_exportacoes_dados_processos_sei_regularidade.py
- Adiciona rota, serviço e testes para exportação de processos sei de regularidade
História: AB#117566
> feat(117566): Adiciona rota, serviço e testes para exportação de processos sei de regularidade

- sme_ptrf_apps/sme/services/exporta_atas_service.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_atas/test_exportacoes_atas.py
Esse PR:
- Corrige o filtro por dadas da extração de atas de pc.
AB#117733
> feat(117733): Ajusta filtro por data.

- sme_ptrf_apps/sme/services/exporta_dados_contas_service.py
- sme_ptrf_apps/sme/services/exporta_demonstrativos_financeiros_service.py
- sme_ptrf_apps/sme/services/exporta_rateios_service.py
- sme_ptrf_apps/sme/services/exporta_relacao_bens_pc.py
- sme_ptrf_apps/sme/services/exporta_repasses_service.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_contas/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_contas/test_exportacoes_dados_contas.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_rateios/test_exportacoes_dados_rateios.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_repasses/test_exportacoes_repasses.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_relacoes_bens/test_exportacoes_relacao_bens.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_status_prestacoes_conta/test_exportacoes_demonstrativos_financeiros.py
feat(117737): Extração dados contas
Esse PR:
- Corrige filtro por data extracao rateios
- Corrige filtro por data extracao relacao bens
- Corrige filtro por data extracao repasses
- Corrige filtro por data extracao demonstrativo financeiro
- Corrige filtro por data extracao dados das contas
- Adiciona metodo ao serviço de extracao dados das contas para retornar os filtros utilizados
- Adiciona e modifica testes relacionados
História: [AB#117737](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/117737)
> feat(117737): Extração dados contas

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/tasks/exportar_relacao_bens.py
Esse PR:
- Implementa a exportação de relações de bens também na visão de DRE.
Atende [AB#118383](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118383)
> feat(118383): Exportação de Relações de bens na DRE

- sme_ptrf_apps/core/models/proccessos_associacao.py
- sme_ptrf_apps/core/tasks/__init__.py
- sme_ptrf_apps/core/tasks/vincula_processo_sei_a_periodos.py
feat(118500): Vinculo processos a periodos
Esse PR:
- Adiciona script para vincular processos a periodos
História: [AB#118500](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118500)
> feat(118500): Vinculo processos a periodos

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_devolucao_tesouro_prestacoes_conta.py
- sme_ptrf_apps/sme/tasks/exportar_devolucoes_ao_tesouro.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_devolucao_tesouro/test_exportacoes_devolucao_tesouro_pc.py
Esse PR:
- Inclui a extração de devolução ao tesouro na visão de DRE
- Inclui coluna DRE
- Remove ";" dos textos
- Exibe filtro em rodapé
- Envia filtro para a central de downloads
[AB#118384](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118384)
> feat(118384): Add extração devolução tesouro em DRE e melhorias

- config/api_router.py
- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/__init__.py
- sme_ptrf_apps/core/api/views/parametrizacoes_associacoes.py
- sme_ptrf_apps/core/services/unidade_service.py
feat(118528): Parametrizacoes associacoes
Esse PR:
- Adiciona viewset para listar associacoes
História: [AB#118528](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118528)
> feat(118528): Parametrizacoes associacoes

- sme_ptrf_apps/sme/services/exporta_relacao_bens_pc.py
Esse PR:
- Inclui na extração de relações de bens o tratamento de ";" 
[AB#118383](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118383)
> feat(118383): Faz tratamento de ;

- sme_ptrf_apps/receitas/admin.py
- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_repasses_service.py
- sme_ptrf_apps/sme/tasks/exportar_repasses.py
- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_repasses/test_exportacoes_dados_repasses.py
Esse PR:
- Implementa Dre Extração de Dados - Repasses
História: [AB#117717](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/117717)
> feat(117717): Extração de dados: Incluir extração de dados Repasses e exibir o filtro aplicado na Central de downloads

- sme_ptrf_apps/core/services/unidade_service.py
feat(118528): Corrige validação consulta unidade
Esse PR:
- Adiciona validação na funcao "consulta_unidade" para casos em que é retorno um valor None
História: [AB#118528](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118528)
> feat(118528): Corrige validação consulta unidade

- sme_ptrf_apps/core/services/unidade_service.py
feat(118528): Corrige mensagem
Esse PR:
- Corrige mensagem de erro
História: [AB#118528](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118528)
> feat(118528): Corrige mensagem

- sme_ptrf_apps/core/api/views/parametrizacoes_acoes_associacoes.py
- sme_ptrf_apps/core/api/views/parametrizacoes_associacoes.py
Esse PR:
- Resolve Filtrar por Informações em Parametrizações Associação
Historia: [AB#119436](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119436)
> fix(119436): Parametrizações: Associações: Filtro de informações não filtra as opções selecionadas

- sme_ptrf_apps/core/api/views/parametrizacoes_acoes_associacoes.py
- sme_ptrf_apps/core/api/views/parametrizacoes_associacoes.py
- sme_ptrf_apps/core/services/unidade_service.py
História: [AB#118225](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118225)
> Posição em Develop 12/04/2024 às 12:00 h

- sme_ptrf_apps/receitas/admin.py
- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
- sme_ptrf_apps/sme/tasks/exportar_receitas.py
- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_creditos.py/test_exportacoes_dados_creditos.py
feat(118381): Extração de dados créditos
Esse PR:
- Adiciona validação para substituir ; por ,
História: [AB#118381](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118381)
> feat(118381): Extração de dados créditos

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_dados_processos_sei_prestacoao_contas_service.py
- sme_ptrf_apps/sme/tasks/__init__.py
- sme_ptrf_apps/sme/tasks/exportar_processos_sei_prestacao_contas.py
- sme_ptrf_apps/sme/tests/test_api_exportacao_dados_processos_sei_prestacao_contas/test_exportacao_dados_processos_sei_prestacao_contas.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacao_dados_processos_sei_prestacao_contas/test_exportacao_dados_processos_sei_prestacao_contas.py
- Implementa serviço e rota para exportar processos sei prestação contas
História: [AB#118499](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118499)
> feat(118499): Implementa serviço e rota para exportar processos sei prestação contas

- sme_ptrf_apps/core/models/unidade.py
- sme_ptrf_apps/core/services/processa_cargas.py
- sme_ptrf_apps/users/services/carga_usuario_v2_service.py
- sme_ptrf_apps/users/services/gestao_usuario_service.py
feat(118804): Carga usuarios em gestão usuarios
Esse PR:
- Adiciona condição por feature flag para executar a nova carga de usuários
- Adiciona serviço para carga de usuários considerando regras da gestão de usuários
- Altera serviço GestaoUsuarioService para utilizar metodos chaves atraves de class_method
História: [AB#118804](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118804)
> feat(118804): Carga usuarios em gestão usuarios

- sme_ptrf_apps/contrib/checa_processos_duplicados.py
- sme_ptrf_apps/core/api/serializers/processo_associacao_serializer.py
- sme_ptrf_apps/core/tests/tests_api_processos_associacoes/test_processo_associacao_create.py
- sme_ptrf_apps/core/tests/tests_api_processos_associacoes/test_processo_associacao_update.py
Esse PR:
- Altera a API de processos de PC para não permitir a gravação de processos já usados.
Atente [AB#119725](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/119725)
> feat(119725) Validação de unicidade do processo de PC

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_atas_service.py
- sme_ptrf_apps/sme/tasks/exportar_atas.py
- sme_ptrf_apps/sme/tests/test_api_exportacao_dados_atas/test_exportacao_dados_atas.py
- Adiciona filtro por DRE
- Adiciona teste para a rota da api
- Adiciona formatação de valores
História: [AB#118385](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118385)
> feat(118385): Implementa extração de Ata na visão DRE

- sme_ptrf_apps/users/admin.py
- Adiciona filtro admin por "e_servidor" em acesso concedido SME
História: [AB#120416](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120416)
> feat(120416): Adiciona filtro admin em  acesso concedido SME

- sme_ptrf_apps/users/admin.py
- Adiciona filtro admin "e_servidor" em user
História: [AB#120415](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120415)
> feat(120415): Adiciona filtro admin em user

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/users/admin.py
- Adiciona filtro admin em falha na geração de pc
História: [AB#120398](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120398)
> feat(120398): Adiciona filtro admin em falha na geração de pc

- sme_ptrf_apps/sme/services/exporta_atas_service.py
- sme_ptrf_apps/sme/services/exporta_dados_processos_sei_prestacoao_contas_service.py
- Ajusta formatação de texto.
História: [AB#118499](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118499)
> feat(118499): Ajusta formatação

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_demonstrativos_financeiros_service.py
- sme_ptrf_apps/sme/tasks/exportar_demonstrativos_financeiros.py
- sme_ptrf_apps/sme/tests/test_api_exportacao_demonstrativo_financeiro.py/test_exportacao_dados_demonstativo_financeiro.py
Esse PR:
- Substitui ponto e virgula por ponto para evitar quebra de linha indesejada;
- Adiciona filtro de resultado por dre na extração de dmeonstrativo financeiro;
- Adiciona teste relacionado.
História: [AB#118387](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118387)
> feat(118387): Adiciona extracao demo financeiro na DRE

- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_documentos_despesas.py
- sme_ptrf_apps/sme/tasks/exportar_documentos_despesas.py
Esse PR:
- Implementa a extração de despesas na visão de DRE.
Atende [AB#118388](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118388)
> feat(118388): Add extração de despesas em DRE

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
Esse PR:
- Corrige concluir período erro tentativas
História: [AB#121314](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/121314)
> fix(121314): geração de documento:Concluir período:erro tentativas 

- sme_ptrf_apps/receitas/api/serializers/__init__.py
- sme_ptrf_apps/receitas/api/serializers/repasse_serializer.py
- sme_ptrf_apps/receitas/api/views/repasse.py
- sme_ptrf_apps/receitas/models/repasse.py
feat(33155): Parametrizações repasse
Esse PR:
- Adiciona validação para exclusão
- Altera serializer utilizado
- Altera permissão da API
História: [AB#33155](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/33155)
> feat(33155): Parametrizações repasse

- sme_ptrf_apps/receitas/api/serializers/repasse_serializer.py
- sme_ptrf_apps/sme/api/views/exportacoes_dados.py
- sme_ptrf_apps/sme/services/exporta_dados_contas_service.py
- sme_ptrf_apps/sme/tasks/exportar_dados_contas.py
- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_contas.py/test_exportacoes_dados_contas.py
feat(118389): Extração de contas dre
Esse PR:
- Adiciona filtro por DRE para a extração
- Adiciona validação de ponto e virgulo nos campos
História: [AB#118389](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/118389)
> feat(118389): Extração de contas dre

- sme_ptrf_apps/sme/services/exporta_documentos_despesas.py
Corrige bug: [AB#120967](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/120967)
> fix(120967): Corrige SME extração de dados quebra de linha

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
Corrige bug: [AB#121314](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/121314)
> fix(121314): Corrige concluir período erro tentativas

- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/services/despesa_service.py
- sme_ptrf_apps/despesas/tasks/__init__.py
- sme_ptrf_apps/despesas/tasks/migrar_gastos_periodos_anteriores.py
Esse PR:
- Atualiza despesas com data de transação anterior ao período inicial de sua associação e atualiza os campos despesa_anterior_ao_uso_do_sistema e despesa_anterior_ao_uso_do_sistema_pc_concluida.
- Corrige a lógica que determina se uma despesa é anterior.
Atende AB#122906
> feat(122906): Implementa migração de períodos anteriores

- sme_ptrf_apps/core/tests/tests_dados_demo_financeiro_service/test_blocos_de_despesas.py
Esse PR:
- Corrige teste
História: AB#122998
> fix(122998): Ajusta teste

- sme_ptrf_apps/despesas/models/rateio_despesa.py
- Corrige filtro por data transacao para rateios de periodos anteriores
História: [AB#123234](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/123234)
> fix(123234): Corrige filtro por data transacao para rateios de periodos anteriores

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- Corrige filtro de rateios de períodos anteriores em contas
História: [AB#123089](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/123089)
> fix(123089): Corrige filtro de rateios de períodos anteriores em contas

- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_unidades/test_exportacoes_unidades.py
Esse PR:
Melhora a cobertura de testes sobre a task desenvolvida
História: 124176
> feature(124190): Aumentando teste de cobertura sobre a task desenvolvida

- sme_ptrf_apps/sme/services/exporta_dados_unidades_service.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacoes_dados_unidades/test_exportacoes_unidades.py
acompanhar pipeline de testes, outros arquivos subiram no mesmo commit e precisei realizar um revert
> Inclusão de acentuação na coluna (Numero) no cabeçalho da tabela de exportação de unidades

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/fixtures/factories/associacao_factory.py
- sme_ptrf_apps/sme/services/exporta_associacoes_service.py
- sme_ptrf_apps/sme/tests/tests_services/test_exportacao_associacoes/test_exportacao_dados_associacoes.py
Alteração do valor do campo ID do Período Inicial de uuid para id.
Adição de factory de Associação com o campo periodo preenchido.
Ajustes no teste unitário para validar o campo id
> feature(124183): Alteração do valor do campo ID do Período Inicial de uuid para id

- sme_ptrf_apps/despesas/api/views/tipo_documento_viewset.py
Esse PR:
Ajusta as permissões da API Tipos de documentos
Historia AB#124182
> feature(124182): ajuste de permissões

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/despesas/api/serializers/motivo_pagamento_antecipado_serializer.py
- sme_ptrf_apps/despesas/api/views/motivos_pagamento_antecipado_viewset.py
- sme_ptrf_apps/despesas/fixtures/factories/__init__.py
- sme_ptrf_apps/despesas/fixtures/factories/motivo_pagamento_antecipado_factory.py
- sme_ptrf_apps/despesas/tests/tests_motivos_pagamentos_antecipados/conftest.py
- sme_ptrf_apps/despesas/tests/tests_motivos_pagamentos_antecipados/test_motivo_pagamento_antecipado_serialiazer.py
- sme_ptrf_apps/despesas/tests/tests_motivos_pagamentos_antecipados/test_motivo_pagamento_antecipado_viewset.py
Esse PR:
Adiciona API para Motivos de pagamento antecipado
História AB#124988
> Feature/124988 api motivos pagamento antecipado 

- config/api_router.py
- sme_ptrf_apps/core/api/serializers/__init__.py
- sme_ptrf_apps/core/api/serializers/conta_associacao_serializer.py
- sme_ptrf_apps/core/api/views/__init__.py
- sme_ptrf_apps/core/api/views/contas_associacoes_viewset.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/tests/tests_api_contas_associacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_contas_associacoes/test_create.py
- sme_ptrf_apps/core/tests/tests_api_contas_associacoes/test_delete.py
- sme_ptrf_apps/core/tests/tests_api_contas_associacoes/test_filtros.py
- sme_ptrf_apps/core/tests/tests_api_contas_associacoes/test_get.py
- sme_ptrf_apps/core/tests/tests_api_contas_associacoes/test_list.py
- sme_ptrf_apps/core/tests/tests_api_contas_associacoes/test_update.py
Esse PR:
Adiciona API para Contas de Associações
História AB#124990
> feat(124990): API parametrização de contas de associações

- sme_ptrf_apps/despesas/api/views/motivos_pagamento_antecipado_viewset.py
Esse PR:
Ajuste o perform_destroy para o response de exclusão de Motivos de pagamento antecipado
História AB#124988
> feat(124988): Ajuste de perform_destroy

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/serializers/tipo_devolucao_ao_tesouro_serializer.py
- sme_ptrf_apps/core/api/views/tipos_devolucao_ao_tesouro_viewset.py
- sme_ptrf_apps/core/fixtures/factories/__init__.py
- sme_ptrf_apps/core/fixtures/factories/tipo_devolucao_ao_tesouro_factory.py
- sme_ptrf_apps/core/tests/tests_tipo_devolucao_ao_tesouro/test_tipo_devolucao_ao_tesouro_serializer.py
- sme_ptrf_apps/core/tests/tests_tipo_devolucao_ao_tesouro/test_tipos_devolucao_ao_tesouro_viewset.py
Esse PR:
Adiciona recursos de API para consumo do Frontend na tela de Motivos(Tipos) de Devolução ao Tesouro
História AB#124987
> feat(124987): API tipos devolucao tesouro

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/serializers/tipo_devolucao_ao_tesouro_serializer.py
- sme_ptrf_apps/core/api/views/tipos_devolucao_ao_tesouro_viewset.py
- sme_ptrf_apps/core/fixtures/factories/__init__.py
- sme_ptrf_apps/core/fixtures/factories/tipo_devolucao_ao_tesouro_factory.py
- sme_ptrf_apps/core/tests/tests_tipo_devolucao_ao_tesouro/test_tipo_devolucao_ao_tesouro_serializer.py
- sme_ptrf_apps/core/tests/tests_tipo_devolucao_ao_tesouro/test_tipos_devolucao_ao_tesouro_viewset.py
Esse PR:
Ajuste o cliente jwt na execução dos testes unitários
História AB#124987
> feat(124987):  api tipos devolucao tesouro

- config/api_router.py
- sme_ptrf_apps/despesas/api/serializers/tipo_transacao_serializer.py
- sme_ptrf_apps/despesas/api/views/tipos_transacao_viewset.py
- sme_ptrf_apps/despesas/fixtures/factories/tipo_transacao_factory.py
- sme_ptrf_apps/despesas/tests/tests_api_tipos_transacao/conftest.py
- sme_ptrf_apps/despesas/tests/tests_api_tipos_transacao/test_tipo_transacao.py
Esse PR:
Adiciona API para Tipos de transações
História AB#124181
> feat(124181): API parametrização despesas tipos de transação

- config/api_router.py
- sme_ptrf_apps/despesas/api/serializers/tipo_transacao_serializer.py
- sme_ptrf_apps/despesas/api/views/tipos_transacao_viewset.py
- sme_ptrf_apps/despesas/fixtures/factories/tipo_transacao_factory.py
- sme_ptrf_apps/despesas/tests/tests_api_tipos_transacao/conftest.py
- sme_ptrf_apps/despesas/tests/tests_api_tipos_transacao/test_tipo_transacao.py
Esse PR:
Adiciona nova API para Tipos de transações
História AB#124181
> feat(124181) Nova API para tipos de transação

- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- Considera valor de despesas de períodos anteriores na Ata
AB#125101
> fix(125101): Considera valor de despesas de períodos anteriores na Ata

- sme_ptrf_apps/core/api/views/contas_associacoes_viewset.py
Esse PR:
Adiciona mais filtros na listagem de contas das associações via API
História AB#124990
> feat124990): Adição de mais filtros na listagem de contas de associações

- sme_ptrf_apps/core/api/views/contas_associacoes_viewset.py
Esse PR:
Adição de mais filtros no queryset de listagem de contas de associações
História AB#124990
> feat(124990): Adição de mais filtros na listagem de contas de associações

- sme_ptrf_apps/dre/api/serializers/motivo_aprovacao_ressalva_serializer.py
- sme_ptrf_apps/dre/api/views/motivo_aprovacao_ressalva_viewset.py
Esse PR:
Adição de filtro por motivo na query de motivos de aprovação com ressalva. Validação na criação e edição para evitar registros repetidos
História AB#124909
> feat(124909): API de motivos de aprovação com ressalva

- sme_ptrf_apps/dre/api/views/motivo_aprovacao_ressalva_viewset.py
Esse PR:
Adição de validação na exclusão do motivo que tenha relacionamento com alguma PC
História AB#124909
> feat(124909): Adição de validação na exclusão do motivo que tenha relacionamento com alguma PC

- sme_ptrf_apps/despesas/api/views/tipos_transacao_viewset.py
Esse PR:
Ajuste de mensagem de erro no viewset ao deletar tipo de transação
História AB#124181
> feat(124181):  Ajuste de mensagem de erro ao deletar tipo de transação

- sme_ptrf_apps/despesas/api/views/tipos_transacao_viewset.py
Esse PR:
Ajuste de mensagem de erro no viewset ao deletar tipo de transação
História AB#124181
> feat(124181): Ajuste de mensagem de erro ao deletar tipo de transação

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
-  Implementa regra para considerar despesas não demonstradas no retorno do resumo por ação em demonstrativo financeiro
AB#125101
> fix(125101): Corrige geração de dados resumo por ação no demonstrativo financeiro

- sme_ptrf_apps/dre/admin.py
-  Corrige ação admin vincular pcs ao consolidado
AB#125075
> fix(125075): Corrige ação admin vincular pcs ao consolidado

- sme_ptrf_apps/core/services/info_por_acao_services.py
Correção de retorno da api consulta saldos caso não tenha os parâmetros necessários AB#124967
> Fix(124967): botao salvar ediacao despesas

- sme_ptrf_apps/receitas/api/views/repasse.py
Esse PR:
- Altera a ordenação dos períodos na tela de parametrização de repasses.
História: AB#125424
> feat(125424): Ordenação de períodos em parametrização de repasses

- sme_ptrf_apps/core/services/carga_contas_associacoes_service.py
- sme_ptrf_apps/core/tests/tests_carga_contas_associacoes_service/test_carga_contas_associacoes_service.py
Esse PR:
Inclui o campo Número de Cartão e adiciona validações de campos obrigatórios e testes unitários
História AB#124991
> feat(124991): carga contas associacoes inclui validacoes

- sme_ptrf_apps/core/services/carga_contas_associacoes_service.py
- sme_ptrf_apps/core/tests/tests_carga_contas_associacoes_service/test_carga_contas_associacoes_service.py
Esse PR:
Inclui o campo Número de Cartão e adiciona validações de campos obrigatórios e testes unitários
História AB#124991
> feat(124991): carga contas associacoes inclui validacoes - homolog

- sme_ptrf_apps/receitas/tests/test_repasse/test_api.py
Esse PR:
- Adiciona teste.
História: AB#125424
> feat(125424): Adiciona teste de ordenação retorno períodos

- config/api_router.py
- sme_ptrf_apps/despesas/api/serializers/especificacao_material_servico_serializer.py
- sme_ptrf_apps/despesas/api/views/especificacoes_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_especificacoes/test_especificacoes_endpoint.py
Esse PR:
Adiciona o backend/API para utilização no frontend de parametrizações de Especificações de Materiais e Serviços
História AB#125420
> feat(125420): api especificacoes materiais servicos para o front de parametrizações

- sme_ptrf_apps/despesas/api/views/especificacoes_viewset.py
Esse PR:
Adiciona um ajuste quanto ao parâmetro de URL de filtro descrição
História AB#125420
> feat(125420): api especificacoes materiais servicos strip filtro

- sme_ptrf_apps/despesas/api/views/especificacoes_viewset.py
Esse PR:
Adiciona um ajuste quanto ao parâmetro de URL de filtro descrição
História AB#125420
> feat(125420): api especificacoes materiais servicos strip filtro - Homolog

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/parametros_ue_viewset.py
- sme_ptrf_apps/core/models/parametros.py
- sme_ptrf_apps/core/tests/tests_api_parametros_ue/test_get_texto_pagina_paa_ue.py
- sme_ptrf_apps/core/tests/tests_parametros/test_model.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_monitora_prestacao_de_contas_service.py
Esse PR:
Adiciona API para consumo de API no frontend para o Texto de Página PAA
História AB#125887
> feat(125887): Inclusão de API para Texto de Página PAA

- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acoes_associacoes_list.py
paginacao api acoes associacoes e correcao dos testes
> Feature(12607): paginacao api acoes associacoes e correcao dos testes

- sme_ptrf_apps/despesas/fixtures/factories/tipo_documento_factory.py
Esse PR:
Ajusta factory de Tipo Documento que ocasionava erro de constraint de unicidade de instância na execução dos testes na pipeline do Jenkins
História AB#126197
> test(126197): ajuste de factory

- sme_ptrf_apps/receitas/admin.py
- sme_ptrf_apps/receitas/api/serializers/tipo_receita_serializer.py
- sme_ptrf_apps/receitas/api/views/tipo_receita_viewset.py
- sme_ptrf_apps/receitas/models/tipo_receita.py
Esse PR:
- Action Buscar unidades vinculadas e não vinculadas paginada
- Action Executar ação de vincular e desvincular 
- Action  Executar ação de vincular e desvincular em lote 
- Validação de desvincular 
- Selecionar todas unidades
AB#125425
> feat(125425): Implementa rotas para tipo credito

- sme_ptrf_apps/receitas/api/serializers/tipo_receita_serializer.py
- sme_ptrf_apps/receitas/api/views/tipo_receita_viewset.py
- sme_ptrf_apps/receitas/models/tipo_receita.py
Esse PR:
- Corrige regra de todas selecionadas
AB#125425
> feat(125425): Modifica regra de todas selecionadas

- sme_ptrf_apps/receitas/api/serializers/tipo_receita_serializer.py
- sme_ptrf_apps/receitas/api/views/tipo_receita_viewset.py
Esse PR:
- Modifica query e serializer de listagem de tipos de crédito.
História: AB#125425
> feat(125425): Modifica query de listagem

- sme_ptrf_apps/receitas/api/views/tipo_receita_viewset.py
Esse PR:
- Modifica o filtro de unidades na parametrização de tipos de crédito.
História: AB#125425
> feat(125425): Modifica filtro associação

- sme_ptrf_apps/core/models/acao_pdde.py
Esse PR:
- Altera campo categoria de ação pdde para ser opcional no admin
História: AB#126197
> feat(126197): Campo categoria de ação pdde como opcional no admin

- config/api_router.py
- sme_ptrf_apps/core/api/views/__init__.py
- sme_ptrf_apps/core/api/views/paa_viewset.py
- sme_ptrf_apps/core/services/paa_service.py
- sme_ptrf_apps/core/tests/tests_paa/test_levantamento_prioridade.py
- sme_ptrf_apps/static/css/pdf-levantamento-prioridades-paa.css
- sme_ptrf_apps/templates/pdf/paa/partials/tabela-participantes.html
- sme_ptrf_apps/templates/pdf/paa/partials/tabela-prioridades.html
- sme_ptrf_apps/templates/pdf/paa/pdf_levantamento_prioridades_paa.html
Esse PR:
- Adiciona serviço para download do PDF de levantamento de prioridades do PAA;
- Adiciona PDF de levantamento de prioridades;
- Adiciona endpoint, viewset e testes;
História: AB#126630
> feat(126630): Adiciona serviço download pdf levantamento paa

- sme_ptrf_apps/static/css/pdf-levantamento-prioridades-paa.css
Esse PR:
- Adiciona estilo negrito.
História: AB#126630
> feat(126630): Adiciona estilo negrito pdf

- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acoes_associacoes_list.py
Esse PR:
Ajuste os testes unitários para os saldos de acoes associacoes
História AB#124771
> test(124771): ajustes de testes unitários quanto ao saldo de acoes associações

- Dockerfile
- requirements/base.txt
Esse PR:
- Atualização do Python no Dockerfile para a versão 3.12.9
- Atualização do Django no requirements/base.txt para a versão 4.2.20
História: AB#127057
> feat(127057): Atualização do Python e Django

- config/api_router.py
Esse PR:
- Adiciona novas rotas para fontes de recursos e recursos próprios paa
História: AB#126196
> feature(126196): Adição das rotas de fontes de recursos e recursos proprios paa

- sme_ptrf_apps/core/api/serializers/categoria_pdde_serializer.py
Esse PR:
- Remove trecho de código comentado
História: AB#126656
> feature(126656): Removendo trecho de código comentado

- sme_ptrf_apps/core/tests/tests_acoes_pdde/test_acoes_pdde_model.py
- sme_ptrf_apps/core/tests/tests_acoes_pdde/test_acoes_pdde_serializer.py
- sme_ptrf_apps/core/tests/tests_categoria_pdde/test_categoria_pdde_serializer.py
- sme_ptrf_apps/core/tests/tests_categoria_pdde/test_categoria_pdde_viewset.py
Esse PR:
- Adiciona testes unitários para o novo endpoint de categorias pdde
- Adiciona testes unitários para os novos serializers
- Adiciona testes unitários para os novos campos do model de ação pdde
História: AB#126656
> feat(126656): Adição de testes unitários 

- sme_ptrf_apps/core/tests/tests_acoes_pdde/test_acoes_pdde_model.py
- sme_ptrf_apps/core/tests/tests_acoes_pdde/test_acoes_pdde_serializer.py
- sme_ptrf_apps/core/tests/tests_categoria_pdde/test_categoria_pdde_serializer.py
- sme_ptrf_apps/core/tests/tests_categoria_pdde/test_categoria_pdde_viewset.py
Esse PR:
- Adiciona testes unitários para o novo endpoint de categorias pdde
- Adiciona testes unitários para os novos serializers
- Adiciona testes unitários para os novos campos do model de ação pdde
História: AB#126656
> feat(126656): Adição de testes unitários

- sme_ptrf_apps/core/api/views/fonte_recurso_paa_viewset.py
Esse PR:
- Adiciona autenticação nas rotas de fontes de recursos paa
História: AB#126196
> feat(126196): Adição de autenticação nas rotas de fontes de recursos paa

- sme_ptrf_apps/core/api/serializers/recurso_proprio_paa_serializer.py
- sme_ptrf_apps/core/api/views/recurso_proprio_paa_viewset.py
Esse PR:
- Adiciona filtros pro associação nos endpoints de recursos próprios paa
História: AB#126196
> feat(126196): Adição de filtro de recursos próprios paa por associação

- sme_ptrf_apps/core/migrations/0403_fonte_recurso_paa.py
Esse PR:
- Ajuste na grafia dos nomes das Fontes de Recursos Paa
História: AB#126196
> feat(126196): Ajuste nos nomes de Fontes de Recursos

- sme_ptrf_apps/paa/tests/periodos_paa/test_model.py
- sme_ptrf_apps/paa/tests/periodos_paa/test_patch.py
- sme_ptrf_apps/paa/tests/periodos_paa/test_post.py
- sme_ptrf_apps/paa/utils.py
Esse PR:
- Correção na mensagem de erro na validação de data final no cadastro de PeriodoPaa
História: AB#125050
> feat(125050): Correção em mensagem de erro na validação de datas

- requirements/base.txt
Esse PR:
- Atualização das libs: django-admin-interface, django-allauth, django-auditlog, django-compressor e rcssmin 
História: AB#127758
> feat(127758): Atualização de libs

- requirements/base.txt
- sme_ptrf_apps/core/admin.py
Esse PR:
- Atualização das libs: django-admin-interface, django-allauth, django-auditlog, django-compressor e rcssmin
-Ajuste na classe LogEntryAdmin para evitar erro de localtime/timezone ao exibir a listagem no admin devido à atualização da lib
História: AB#127758
> feat(127758): Atalizaçãode libs

- sme_ptrf_apps/core/api/serializers/categoria_pdde_serializer.py
- sme_ptrf_apps/core/api/views/categorias_pdde_viewset.py
- sme_ptrf_apps/core/tests/tests_categoria_pdde/test_categoria_pdde_serializer.py
- sme_ptrf_apps/core/tests/tests_categoria_pdde/test_categoria_pdde_viewset.py
Esse PR:
- Refatoração na lógica de deleção da Categoria PDDE pra não permitir que uma Ação PDDE fique sem categoria.
História: AB#127758
> feat(127758): Refatoração deleção Categoria PDDE

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_receitas_previstas_paa/test_receitas_previstas_paa_admin.py
- sme_ptrf_apps/paa/api/serializers/paa_serializer.py
- sme_ptrf_apps/paa/services/paa_service.py
Esse PR:
Ajusta mensagens de response e lógica de permitir elaborar novo PAA
História AB#127073
> feature(127073): Paa mensagens response

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_receitas_previstas_paa/test_receitas_previstas_paa_admin.py
- sme_ptrf_apps/paa/api/serializers/paa_serializer.py
- sme_ptrf_apps/paa/services/paa_service.py
Esse PR:
Ajusta mensagens de response e lógica de permitir elaborar novo PAA
História AB#127073
> feat(127073): Paa mensagens response

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/paa/api/serializers/paa_serializer.py
- sme_ptrf_apps/paa/fixtures/factories/__init__.py
- sme_ptrf_apps/paa/fixtures/factories/paa.py
- sme_ptrf_apps/paa/fixtures/factories/parametro_paa.py
- sme_ptrf_apps/paa/tests/conftest.py
- sme_ptrf_apps/paa/tests/paa/test_admin.py
- sme_ptrf_apps/paa/tests/paa/test_associacoes_paa_vigente.py
- sme_ptrf_apps/paa/tests/paa/test_delete.py
- sme_ptrf_apps/paa/tests/paa/test_get.py
- sme_ptrf_apps/paa/tests/paa/test_model.py
- sme_ptrf_apps/paa/tests/paa/test_post.py
- sme_ptrf_apps/paa/tests/parametro_paa/test_admin.py
- sme_ptrf_apps/paa/tests/parametro_paa/test_get.py
- sme_ptrf_apps/paa/tests/parametro_paa/test_model.py
Esse PR:
Adiciona testes unitários do PAA,  Parâmetros do PAA e PAA Vigente da Associação
História AB#127073
> test(127073): Testes unitários do PAA

- .pre-commit-config.yaml
- README.md
- requirements/local.txt
- setup.cfg
Esse PR:
- Atualiza versão da lib pre-commit
- Ajustes no yaml de configuração
- Ajustes no setup.cfg
- Adição de instruções no README
História: AB#127797
> feat(127797): Configuração e ajustes do pre-commit

- sme_ptrf_apps/templates/pdf/paa/pdf_levantamento_prioridades_paa.html
Esse PR:
- Adiciona seção de Pais, Responsáveis e Alunos no PDF de levantamento.
História: AB#127663
> feat(127663): Adiciona seção de pais no pdf de levantamento

- sme_ptrf_apps/users/api/serializers/usuario_serializer.py
Esse PR:
- Ajuste no serializer do usuário no campo de url
> bugfix: Correção no serializer de usuário na construção da url

- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_despesa_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/despesa_situacao_patrimonial_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/rateio_situacao_patrimonial_serializer.py
Esse PR:
- Adiciona os uuids de BemProduzidoRateio e BemProduzidoDespesa na consulta de BemProduzido.
História: AB#127456
> feat(127456): Adiciona uuids

- Makefile
- README.md
Esse PR:
- Inclui o arquivo Makefile para padronização de comandos mais comuns do projeto PTRF
- Atualiza o README do repositório para substituição dos comandos
História AB#127768
> tec(127768): Makefile

- sme_ptrf_apps/situacao_patrimonial/admin.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/rateio_situacao_patrimonial_serializer.py
Esse PR:
- Ajusta forma para criar/atualizar rateios do bem produzido com valores
> feat(127456): Ajustes update bem produzido e adc admin rateio

- sme_ptrf_apps/situacao_patrimonial/api/views/despesa_situacao_patrimonial_viewset.py
Esse PR:
- Adiciona distinct na viewset de despesas de situação patrimonial.
História: AB#127456
> feat(127456): Adiciona distinct query despesas

- requirements/base.txt
Esse PR:
- Atualiza as libs do backend:
- redis
- elastic-apm
- psutil
- Babel
- Pillow
> feature(128813): Atualização de libs

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
Esse PR:
- Corrige quebra linha.
História: AB#127765
> fix(127765): Correção de quebra linha

- sme_ptrf_apps/situacao_patrimonial/admin.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_serializer.py
Esse PR:
- Adiciona o admin de bem produzido item;
- Modifica objeto de criação do bem produzido item no inicio do cadastro de bem produzido.
História: AB127457
> feat(127457): Adiciona bem produzido item no admin

- sme_ptrf_apps/despesas/api/serializers/especificacao_material_servico_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/views/bem_produzido_viewset.py
Esse PR:
- Ajusta serializers para retorno de informações no frontend.
História: AB#127457
> feat(127457): Ajustes serializer de item de bem patrimonial

- config/api_router.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_item_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/views/__init__.py
- sme_ptrf_apps/situacao_patrimonial/api/views/bem_produzido_viewset.py
- sme_ptrf_apps/situacao_patrimonial/tests/bem_produzido/test_admin.py
Esse PR:
- Cria a viewset e serializer de Bem Produzido rascunho, e Bem Produzido Item rascunho para separa a lógica de rascunho;
- Corrige testes;
História: AB#127457
> feat(127457): Adiciona viewset de rascunho

- tests/api/cypress/e2e/PTRF/api/validar_acoes_associacoes.cy.js
- tests/api/cypress/e2e/PTRF/api/validar_receitas_previstas_paa.cy.js
Fix - Ajustes nos endpoint de receitas_previstas_paa
> Fix - Ajustes nos endpoint de receitas_previstas_paa

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/paa/fixtures/factories/prioridade_paa_factory.py
- sme_ptrf_apps/paa/tests/fontes_recursos_paa/test_fontes_recursos_paa_viewset.py
- sme_ptrf_apps/paa/tests/prioridades_paa/conftest.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_admin.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_model.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_serializer.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_viewset.py
Esse PR:
Inclui testes unitários sobre a feature de Prioridades do PAA
História AB#127465
> test(127465): testes unitários para prioridades do PAA

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/models/acao_associacao.py
- sme_ptrf_apps/core/models/membro_associacao.py
- sme_ptrf_apps/core/models/motivo_rejeicao_encerramento_conta_associacao.py
- sme_ptrf_apps/core/models/proccessos_associacao.py
- sme_ptrf_apps/core/models/solicitacao_encerramento_conta_associacao.py
Este PR:
- Corrige a sequência dos models do core a partir do 07.*
> feature(129206): Ajustes em labels de models do core no admin

- sme_ptrf_apps/core/api/views/periodos_viewset.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_list_periodos.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_e_adquirido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/views/bem_produzido_e_adquirido_viewset.py
- sme_ptrf_apps/situacao_patrimonial/tests/serializers/test_bem_produzido_e_adquirido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/tests/viewsets/test_bem_produzido_e_adquirido_viewset.py
Esse PR:
- Adiciona novos campos no retorno de bens
- Ajusta filtro por período no get de bens para receber uma lista de períodos
- Atualiza testes
- Adiciona filtro somente_com_pcs_entregues no get de períodos
- Adiciona teste no get de períodos
[AB#127458](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127458)
> feat(127458): Implementa ajustes no retorno dos bens e adiciona filtro no get de periodos

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-execucao-fisico-financeira.html
[AB#129207](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129207)
> feat(129207): Remove lógica de mostrar Conta inativa quando conta não houver movimentação

- sme_ptrf_apps/sme/services/exporta_rateios_service.py
Este PR:
- Altera o campa do valor status do relatório, agora usando o model de Despesa ao invés de RateioDespesa
História [AB#129878](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_workitems/edit/129878)
> feature(129878): Atualização da extração de dados Despesas: Classificação das despesas

- sme_ptrf_apps/core/api/views/periodos_viewset.py
- sme_ptrf_apps/situacao_patrimonial/admin.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/__init__.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/views/bem_produzido_viewset.py
- sme_ptrf_apps/situacao_patrimonial/models/bem_produzido.py
- sme_ptrf_apps/situacao_patrimonial/models/bem_produzido_despesa.py
- sme_ptrf_apps/situacao_patrimonial/models/bem_produzido_rateio.py
- Implementa serializer de save e rascunho com criação/edição unificado de despesa, rateios, itens, recursos próprios e validações.
[AB#129378](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129378)
> feat(129378): Unifica serializer criação/edição de bens produzidos

- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_admin.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_model.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_viewset.py
Esse PR:
inclui testes adicionais sobre a implementação da história
História [AB#127464](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127464)
> test(127464): Testes unitários

- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_e_adquirido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_item_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/rateio_situacao_patrimonial_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/views/despesa_situacao_patrimonial_viewset.py
- sme_ptrf_apps/situacao_patrimonial/tests/viewsets/test_bem_produzido_viewset.py
Esse PR:
- Realize ajustes nos serializer e na viewset de situação patrimonial para a edição de bem produzido.
História: [AB#129378](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129378)
> feat(129378): Ajustes serializers e viewset

- sme_ptrf_apps/situacao_patrimonial/api/views/despesa_situacao_patrimonial_viewset.py
Esse PR:
- Remove filtro que removia da listagem a despesa quando a ela tinha todo o valor utilizado, impossibilitando assim, editar a mesma despesa. Em conjunto no front-end foi adicionada a regra de deixar não selecionável as despesas sem valor na criação do bem patrimonial.
História: [AB#129378](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129378)
> feat(129378): remove filtro de valor na listagem despesa

- sme_ptrf_apps/paa/tests/prioridades_paa/conftest.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_serializer.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_viewset.py
História [AB#127466](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127466)
Task [AB#130910](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/130910)
> test(127466): implementação de ajustes de testes unitários sobre a feature de edição de prioridades

- sme_ptrf_apps/paa/api/views/acoes_pdde_viewset.py
- sme_ptrf_apps/paa/tests/acoes_pdde/test_acoes_pdde_viewset.py
[AB#131686](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20015%20-%20COPLAN%20-%20PTRF?workitem=131686)
- Adiciona cenários de testes para exclusão de ações PDDE
> test(131686): Adiciona cenários de testes para exclusão de Ações PDDE

- sme_ptrf_apps/paa/tests/acoes_pdde/test_acoes_pdde_model.py
[AB#131686](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/131686)
- Remove teste com regra obsoleta
> refactor(tests): Remove testes obsoletos por mudança de regra

- sme_ptrf_apps/paa/api/views/periodo_paa_viewset.py
- sme_ptrf_apps/paa/models/periodo_paa.py
[AB#129376](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20015%20-%20COPLAN%20-%20PTRF?workitem=129376)
- Adicionada a validação para exclusão de Período PAA. Excluir somente períodos não vinculados a nenhuma PAA
> feat(129376): Remoção de período PAA

- sme_ptrf_apps/paa/api/views/periodo_paa_viewset.py
[AB#129376](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20015%20-%20COPLAN%20-%20PTRF?workitem=129376)
- Adicionado o tratamento de erro para período não encontrado (404), com mensagem personalizada.
> feat(129376): Adiciona tratamento de exceção para período não encontrado

- sme_ptrf_apps/paa/api/views/acoes_pdde_viewset.py
[AB#129377](https://dev.azure.com/SME-Spassu/COPLAN%20-%20PTRF/_sprints/taskboard/COPLAN%20-%20PTRF%20Team/COPLAN%20-%20PTRF/Sprint%20015%20-%20COPLAN%20-%20PTRF?workitem=129377)
- Adiciona filtro de status na listagem de ações PDDE durante a elaboração de PAA.
> feat(129377): Adiciona filtro de status na listagem de ações PDDE em elaboração de PAA

- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_viewset.py
Esse PR:
Inclui teste unitário para a view de duplicação de Prioridade
História [AB#127468](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127468)
> test(127468): Testes unitários para a feature de duplicação de Prioridades

- sme_ptrf_apps/sme/services/exporta_dados_saldos_bancarios_service.py
- sme_ptrf_apps/sme/tests/tests_api_exportacoes_dados_saldos_bancarios/test_exportacoes_dados_saldos_bancarios.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacao_dados_saldos_bancarios/conftest.py
- sme_ptrf_apps/sme/tests/tests_services/tests_exportacao_dados_saldos_bancarios/test_exportacao_dados_saldos_bancarios.py
[AB#129205](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129205)
> feat(129205): Implementa testes para exportação de dados de saldos bancários

- sme_ptrf_apps/sme/services/exporta_dados_saldos_bancarios_service.py
[AB#129205](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/129205)
> feat(129205): Adiciona informações filtro na geração do relatório

- tests/api/cypress.config.js
- tests/api/cypress/support/e2e.js
> Fix/132472 Ajustes cenários quebrados

- tests/api/cypress.config.js
Esse PR:
- Atualiza endereço cypress.
História: [AB#132531](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/132531)
> tec(132531): Atualiza endereco cypress

- requirements/local.txt
[AB#131491](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/131491)
> feat(131491): Atualiza libs qualidade de código

- sme_ptrf_apps/paa/api/serializers/programa_pdde_serializer.py
- sme_ptrf_apps/paa/api/views/paa_viewset.py
- sme_ptrf_apps/paa/services/__init__.py
- sme_ptrf_apps/paa/services/paa_service.py
- sme_ptrf_apps/paa/services/resumo_prioridades_service.py
História [AB#127462](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127462)
> feature(127462): API resumo de recursos de Prioridades do PAA

- sme_ptrf_apps/paa/api/serializers/programa_pdde_serializer.py
- sme_ptrf_apps/paa/api/views/paa_viewset.py
- sme_ptrf_apps/paa/services/__init__.py
- sme_ptrf_apps/paa/services/paa_service.py
- sme_ptrf_apps/paa/services/resumo_prioridades_service.py
- sme_ptrf_apps/paa/tests/conftest.py
- sme_ptrf_apps/paa/tests/services/test_resumo_prioridades.py
História [AB#127462](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127462)
> test/127462: Testes unitários Resumo de Prioridades

- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_e_adquirido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/serializers/despesa_situacao_patrimonial_serializer.py
- sme_ptrf_apps/situacao_patrimonial/api/views/bem_produzido_viewset.py
- sme_ptrf_apps/situacao_patrimonial/api/views/despesa_situacao_patrimonial_viewset.py
Esse PR:
- Adiciona recursos próprios;
- Ordena tabela;
- Adiciona validações e correções.
História: [AB#131978](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/131978)
> feat(131978): Melhorias situação patrimonial

- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/core/api/views/acoes_viewset.py
- sme_ptrf_apps/core/api/views/arquivo_viewset.py
- sme_ptrf_apps/core/api/views/contas_associacoes_viewset.py
- sme_ptrf_apps/core/api/views/membro_associacao_viewset.py
- sme_ptrf_apps/dre/api/views/motivo_aprovacao_ressalva_viewset.py
Esse PR:
Adiciona documentação de parâmetros de API sobre a história de débito técnico
História [AB#132650](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/132650)
> tec(132650): Inclusão de Parâmetros de API

- sme_ptrf_apps/situacao_patrimonial/api/serializers/bem_produzido_e_adquirido_serializer.py
Esse PR:
- Adiciona melhorias na listagem de bens produzidos.
História: [AB#131978](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/131978)
> feat(131978): Adiciona melhorias na listagem

- sme_ptrf_apps/paa/services/resumo_prioridades_service.py
Esse PR:
Ajusta na tabela de Resumo de recursos a troca de consolidados de Programas PDDE por Ações PDDE
História [AB#127462](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/127462)
> feature(127462): ajuste de acoes pdde em resumo de recursos

- sme_ptrf_apps/core/api/views/arquivos_download_viewset.py
- sme_ptrf_apps/core/api/views/modelos_cargas_viewset.py
- sme_ptrf_apps/core/api/views/parametrizacoes_acoes_associacoes.py
- sme_ptrf_apps/core/api/views/tags_viewset.py
- sme_ptrf_apps/despesas/api/views/tipos_custeio_viewset.py
- sme_ptrf_apps/despesas/api/views/tipos_transacao_viewset.py
- sme_ptrf_apps/sme/api/views/saldos_bancarios_sme_detalhes_associacoes_viewset.py
- sme_ptrf_apps/sme/api/views/saldos_bancarios_sme_viewset.py
Esse PR:
Adiciona parâmetros de API nas viewset para documentação no Swagger
História [AB#133518](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/133518)
> tec(133518): Documentação de Parâmetros de API

- sme_ptrf_apps/paa/admin.py
- sme_ptrf_apps/paa/api/views/paa_viewset.py
- sme_ptrf_apps/paa/services/paa_service.py
- sme_ptrf_apps/paa/tests/paa/test_levantamento_prioridade.py
- sme_ptrf_apps/paa/tests/paa/test_paa_viewset.py
- sme_ptrf_apps/paa/tests/prioridades_paa/test_prioridade_paa_admin.py
- sme_ptrf_apps/paa/tests/receitas_previstas_paa/test_receitas_previstas_paa_admin.py
Esse PR:
- Adiciona Importação de Prioridades de PAA anterior
- Testes unitários relacionados
História [AB#132467](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/132467)
> feature(132467): Importação de Prioridades sobre PAAs Anteriores

- sme_ptrf_apps/situacao_patrimonial/api/views/bem_produzido_e_adquirido_viewset.py
Esse PR:
- Remove da visão DRE os bens produzidos incompletos.
História: [AB#133158](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/133158)
> feat(133158): Ajustes situação patrimonial

- sme_ptrf_apps/paa/services/resumo_prioridades_service.py
Esse PR:
Considera as Prioridades PAA com o campo `prioridade` com valores "Sim" e "Não" para contabilizar na tabela de resumo de Prioridades
História [AB#132467](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/132467)
> feature(132467): Considera prioridades "Sim" e "Não" na tabela

- sme_ptrf_apps/core/api/views/analise_conta_prestacao_conta_viewset.py
- sme_ptrf_apps/core/api/views/analise_lancamento_prestacao_conta_viewset.py
- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/api/views/presentes_ata_viewset.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/api/views/tipos_acerto_documento_viewset.py
- sme_ptrf_apps/core/api/views/tipos_acerto_lancamento_viewset.py
Esse PR:
Adiciona Documentação de Parâmetros de URL nas API`s nas actions das viewsets:
- TiposAcertoLancamentoViewSet
- TiposAcertoDocumentoViewSet
- AnalisesPrestacoesContasViewSet
- PresentesAtaViewSet
- AnaliseContaPrestacaoContaViewSet
- AnaliseLancamentoPrestacaoContaViewSet
> tec(134519): Inclusão de documentação de parâmetros de API

- sme_ptrf_apps/core/services/prestacao_conta_service.py
[AB#134189](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/134189)
> feat(134189): Validar alteração de saldo sem solicitação em concluir-v2

- sme_ptrf_apps/core/services/prestacao_conta_service.py
- sme_ptrf_apps/core/services/resumo_rescursos_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_prestacao_de_contas_service.py
[AB#134189](https://dev.azure.com/SME-Spassu/9517625e-d03b-4045-bc4f-69692f861ed6/_workitems/edit/134189)
> feat(134189): Comentar: Concluir acerto: Validar se houve alteração no saldo bancário e não permitir a conclusão dos acertos 
