- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_put_despesas.py
- sme_ptrf_apps/utils/update_instance_from_dict.py
Esse PR:
- Implementa a atualização de despesas
- implementa exclusão de despesas
> feature/13087-update-despesa 

- sme_ptrf_apps/receitas/api/serializers/__init__.py
- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- sme_ptrf_apps/receitas/api/views/receita_viewset.py
- sme_ptrf_apps/receitas/tests/test_receita/test_api.py
> Listagem de receitas

- sme_ptrf_apps/receitas/api/views/receita_viewset.py
- sme_ptrf_apps/receitas/tests/test_receita/test_api.py
- Alteração de receita
- Deleção de receita
- Busca por receita
> Altera receita, Deleta Receita, Busca uma receita

- config/settings/base.py
- requirements/base.txt
Esse PR:
- Instala django-cors-headers no projeto.
> build(config): Instala django-cors-headers

- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas.py
Corrige testes que estavam quebrando poir alteração no result da lista
de rateios de despesas.
> fix(tests): Corrige unit tests

- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/despesas/tests/tests_despesas/test_despesa_calculo_status.py
Esse PR:
- Corrige o calculo do status de despesas (completo ou incompleto) que não estava funcionando corretamente.
> fix(despesas): Corrige calculo do status de despesas

- sme_ptrf_apps/users/api/views/login.py
- Retorno dos dados da associação no login.
> features/12879 Retorna associacao no login

- config/settings/base.py
Esse PR:
- Altera o STATIC_URL para "/django_static/"
> build(config): Alterar stati_url para django_statics

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- Listagem atualizada normalmente
> Resolvendo Listagem de despesas

- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- Adiçao de descriçao no retorno de receita
> Adiçao de descriçao no retorno de receita

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/conftest.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_por_especificacao.py
Esse PR:
- Implementa na API de despesas a busca por qualquer termo na descrição da especificação de material ou serviço.
> Feature/13078 filtro rateios despesas por especificação

- config/settings/base.py
- sme_ptrf_apps/despesas/admin.py
- Filtros nos rateios despesas no admin
> Filtros em rateios despesas no Admin

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_com_filtros.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_search_por_especificacao.py
Esse PR:
- Implementa o filtro por associação em rateios de despesa.
> Feature/13076 add associação aos filtros rateio despesa

- requirements/base.txt
> Correçao requirements

- sme_ptrf_apps/receitas/admin.py
- Filtros em receitas no Admin
> Filtro em receitas no admin.

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_com_filtros.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_search_por_especificacao.py
Esse PR:
- Implementa o filtro pelo uuid da acção da associação na consulta de rateios de despesas.
> Feature/13076 filtro rateios depesas por acao associacao UUID

- config/settings/base.py
- requirements/base.txt
- sme_ptrf_apps/receitas/models/receita.py
- Histórico de alterações de receitas lançadas.
> Adiciona consulta histórico de alterações das receitas

- sme_ptrf_apps/despesas/models/despesa.py
- Histórico de alterações das despesas lançadas.
> Adiciona histórico de alterações das despesas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/receitas/api/views/receita_viewset.py
- sme_ptrf_apps/receitas/tests/conftest.py
- sme_ptrf_apps/receitas/tests/test_receita/test_get_receitas_com_filtros.py
- sme_ptrf_apps/receitas/tests/test_receita/test_get_receitas_search_por_descricao.py
Esse PR implementa na API de Receitas filtros por:
- Tipo de Receita
- Ação da Associação
- Conta da Associação
> Feature/13233 filtros avançados receitas

- config/settings/base.py
- sme_ptrf_apps/jwt_middleware.py
- Correção do funcionamento do auditlog com jwt.
Quando o usuário era logado usando front via jwt o auditlog não conseguia identificar o usuário logado.
> Correção do funcionamento do auditlog com o jwt.

- sme_ptrf_apps/core/api/serializers/__init__.py
- sme_ptrf_apps/core/api/serializers/associacao_serializer.py
- sme_ptrf_apps/core/api/serializers/unidade_serializer.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_update_associacao.py
- sme_ptrf_apps/core/tests/tests_associacao/test_associacao_serializer.py
- sme_ptrf_apps/core/tests/tests_unidade/tests_unidade_serializer.py
Esse PR:
- Altera o serializer de unidades para exibir corretamente os dados da DRE.
> feat(13115): Altera serializer de unidades

- sme_ptrf_apps/despesas/admin.py
- sme_ptrf_apps/receitas/admin.py
- Adição de filtro DRE nos admins de receitas e despesas.
> Adiçao filtro DRE nos admins de receitas e despesas.

- sme_ptrf_apps/receitas/services/carga_repasses.py
- sme_ptrf_apps/static/cargas/2020_01_01_a_2020_06_30_cartao.csv
- sme_ptrf_apps/static/cargas/2020_01_01_a_2020_06_30_cheque.csv
- Correção na criação do repasse na carga inicial.
> Correção criação repasse na carga inicial.

- sme_ptrf_apps/receitas/api/serializers/tipo_receita_serializer.py
- sme_ptrf_apps/receitas/tests/test_receita/test_api.py
- sme_ptrf_apps/receitas/tests/test_tipo_receita/test_model.py
- Adição do atributo e_repasse na tabela tipo_receita.
> Atualizaçao dos dados de tipo-receita nas tabelas de receita.

- sme_ptrf_apps/receitas/api/views/repasse.py
- sme_ptrf_apps/users/api/views/login.py
- No momento do login não criar usuário no PTRF.
> Não criar usuario na hora do login.

- sme_ptrf_apps/users/services/carga_usuarios.py
- Correção na carga de usuários.
> Correção na carga de usuários.

- sme_ptrf_apps/receitas/services/repasse_service.py
- sme_ptrf_apps/receitas/tests/test_receita/test_api.py
- Validação da data da receita na atualização do repasse.
> Validação da data da receita na atualização do repasse.

- sme_ptrf_apps/receitas/api/views/repasse.py
- sme_ptrf_apps/receitas/services/carga_repasses.py
- Altera endpoint de repasses/pendentes para ediçao de receitas.
> Altera endpoint de repasses/pendentes para ediçao de receitas.

- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- sme_ptrf_apps/receitas/services/repasse_service.py
- Update Receita do tipo repasse.
> Update Receita do tipo repasse.

- sme_ptrf_apps/despesas/admin.py
- Adição do tipo despesa nos rateios no admin.
> Adição tipo despesa

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/fechamento_periodo.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/conftest.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_get_despesas_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_get_receitas_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_services/conftest.py
- sme_ptrf_apps/core/tests/tests_services/test_concluir_prestacao_de_contas_service.py
- sme_ptrf_apps/core/tests/tests_services/test_iniciar_prestacao_de_contas_service.py
- sme_ptrf_apps/core/tests/tests_services/test_salvar_prestacao_de_contas_service.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/despesas/tests/tests_rateio_despesa/conftest.py
- sme_ptrf_apps/despesas/tests/tests_rateio_despesa/test_totais_despesas_da_acao_associacao_no_periodo_metodo.py
- sme_ptrf_apps/receitas/models/receita.py
- sme_ptrf_apps/receitas/tests/test_receita/conftest.py
- sme_ptrf_apps/receitas/tests/test_receita/test_totais_receitas_da_acao_associacao_no_periodo_metodo.py
Esse PR:
- Implementa a conclusão de uma prestação de contas com criação dos fechamentos por ação;
- Faz ajustes no retorno de receitas da prestação de contas;
- Faz ajustes no retorno de despesas da prestação de contas;
- Algumas refatorações de código.
> Feature/15110 Conciliação Fechamentos

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_totais.py
Esse PR:
- Implementa endpoint que retorna totais de despesas para determinado filtro.
> feat(14552): Endpoint de consulta de totais de despesas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/periodo_associacao_services.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Implementa o endpoint que permite verificar o status do período referente a uma data
> feat(15450): Endpoint para verificar status do período de uma data

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_painel_acoes.py
Esse PR:
Alterar o retorno do painel de ações adicionando a informação de outras receitas.
> feat(14998): Add outras receitas a consulta do painel de ações

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/models_abstracts.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_painel_acoes.py
Esse PR:
- Implementa a busca de informações do painel de ações de dado período.
> feat(13544): Consulta painel de ações por período

- sme_ptrf_apps/core/services/demonstrativo_financeiro.py
- Ajuste no serviço que gera a planilha
> Ajuste na geração prévia do demonstrativo financeiro.

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_tabela_valores_pendentes.py
- Endpoint que retorna os dados dos valores pendentes.
> Features/16489 exibir tabela de valores pendentes na conciliação

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/periodos_viewset.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_list_periodos.py
- Endpoint que retorna os períodos até a data atual.
> Endpoint que nao retorna periodos futuros.

- config/settings/base.py
- sme_ptrf_apps/core/models/demonstrativo_financeiro.py
- sme_ptrf_apps/core/models/relacao_bens.py
- sme_ptrf_apps/core/services/relacao_bens.py
- O nome da associação aparece na mensagem do bloco 3 do arquivo de relação de bens.
- Correção do timezone da aplicação.
> Correção no bloco 3 do arquivo de relação de bens e no timezone

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_ja_lancada.py
Esse PR:
- Cria endpoint para verificar se despesa já foi lançada.
> feat(16187): Verificar se despesa já existe

- sme_ptrf_apps/receitas/api/views/receita_viewset.py
- sme_ptrf_apps/receitas/tests/conftest.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_get_receitas_com_filtros.py
Esse PR:
- Implementa na API de receitas o filtro por range de data
> feat(14898): Add filtro por range de data para receitas

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_ja_lancada.py
Esse PR:
Altera a verificação de despesas repetidas para considerar  as despesas da associação.
> feat(16187): Corrige verificação de despesa repetida

- sme_ptrf_apps/core/services/demonstrativo_financeiro.py
- Correção do campo observações na montagem do demonstrativo financeiro.
> Observaçoes no demonstrativo financeiro.

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/users/api/views/login.py
- Inclusão do tipo escola ao nome da escola abaixo do nome do usuário.
> Incluir tipo escola ao nome da escola abaixo do nome do usuário.

- sme_ptrf_apps/core/services/demonstrativo_financeiro.py
- Correção na observação no demonstrativo financeiro.
> Correção demonstrativo financeiro.

- sme_ptrf_apps/receitas/api/views/repasse.py
- Correção na edição de receitas do tipo repasse.
> Correção Edição de receitas repasse.

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/receitas/api/views/receita_viewset.py
- sme_ptrf_apps/receitas/tests/conftest.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_get_receitas_search_por_descricao.py
Esse PR:
- Altera o filtro de créditos por detalhamento para desconsiderar caracteres acentuados.
> feat(17958): Desconsidera acentos filtro créditos

- config/settings/local.py
- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_get_info_para_ata_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_get_receitas_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_services/conftest.py
- sme_ptrf_apps/core/tests/tests_services/test_concluir_prestacao_de_contas_service.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
- Corrige o bug que fazia com que a ata exibisse lançamentos de outras contas
> fix(19001) Bug ata exibindo lançamentos de outras contas

- sme_ptrf_apps/users/tasks.py
> Adicionando logs

- sme_ptrf_apps/users/tasks.py
> Link do email para redefinir senha.

- sme_ptrf_apps/templates/email/email_redefinicao_senha.html
- sme_ptrf_apps/users/tasks.py
- Alteração no template de email.
> Alteração no template de email.

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_verifica_saldo_antes_post.py
Esse PR:
- Altera as rotinas de verificação de saldos para considerar os recursos  de livre aplicação.
> feat(19334): Ajusta verificação saldos considerar livre aplicação

- config/api_router.py
- sme_ptrf_apps/users/api/serializers/__init__.py
- sme_ptrf_apps/users/api/serializers/senha_serializer.py
- sme_ptrf_apps/users/api/serializers/user.py
- sme_ptrf_apps/users/api/validations/usuario_validations.py
- sme_ptrf_apps/users/api/views/senha_viewset.py
- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/services/__init__.py
- sme_ptrf_apps/users/services/sme_integracao_service.py
- sme_ptrf_apps/users/tests/test_serialize.py
* Alteração de email do usuário
* Alteração de senha do usuário
> Features/19311 alteração de email e senha

- requirements/base.txt
- Adição do ckeditor como dependência.
> add ckeditor requirement

- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- No demonstrativo financeiro só exibir ações que tenham lançamentos ou saldo
> Features/18889 Exibe ações no demonstrativo financeiro que tenham saldo ou que tenham lançamentos

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_info_por_acao_services/test_info_acao_associacao_no_periodo_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_info_por_acao_services/test_info_acoes_associacao_no_periodo_service.py
- sme_ptrf_apps/receitas/admin.py
- sme_ptrf_apps/receitas/models.py
Esse PR:
- Corrige o  serviço que retornava informações por ação não estava considerando corretamente as entradas de livre aplicação.
> feat(19335): Corrige serviço info por ação quanto a livre aplicação

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/tag.py
*  Correção para tabelas de despesas.
> Correção get_valores tag

- sme_ptrf_apps/receitas/admin.py
- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
Esse PR:
- Apenas adiciona alguns logs na carga de repasses.
> feat(19341): Add info logs na carga de repasses

- sme_ptrf_apps/core/services/prestacao_contas_services.py
* Adição receita-devolucao-no-periodo nos totais info para ata.
> Features/adição receita devolução no periodo nos totais info para ata

- sme_ptrf_apps/core/services/demonstrativo_financeiro.py
* Alteração no serviço do demonstrativo financeiro para adicionar a linha de livre aplicação.
> Features/19338 adicionar linha livre aplicação na planilha demonstrativo financeiro

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_get_info_para_ata_prestacao_conta.py
Esse PR contém.
* Correções por testes.
> Correções nos testes.

- sme_ptrf_apps/core/services/demonstrativo_financeiro.py
* Correção na formatação dos valores numéricos no demonstrativo financeiro.
> Correçao na formataçao dos numeros no demonstrativo financeiro.

- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_retrieve_associacao.py
Esse PR:
- Adiciona cargo_educacao ao retrieve de associações nos dados do presidente da diretoria e
presidente do conselho fiscal .
> feat(20335): Adiciona cargo_educacao ao retrieve de associações

- sme_ptrf_apps/core/services/enviar_email.py
- sme_ptrf_apps/users/api/serializers/senha_serializer.py
* envio de email de forma síncrona.
> features/ Enviando email de forma síncrona

- sme_ptrf_apps/core/services/demonstrativo_financeiro.py
* Correção saldo bancário demonstrativo financeiro.
> Features/correção saldo bancário demonstrativo financeiro

- sme_ptrf_apps/users/api/views/login.py
* API do Login retorna unidades e visões dos usuários logados.
> Features/19963 visões usuário logado

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_associacoes_verificacao_regularidade_update.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/regularidade_associacao_service.py
Esse PR:
- Implementa endpoint para atualizar itens de verificação em lote;
- Endpoint para marcar/desmarcar lista de verificação
> Feature/20362 regularidade unidade marca desmarca.todos

- sme_ptrf_apps/users/admin.py
*  No admin de usuários e possível selecionar a visão do mesmo.
> Features/selecionar visão no admin de usuários.

- sme_ptrf_apps/dre/tests/conftest.py
* Correção do fixture de atribuição
> Correçao do fixture de atribuiçao

- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/api/views/relacao_bens_viewset.py
Métodos estavam ainda considerando a conta para filtrar a prestação de contas.
> feat(22743): Altera get info relação de bens de demonstrativo financeiro

- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/api/views/relacao_bens_viewset.py
Esse PR:
Alterara os endpoints documento-final para demonstrativo financeiro e relação de bens de modo a não gerarem mais os documentos, apenas fazerem o download.
> feat(22743): Endpoint documento-final faz apenas o download

- sme_ptrf_apps/dre/api/views/tecnicos_dre_viewset.py
- sme_ptrf_apps/dre/tests/tests_api_tecnicos_dre/test_tecnico_dre_delete.py
Esse PR:
- Implementa a  transferência das atribuições de um técnico para outro no ato de sua exclusão.
> feat(20479): Transferência de atribuições na exclusão de tecnico

- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_com_filtros.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
- Ajusta modelo de despesa para limpar o campo periodo_conciliacao quando houver alteração.
- Ajusta modelo de creditos para limpar o campo periodo_conciliacao quando houver alteração.
> feat(22738): Ao editar despesa/receita limpa periodo de conciliacao

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_get_info_para_ata_prestacao_conta.py
Esse PR:
- Altera o result de informações para atas para incluir informações bancárias.
> Feature/22699 atas retornar dados bancários info acoes

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_get_info_para_ata_prestacao_conta.py
Não estavam sendo enviadas todas as contas da Associação.
> feat(22699): Resolve problema nas contas enviadas em info para atas

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_desfaz_conclusao_analise_prestacao_conta.py
Esse PR:
- Implementa a ação que desfaz a conclusão de análise de PC.
> feat(23678): Ação desfazer conclusão análise PC

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/periodo_associacao_services.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_conclui_prestacao_conta.py
Esse PR:
- Altera o calculo de status do período quando uma PC é devolvida;
- Alterar a conclusão de uma prestação de contas quando o status é devolvida.
> Feature(23678) Status e conclusão de prestações de conta devolvidas

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_com_filtros.py
Esse PR:
- Implementa na API de despesas a busca de despesas por id do tipo de documento.
> feat(23815): Consulta de despesa por id de tipo documento

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_salva_devolucoes_ao_tesouro.py
Esse PR:
- Cria endpoint para criar/atualizar devoluções ao tesouro de uma prestação.
> feat(23669): Atualização de devoluções ao tesouro

- config/api_router.py
- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/serializers/tipo_conta_serializer.py
- sme_ptrf_apps/core/api/views/__init__.py
- sme_ptrf_apps/core/api/views/tipo_conta_viewset.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_tipos_conta/test_tipos_conta_list.py
- sme_ptrf_apps/core/tests/tests_tipo_conta/test_tipo_conta_model.py
- sme_ptrf_apps/core/tests/tests_tipo_conta/test_tipo_conta_serializer.py
- sme_ptrf_apps/core/tests/tests_tipo_conta/test_tipo_conta_viewset.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_api.py
- Finalizando Ajustes em Feature 25487 - [DRE]  Relatório consolidado DRE - Página inicial
> Alteração em Rotas, Admin, ViewSet, Tests e Criação do Serializaer e Testes necessários

- sme_ptrf_apps/core/api/views/tipo_conta_viewset.py
- Finalizando Feature 25487-ajuste
> Removendo permissão PermissaoDashboardDre de sme_ptrf_apps/core/api/views/tipo_conta_viewset.py

- sme_ptrf_apps/core/services/demonstrativo_financeiro.py
* Ajuste no serviço que gera o demonstrativo financeiro.
> Features/26959 correçao demonstrativo gerado com mesmo nome

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard.py
Esse PR:
- Adiciona a informação de quantidade de aprovadas com ressalvas no retornado pelo dashboard.
> feat(25499):Aprovadas com ressalvas no dashboard

- README.md
- sme_ptrf_apps/__init__.py
> docs(1.2.0): Atualiza versão para 1.2.0

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_get_rateios_despesas_totais.py
Testa a aplicação de filtro por fornecedor na consulta de totais de rateio.
> feat(26292): Filtro por fornecedor em consulta de totais de rateio

- sme_ptrf_apps/core/services/carga_associacoes.py
- sme_ptrf_apps/core/services/periodo_inicial.py
- sme_ptrf_apps/receitas/services/carga_repasses_previstos.py
- sme_ptrf_apps/receitas/services/carga_repasses_realizados.py
- sme_ptrf_apps/users/services/carga_usuarios.py
* Correção na leitura dos arquivos .csvs para identificação dos delimitadores nas cargas via admin.
> Hotfix nas cargas via admin.

- sme_ptrf_apps/dre/api/views/relatorios_consolidados_dre_viewset.py
- sme_ptrf_apps/dre/models/relatorio_consolidado_dre.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_download_relatorio_final.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_status_relatorio_consolidado_dre.py
- sme_ptrf_apps/dre/tests/tests_relatorio_consolidado_dre/test_relatorio_consolidado_dre_model.py
Esse PR:
- Adiciona à consulta de status do relatório informações sobre a geração do documento;
- Implementa endpoint para download do relatório.
> Feature(25514) Relatório DRE Download

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta_nao_recebidas.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_model.py
- sme_ptrf_apps/dre/api/views/relatorios_consolidados_dre_viewset.py
Esse PR:
- Cria endpoint que retorna lista de prestações de contas não apresentadas;
- Alterar consulta dashboard DRE para somar PCs não apresentadas às não recebidas.
> Feature(26461) Painel DRE PCs Não Recebidas

- sme_ptrf_apps/dre/api/views/relatorios_consolidados_dre_viewset.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/planilha_relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_download_relatorio_previa.py
Esse PR:
- Cria serviço e endpoint para download da prévia do relatório consolidado DRE.
> feat(25521): Download de previa de relatorio DRE

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/periodo_associacao_services.py
* Criação de status Em_processamento e atualização de serviço para o status do período.
> Features/27551 geracao documentos prestacao contas async: Part 1

- README.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/despesas/admin.py
- sme_ptrf_apps/users/api/views/login.py
Esse PR:
- Ajusta o login do sistema para retornar informações de unidade para a visão SME
> Feature/29770 parametrizacao painel visão sme

- sme_ptrf_apps/receitas/admin.py
Faz ajustes no Admin de repasses para otimização.
> fix(30885): Corrige lentidão no admin de repasses

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard_sme.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Cria serviço e endpoint para retornar informações para o dashboard da SME.
> feat(28840): Informações para dashboard sme

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Altera a legenda de cores de status para a barra
do dashboard sme.
> feat(28840): Muda cor barra dashboard sme

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_dres/test_list_dres.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard_sme.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_unidades/test_list_unidades.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Adiciona resumo por DRE na consulta de acompanhamento de PCs da SME.
> feat(28852):Resumo por DRE acompanha PC SME

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard_sme.py
- sme_ptrf_apps/core/tests/tests_api_unidades/test_list_unidades.py
Esse PR:
- Altera para ordem alfabética o resumo por DRE na consulta de acompanhamento de PCs da SME.
> feat(28852): Resumo por DRE ordem alfabetica

- sme_ptrf_apps/core/admin.py
Esse PR:
- Adiciona campos e filtros na lista de demonstrativos financeiros no Admin.
> feat(29733): Admin lista demonstrativos financeiros

- sme_ptrf_apps/core/admin.py
Esse PR:
- Adiciona campos e filtros na lista de relações de bens no Admin.
> feat(29733): Admin lista relações de bens

- config/api_router.py
- sme_ptrf_apps/core/api/serializers/__init__.py
- sme_ptrf_apps/core/api/serializers/acao_associacao_serializer.py
- sme_ptrf_apps/core/api/views/__init__.py
- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/core/tests/tests_acao_associacao/test_acao_associacao_serializer.py
- sme_ptrf_apps/core/tests/tests_acao_associacao/test_acao_associacao_viewset.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_create.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_delete.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_update.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acoes_associacoes_list.py
Esse PR implementa na API o recurso acoes-associações com:
- List
- Create
- Retrieve
- Update
- Delete
- Filtros por nome associação, nome unidade, eol, ação e status
> Feat(29897) Parametrização Ações Associações

- sme_ptrf_apps/core/api/serializers/acao_associacao_serializer.py
- sme_ptrf_apps/core/tests/tests_acao_associacao/test_acao_associacao_serializer.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acoes_associacoes_list.py
Esse PR:
- Acrescenta a data e hora de criação na lista de ações de associações.
> feat(29897):Add criado_em no list ações associações

- config/api_router.py
- sme_ptrf_apps/core/api/serializers/acao_serializer.py
- sme_ptrf_apps/core/api/views/__init__.py
- sme_ptrf_apps/core/api/views/acoes_viewset.py
- sme_ptrf_apps/core/tests/tests_acao/test_acao_viewset.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acoes_list.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acoes_associacoes_list.py
Esse PR implementa na API o list do recurso ações.
> feat(29897):Lista de ações

- sme_ptrf_apps/core/api/serializers/periodo_serializer.py
- sme_ptrf_apps/core/api/views/periodos_viewset.py
- sme_ptrf_apps/core/models/periodo.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/services/periodo_services.py
- sme_ptrf_apps/core/tests/tests_api_periodos/conftest.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_list_periodos.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_create.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_delete.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_update.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_verifica_datas.py
- sme_ptrf_apps/core/tests/tests_periodo/test_periodo_model.py
- sme_ptrf_apps/core/tests/tests_periodo/test_periodo_serializer.py
Esse PR Implementa a API para o módulo de parametrização de períodos.
> Feat(29908) Parametrização de  Períodos

- sme_ptrf_apps/core/api/views/acoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_acoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acao_delete.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acao_retrieve.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acao_update.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acoes_create.py
- sme_ptrf_apps/core/tests/tests_api_acoes/test_acoes_list.py
Esse PR:
- Implementa ações de List, Create, Retrieve, Update e Delete, para o recurso Ações.
- Implementa o filtro por nome na lista de ações.
> Feat(29917) Parametrização Ações

- sme_ptrf_apps/core/api/serializers/periodo_serializer.py
- sme_ptrf_apps/core/api/views/periodos_viewset.py
- sme_ptrf_apps/core/services/periodo_services.py
- sme_ptrf_apps/core/tests/tests_api_periodos/conftest.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_create.py
- sme_ptrf_apps/core/tests/tests_api_periodos/test_periodo_verifica_datas.py
Esse PR faz ajustes na validação de períodos.
> Feat(29908) Parametro periodos ajustes de validação

- sme_ptrf_apps/core/api/serializers/associacao_serializer.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_retrieve_associacao.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
Inclui o campo período inicial no serializer de associação.
> feat(29886): Período inicial no serializer de associação

- sme_ptrf_apps/core/api/serializers/associacao_serializer.py
- sme_ptrf_apps/core/services/unidade_service.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_retrieve_associacao.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- Incluindo ID no serializer AssociacaoCompletoSerializer, Tipo de Unidade em unidade_service/consulta_unidade e corrigindo testes
> Finalizando Feature - 29886 - ajustes na API

- sme_ptrf_apps/core/api/serializers/associacao_serializer.py
- sme_ptrf_apps/core/api/serializers/unidade_serializer.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/api/views/periodos_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_delete_associacao.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_post_associacao.py
- Incluindo periodo_inicial_uuid em AssociacaoUpdateSerializer, tipo de unidade em UnidadeCreateSerializer, tratando erro quando associação estiver sendo usada e criando testes
> Finalizando Feature 29886 - ajustes na api 2

- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/core/models/acao_associacao.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_create.py
Cria endpoint para vincular associações a uma ação em lote.
> feat(29917): Vínculo associações ação em lote

- sme_ptrf_apps/core/services/notificacao_service.py
- sme_ptrf_apps/users/api/views/user.py
* Ajustes na notificação de membros da associação e filtros de usuários por username
> Ajustes na notificaçao de membros e filtro de usuario por username

- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/core/tests/tests_api_acoes_associacoes/test_acao_associacao_delete.py
- Finalizando: Corrigindo mensagem de erro ao tentar excluir ação de associação
> Corrigindo mensagem de erro ao tentar excluir ação de associação

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api.py
Esse PR corrige o bug que ocorria na atualização de e-mail.
Resolve o bug [AB#32999](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/32999)
> Fix(32999) Bug atualização email

- Dockerfile
Altera dockerfile para add instalações requeridas pelo Weasyprint.
> fix(29181): Ajusta instalação do Weasyprint

- Dockerfile
Altera dockerfile para add instalações requeridas pelo Weasyprint.
> fix(29181): Ajusta instalação do Weasyprint 2

- sme_ptrf_apps/core/tasks.py
Bug [AB#34487](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34487)
> fix(34487): Erro de soft limited ao gerar docs de pc

- sme_ptrf_apps/core/models/arquivo.py
- sme_ptrf_apps/core/models/modelo_carga.py
- Finalizando Feature 34053 - [Admin] Auditoria de alterações (auditlog) para os arquivos de cargas
> Feature 34053 - [Admin] Auditoria de alterações (auditlog) para os arquivos de cargas

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_transacoes_conciliacao.py
- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- sme_ptrf_apps/receitas/api/serializers/tipo_receita_serializer.py
Esse PR implementa a primeira parte das mudanças na API de conciliação.
História [AB#34038](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34038)
> feat(34038): Alterações API Conciliação - parte 1

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/conftest.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_transacoes_conciliacao.py
Esse PR:
- Implementa o filtro por tipo de transação na consulta de transações para conciliação.
História: [AB#34038](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34038)
> feat(34038): Alterações API Conciliação - parte 2

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_conciliar_desconciliar_transacao.py
Esse PR:
- Implementa a conciliação/desconciliação por transação.
História: [AB#34038](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34038)
> feat(34038): Alterações API Conciliação - parte 3

- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_transacoes_conciliacao.py
Corrige falha na montagem da lista de transações.
> feat(34038): Corrige algoritimo que monta lista transacoes

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/users/services/carga_usuarios.py
Esse PR:
- Implementa a atualização do e-mail do usuário no CoreSSO pelo programa de carga de usuários.
História [AB#31470](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31470)
> Feat(31470): Carga usuarios atualiza email no CoreSSO

- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/carga_usuarios.py
Esse PR:
- Altera a carga de usuários para atualizar os grupos de acesso.
História: [AB#31471](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31471)
> feat(31471): Carga usuarios atualizando grupos

- sme_ptrf_apps/contrib/exporta_grupos_csv.py
Esse PR:
- Cria um script para extração dos grupos de permissão de acesso.
História [AB#34014](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34014)
> feat(34014): Script de exportação de grupos e permissões

- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/conftest.py
- sme_ptrf_apps/despesas/tests/tests_api_rateios_despesas/test_verifica_saldo_antes_post.py
Esse PR, altera a verificação de saldos para considerar o caso de despesa em data anterior ao período inicial da associação.
História [AB#35135](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/35135)
> feat(35135): Altera verificação de saldos

- config/api_router.py
- sme_ptrf_apps/sme/api/views/saldos_bancarios_sme_viewset.py
- sme_ptrf_apps/sme/services/saldo_bancario_service.py
- sme_ptrf_apps/sme/tests/conftest.py
- sme_ptrf_apps/sme/tests/tests_api_saldos_bancarios/test_saldos_bancarios.py
- Finalizando Feature 35170 - [SME] Consulta de saldos bancários: Por Diretoria
> Finalizando feature 35170 saldo por dre

- sme_ptrf_apps/sme/api/views/saldos_bancarios_sme_viewset.py
- sme_ptrf_apps/sme/services/saldo_bancario_service-COPIA.py
- sme_ptrf_apps/sme/services/saldo_bancario_service-COPIA2.py
- sme_ptrf_apps/sme/services/saldo_bancario_service-COPIA3.py
- sme_ptrf_apps/sme/tests/tests_api_saldos_bancarios/conftest.py
- sme_ptrf_apps/sme/tests/tests_api_saldos_bancarios/test_saldos_bancarios.py
- Finalizando Feature 35171 - [SME] Consulta de saldos bancários: Por tipo de UE e DRE
> Finalizando feature 35171 saldos por dre ue

- sme_ptrf_apps/core/migrations/0155_demonstrativofinanceiro_status.py
- sme_ptrf_apps/core/migrations/0156_relacaobens_status.py
Ajuste a migração para setar como default o status CONCLUIDO nos
arquivos de PC.
> feat(31433): Ajusta na migração valor default para status docs pc

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/models/observacao_conciliacao.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_observacoes.py
- sme_ptrf_apps/sme/services/saldo_bancario_service.py
- sme_ptrf_apps/sme/tests/tests_api_saldos_bancarios/test_saldos_bancarios.py
- Finalizando Feature 35175 - [SME] Consulta de saldos bancários: Por Unidade Escolar: Download e Preview do extrato anexado
> feature 35175 - download e preview extrato

- sme_ptrf_apps/core/services/relacao_bens.py
> Removendo código comentado

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/services/demonstrativo_financeiro_pdf_service.py
- sme_ptrf_apps/core/services/demonstrativo_financeiro_xlsx_service.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/static/css/pdf-demo-financeiro.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf.html
Esse PR:
- Implementa os endpoints para download do arquivo PDF de demonstrativo financeiro (Prévia e Final)
- Alterar o fluxo de geração de documentos para gerar os PDF também na geração de prévias.
História [AB#34020](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34020)
> Feat(34020) Demonstrativo Financeiro em PDF (Parte 2)

- sme_ptrf_apps/core/services/conciliacao_services.py
Esse PR:
Corrige o valor do saldo reprogramado não conciliado
no módulo de conciliação.
Fix [AB#36552](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/36552)
> Fix(36552): Corrige saldo não conciliado

- README.md
- sme_ptrf_apps/__init__.py
> docs(1.9.0): Inicio Sprint 18

- sme_ptrf_apps/contrib/core_sso_scripts/criacao_usuarios.sql
Esse PR adiciona à pasta contribs do projeto os scripts para criação de usuários no CoreSSO e
vínculo ao PTRF.
[AB#36651](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/36651)
> story(36651) Criação de usuários CoreSSO

- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/static/css/pdf-demo-financeiro.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf.html
- Criando HTML e CSS para demonstrativo financeiro em PDF
> Criando HTML e CSS para demonstrativo financeiro em PDF

- README.md
- sme_ptrf_apps/__init__.py
> docs(1.10.0): Atualiza versão Sprint 19

- sme_ptrf_apps/core/services/carga_associacoes_service.py
Ajusta comportamento da carga quando consultava os dados no EOL.
> feat(31436): Ajustes na carga de associações

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/core/tests/tests_services/conftest.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/despesas/tests/tests_rateio_despesa/conftest.py
- sme_ptrf_apps/users/api/serializers/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_user.py
Esse PR, alterar alguns serviços da aplicação para passarem a ignorar despesas com status INCOMPLETO.
História [AB#39146](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39146)
Pontos verificados (não necessariamente alterados):
> Feat(39146) Trata despesas incompletas

- sme_ptrf_apps/core/services/unidade_service.py
Esse PR altera o serviço que atualiza as informações de unidades
com informações consultados no EOL, para que seja também
atualizado o tipo da unidade.
História [AB#39148](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39148)
> feat(39148): Altera atualização UE para atualizar tipo

- sme_ptrf_apps/core/api/views/membro_associacao_viewset.py
- sme_ptrf_apps/core/tests/tests_membro_associacao/test_membro_associacao_api.py
Esse PR altera a lista de membros da associação para permitir a busca por cpf.
História [AB#39113](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39113)
> feat(39113): Busca de membro por cpf

- sme_ptrf_apps/__init__.py
[AB#41498](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/41498)
> docs(1.13.0): Abre Sprint 22

- sme_ptrf_apps/core/models/__init__.py
- sme_ptrf_apps/core/models/notificacao.py
- sme_ptrf_apps/core/tests/tests_notificacao/test_notificar_service.py
Esse PR implementa um serviço único para geração de notificações permitindo evitar re-notificações se assim quiser.
[AB#38438](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/38438)
> feat(38438): Notificações de proximidade inicio período PC - Parte 2

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/services/relacao_bens.py
- sme_ptrf_apps/core/tasks.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_concluir_prestacao_de_contas_service.py
Esse PR corrige o comportamento do sistema que criava um documento relação de bens mesmo quando não
havia bens adquiridos, e esse documento ficava com o status em processamento perpetuamente.
[AB#38592](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/38592)
> fix(38592): Bug geração relação de bens

- sme_ptrf_apps/__init__.py
> docs(1.14.0): Abre versão 1.14.0

- sme_ptrf_apps/despesas/tests/tests_tipo_custeio/test_tipo_custeio_model.py
Esse PR:
- Altera test test_meta_modelo de Tipo de Custeio
Historia: [AB#40185](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40185)
> test(40185): Ajustes de texto diversos

- sme_ptrf_apps/core/services/unidade_service.py
Esse PR:
- Resolve o problema de não permitir incluir uma nova Associação pelo Admin ou Front, sem ser através de carga
> fix(40093): A inclusão de uma Associação só é feita por meio de carga

- Jenkinsfile
> Ebufaino cicd

- sme_ptrf_apps/core/services/membro_associacao_service.py
Esse PR altera as mensagens retornadas pela consulta de código EOL para serem mais amigáveis ao usuário.
[AB#39282](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39282)
> feat(39282): Ajusta mensagens da consulta EOL

- sme_ptrf_apps/__init__.py
[AB#43368](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43368)
> Posição de Develop em 13/07 08:44

- sme_ptrf_apps/core/services/membro_associacao_service.py
[AB#41495](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/41495)
> Posição do Develop em 13/07 13:13

- sme_ptrf_apps/receitas/api/views/receita_viewset.py
- sme_ptrf_apps/receitas/services/__init__.py
- sme_ptrf_apps/receitas/services/total_receita.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_get_receitas_totais.py
Esse PR Adiciona endpoint que retorna a soma dos valores de créditos.
História [AB#29419](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/29419)
> feat(29419) Adiciona endpoint que retorna a soma dos valores de créditos

- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
Esse PR:
- Altera a saída vinculada a créditos de recursos externos para utilização de formulário simplificado
História: [AB#42276](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42276)
> feat(42276): Gastos da escola: Na edição de saídas vinculadas a créditos de recursos externos usar formulário simplificado

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta_todos_os_status.py
Esse PR: 
- Cria novo endpoint para o filtro TODOS OS STATUS que combina o resultado de associação que ainda não geraram PC (status=Não Apresentado) com os demais.
História: [AB#40217](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40217)
> feat(40217): [DRE] Acompanhamento das Prestações de Contas:  Ver todas as prestações

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_grupos_user.py
Esse PR:
- Retorna a visão atual do usuário e suas subordinadas de acordo com a Prioridade SME > DRE > UE
História: [AB#42237](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42237)
> feat(42237): [DRE][SME] Perfil de Acessos: Exibir grupos de acessos das visões subordinadas

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
Esse PR:
- Implementa tratamento e mensagem de retorno ao tentar deletar despesa relacionada a outras entidades
História: [AB#39149](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/39149)
> feat(39149): [Associação]  Mensagem ao não conseguir apagar despesas por estar relacionada a outras entidades

- sme_ptrf_apps/core/services/notificacao_services/notificacao_teste_envio_de_email.py
Esse PR:
- Altera o filtro de usuários que recebem email de nova notificação
História: [AB#34048](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34048)
> feat(34048): Envio de e-mail para informar entrada de nova notificação - Parte 2

- sme_ptrf_apps/core/models/notificacao.py
- sme_ptrf_apps/core/services/enviar_email.py
- sme_ptrf_apps/core/services/notificacao_services/enviar_email_nova_notificacao.py
- sme_ptrf_apps/core/services/notificacao_services/notificacao_teste_envio_de_email.py
- sme_ptrf_apps/templates/email/email_nova_notificacao.html
- sme_ptrf_apps/users/tasks.py
Esse PR:
- Altera método de envio para fazer a verificação e evitar repetição no envio do email
- Altera template html, ajustando url
- Remove e melhora mensagens de logger.info
História: [AB#34048](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34048)
> feat(34048): Envio de e-mail para informar entrada de nova notificação - Parte 3

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
feat(34436): Reordena relatório consolidado
Esse PR:
- Adiciona tipo unidade a ordenação do retorno da API,
- Agrupa ordenação por status da prestação de contas.
História: [AB#34436](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34436)
> feat(34436) Reordena relatório consolidado

- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_grupos_user.py
Esse PR: 
- Altera endpoint que retorna os grupos de acordo com a visão
- Inclui visao no retorno da API de grupos
História: [AB#42237](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42237)
> feat(42237): Perfil de Acessos: Exibir grupos de acessos das visões subordinadas

- sme_ptrf_apps/core/services/exporta_associacao.py
Esse PR: 
- Corrige bug não exportar dados da Associação
História: [AB#42731](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/42731)
> fix(42731): Firefox: Não está funcionando Exportar dados da Associação

- sme_ptrf_apps/dre/services/planilha_relatorio_consolidado_service.py
Esse PR:
- Ajusta a criação/atualização do relatório consolidado DRE para sobrescrever um relatório previamente criado para a mesma
DRE, Conta e Período, independente do status.
História: [AB#31426](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31426)
> feat(31426): Passa o relatório consolidado DRE para assíncrono - Parte 2

- sme_ptrf_apps/static/css/pdf-demo-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
Esse PR:
- Altera o layout do PDF dos itens
- Altera cabeçalho
- Altera diagramação Bloco 1 e Bloco 2
- Altera diagramação Bloco 9 - Assinatura dos Responsáveis pela Prestação de Contas
> feat(43742): Demonstrativo financeiro: inclusão de bloco e alteração formato no PDF - Parte 2

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/associacoes_service.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_action_status_prestacoes.py
Esse PR:
- Adiciona endpoint que retorna status das prestações por associacao.
- Adiciona filtros por período e status da px
História: [AB#44199](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44199)
> feat(44199): Consulta de análises da DRE: Lista

- sme_ptrf_apps/core/services/associacoes_service.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_action_status_prestacoes.py
Esse PR:
- Adiciona legenda cor ao retorno do endpoint de status das prestações
História: [AB#44199](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44199)
> feat(44199): Consulta de análises da DRE: Lista- Parte 2

- sme_ptrf_apps/templates/pdf/associacoes/exportarpdf/pdf.html
Esse PR:
- Altera PDF de ficha cadastral - dados da associacao
História: [AB#46248](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46248)
> feat(46248): Dados da Associação e Ficha Cadastral: E-mail da Associação passa a chamar e-mail da UE

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
Esse PR:
- Altera o retorno dos totais filtrados em Lista de Despesas
História: [AB#46266](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46266)
> feat(46266): Gastos da Escola: Inconsistência nos totais sem filtro e com filtro

- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/templates/pdf/associacoes/exportarpdf/pdf.html
[AB#46166](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46166)
> Posição de Develop em 23/08 07:04

- sme_ptrf_apps/despesas/models/especificacao_material_servico.py
- sme_ptrf_apps/despesas/models/fornecedor.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/despesas/models/tipo_custeio.py
- sme_ptrf_apps/despesas/models/tipo_documento.py
- sme_ptrf_apps/despesas/models/tipo_transacao.py
- sme_ptrf_apps/despesas/tests/tests_rateio_despesa/test_rateio_despesa_model.py
- sme_ptrf_apps/receitas/models/detalhe_tipo_receita.py
- sme_ptrf_apps/receitas/models/repasse.py
- sme_ptrf_apps/receitas/models/tipo_receita.py
feat(48039) Adiciona auditlog
Esse PR:
- Adiciona auditlog ao modelo EspecificacaoMaterialServico
- Adiciona auditlog ao modelo Fornecedor
- Adiciona auditlog ao modelo RateioDespesa
- Adiciona auditlog ao modelo TipoCusteio
- Adiciona auditlog ao modelo TipoDocumento
- Adiciona auditlog ao modelo TipoTransacao
- Adiciona auditlog ao modelo DetalheTipoReceita
- Adiciona auditlog ao modelo Repasse
- Adiciona auditlog ao modelo TipoReceita
- Altera str do modelo RateioDespesa
- Altera test relacionado ao str do modelo RaterioDespesa
História: [AB#48039](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48039)
> feat(48039) Adiciona auditlog

- sme_ptrf_apps/core/models/ata.py
- sme_ptrf_apps/core/models/demonstrativo_financeiro.py
- sme_ptrf_apps/core/models/fechamento_periodo.py
- sme_ptrf_apps/core/models/notificacao.py
- sme_ptrf_apps/core/models/observacao_conciliacao.py
- sme_ptrf_apps/core/models/parametro_fique_de_olho_pc.py
- sme_ptrf_apps/core/models/parametros.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/models/relacao_bens.py
- sme_ptrf_apps/core/models/tipo_devolucao_ao_tesouro.py
feat(47958) Adiciona auditlog
Esse PR:
- Adiciona auditlog ao modelo Parametros
- Adiciona auditlog ao modelo ParametroFiqueDeOlhoPc
- Adiciona auditlog ao modelo Notificacao
- Adiciona auditlog ao modelo PrestacaoConta
- Adiciona auditlog ao modelo FechamentoPeriodo
- Adiciona auditlog ao modelo DemonstrativoFinanceiro
- Adiciona auditlog ao modelo RelacaoBens
- Adiciona auditlog ao modelo Ata
- Adiciona auditlog ao modelo ObservacaoConciliacao
- Adiciona auditlog ao modelo TipoDevolucaoAoTesouro
História: [AB#47958](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/47958)
> feat(47958) Adiciona auditlog

- sme_ptrf_apps/dre/models/atribuicao.py
- sme_ptrf_apps/dre/models/faq.py
- sme_ptrf_apps/dre/models/faq_categoria.py
- sme_ptrf_apps/dre/models/grupo_verificacao_regularidade.py
- sme_ptrf_apps/dre/models/item_verificacao_regularidade.py
- sme_ptrf_apps/dre/models/justificativa_relatorio_consolidado_dre.py
- sme_ptrf_apps/dre/models/lista_verificacao_regularidade.py
- sme_ptrf_apps/dre/models/motivo_aprovacao_ressalva.py
- sme_ptrf_apps/dre/models/obs_devolucao_relatorio_consolidado_dre.py
- sme_ptrf_apps/dre/models/relatorio_consolidado_dre.py
- sme_ptrf_apps/dre/models/tecnico_diretoria.py
- sme_ptrf_apps/dre/models/verificacao_regularidade_associacao.py
feat(48030) Adiciona auditlog
Esse PR:
- Adiciona auditlog ao modelo Atribuicao
- Adiciona auditlog ao modelo Faq
- Adiciona auditlog ao modelo FaqCategoria
- Adiciona auditlog ao modelo GrupoVerificacaoRegularidade
- Adiciona auditlog ao modelo ItemVerificacaoRegularidade
- Adiciona auditlog ao modelo JustificativaRelatorioConsolidadoDRE
- Adiciona auditlog ao modelo ListaVerificacaoRegularidade
- Adiciona auditlog ao modelo MotivoAprovacaoRessalva
- Adiciona auditlog ao modelo ObsDevolucaoRelatorioConsolidadoDRE
- Adiciona auditlog ao modelo RelatorioConsolidadoDRE
- Adiciona auditlog ao modelo TecnicoDre
- Adiciona auditlog ao modelo VerificacaoRegularidadeAssociacao
História: [AB#48030](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48030)
> feat(48030) Adiciona auditlog

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_get_lancamentos_solicitacoes_acerto.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_post_lancamentos_solicitacoes_acerto_em_lote.py
Esse PR:
- Altera a gravação de solicitações de ajustes para apagar a análise de lançamento caso não haja solicitações de
acertos.
História: [AB#43844](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43844)
> feat(43844) Acompanhamento de PC: Em Análise - parte4 - Pull Request 2

- sme_ptrf_apps/core/services/prestacao_contas_services.py
fix(46123) Corrige prévia demonstrativo financeiro
Esse PR:
- Corrige texto no arquivo PDF
História: [AB#46123](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46123)
> fix(46123) Corrige prévia demonstrativo financeiro

- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
Esse PR: 
- Altera filtro acao associacao, agora também é filtrado por associacao__uuid
História: [AB#34051](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/34051)
> feat(34051): Mensagem ao tentar excluir associação que tenha movimentação - Parte 02

- sme_ptrf_apps/core/api/views/acao_associacao_viewset.py
- sme_ptrf_apps/users/admin.py
História: [AB#48105](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48105)
> homolog(48105): Posição em Develop 06/09/2021 às 12:50

- sme_ptrf_apps/core/models/acao.py
- sme_ptrf_apps/core/models/acao_associacao.py
- sme_ptrf_apps/core/models/associacao.py
- sme_ptrf_apps/core/models/conta_associacao.py
- sme_ptrf_apps/core/models/membro_associacao.py
- sme_ptrf_apps/core/models/periodo.py
- sme_ptrf_apps/core/models/proccessos_associacao.py
- sme_ptrf_apps/core/models/tag.py
- sme_ptrf_apps/core/models/tipo_conta.py
- sme_ptrf_apps/core/models/unidade.py
feat(31474) Adiciona audtilog
Esse PR:
- Adiciona auditlog ao modelo Acao
- Adiciona auditlog ao modelo AcaoAssociacao
- Adiciona auditlog ao modelo Associacao
- Adiciona auditlog ao modelo ContaAssociacao
- Adiciona auditlog ao modelo MembroAssociacao
- Adiciona auditlog ao modelo Periodo
- Adiciona auditlog ao modelo ProcessoAssociacao
- Adiciona auditlog ao modelo Tag
- Adiciona auditlog ao modelo TipoConta
- Adiciona auditlog ao modelo Unidade
História: [AB#31474](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31474)
> feat(31474) Adiciona audtilog

- config/api_router.py
- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/serializers/analise_documento_prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/__init__.py
- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_analise_prestacao_conta/test_analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/conftest.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_documentos.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_retrieve_analise_prestacao_contas.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_documentos/test_get_documentos_solicitacoes_acerto.py
- sme_ptrf_apps/users/api/views/user.py
- sme_ptrf_apps/users/tests/test_api_user/test_api_list_user.py
Esse PR:
- Cria endpoint que retorna solicitações de ajustes de lançamentos de uma análise;
- Cria endpoint que retorna solicitações de ajustes de documentos de uma análise;
- Corrige alguns testes que estavam quebrando.
História: [AB#43914](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/43914)
> feature(43914):  Acompanhamento de PC parte 8a

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_com_filtros.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_receitas_atrelar_saida_de_recurso.py
feat(46303) Agrupa rateios
Esse PR:
- Adiciona serializer para listar despesas com rateios
- Adiciona paginacao ao viewset de despesas
- Adiciona filtros de despesa e rateios ao viewset de despesas
- Altera testes referentes a despesas
História: [AB#46303](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46303)
> feat(46303) Agrupa rateios

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
Adiciona "Serializer" ao nome da classe
> feat(46303)-parte-2 altera nome serializer

- sme_ptrf_apps/core/services/associacoes_service.py
- sme_ptrf_apps/core/services/periodo_services.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_painel_acoes.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_painel_acoes_de_uma_conta.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_action_status_prestacoes.py
Esse PR: 
- Inclui pc uuid em status_prestacao_conta_associacao
História: [AB#44206](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44206)
> feat(44206): Consulta de análises da DRE: Detalhamento da análise

- sme_ptrf_apps/core/services/conciliacao_services.py
- sme_ptrf_apps/despesas/api/views/rateios_despesas_viewset.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
feat(48640) Altera vinculo de despesas ao periodo
Esse PR:
- Vincula despesas por data transação
História: [AB#48640](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/48640)
> feat(48640) Altera vinculo de despesas ao periodo

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_com_filtros.py
Esse PR:
- Implementa Filtro por Tag em Despesas
História: [AB#46304](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46304)
> feat(46304): Gastos da escola: Filtro por vínculos de atividade (tags)

- sme_ptrf_apps/static/css/pdf-demo-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(51274) Ajustes PDF desmontrativo financeiro
Esse PR:
- Realiza ajustes nos textos.
História: AB#51247
> feat(51274) Ajustes PDF desmontrativo financeiro

- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(51753) Ajuste de texto no PDF demonstrativo financeiro
Esse PR:
- Realiza ajuste de texto da coluna 35 dos blocos: 5,6 e 7
História: [AB#51753](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/51753)
> feat(51753) Ajuste de texto no PDF demonstrativo financeiro

- sme_ptrf_apps/core/models/analise_prestacao_conta.py
feat(44181)-parte-3 Ajuste de texto
Esse PR:
- Realiza ajuste de texto
História: [AB#44181](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/44181)
> feat(44181)-parte-3 Ajuste de texto

- sme_ptrf_apps/core/choices/membro_associacao.py
- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/core/services/relacao_bens_dados_service.py
- sme_ptrf_apps/core/tests/tests_api_membros_associacao/test_list_cargos_diretoria_executiva.py
- sme_ptrf_apps/static/css/relacao-de-bens-pdf.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
- sme_ptrf_apps/templates/pdf/relacao_de_bens/pdf.html
Esse PR:
- Inclui informações de Presidente ausente em PDF Demonstrativo Financeiro e Relação de Bens
História: [AB#51989](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/51989)
> feat(51989): Presidente ausente: Geração de Documentos da Prestação de Contas

- sme_ptrf_apps/core/services/ata_dados_service.py
- sme_ptrf_apps/static/css/ata-pdf.css
- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR:
- Inclui assinaturas e separa conselho fiscal em PDF Ata de Apresentação de  PC
História: [AB#52123](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52123)
> feat(52123): Atas de PC : Distinguir a ata do parecer do conselho fiscal, incluir lista de assinaturas (PDF)

- sme_ptrf_apps/core/services/associacoes_service.py
feat(51989)-parte-2
Esse PR:
- Ajusta texto no endpoint que retorna o presidente ausente.
História: [AB#51989](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/51989)
> feat(51989)-parte-2

- sme_ptrf_apps/core/services/associacoes_service.py
Corrige erro no retorno de status do presidente.
> fix(51982): Corrige erro get_status_presidente

- sme_ptrf_apps/core/services/associacoes_service.py
História: [AB#52395](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52395)
> homolog(52395): Posição em Develop 17/11/2021 às 08:14

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_status_presidente.py
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(53081) Melhorias PDF Demonstrativo financeiro
Esse PR:
- Realiza melhorias no PDF do demonstrativo financeiro
História: [AB#53081](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53081)
> feat(53081) Melhorias PDF Demonstrativo financeiro

- sme_ptrf_apps/core/services/relacao_bens_dados_service.py
- sme_ptrf_apps/core/templatetags/formata_valores.py
- sme_ptrf_apps/static/css/relacao-de-bens-pdf.css
- sme_ptrf_apps/templates/pdf/relacao_de_bens/pdf.html
Esse PR: 
- Implementa melhorias em PDF de Relação de Bens
História: [AB#53194](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53194)
> feat(53194): Relação de bens (PDF): melhorias

- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/services/ata_dados_service.py
- sme_ptrf_apps/core/services/ata_service.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR faz diversas alterações de texto e cálculos na ata de Prestação de Contas.
História: [AB#53174](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53174)
> feat(53174): Altera cálculos e textos da ata PC em PDF

- sme_ptrf_apps/templates/pdf/ata/pdf.html
> feat(53174): Ajusta texto pdf ata

- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(53081)-parte-2
Esse PR:
- Ajusta tamanho das colunas bloco 5,6 e 7
História: [AB#53081](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53081)
> feat(53081)-parte-2

- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(53081)-parte-3
Esse PR:
- Ajusta tamanho da coluna "Ação do programa" bloco 5,6 e 7
História: [AB#53081](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53081)
> feat(53081)-parte-3

- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
Ajuste tamanho da coluna "Ação do programa" bloco 5,6 e 7
> feat(53081)-ajuste

- sme_ptrf_apps/templates/pdf/ata/pdf.html
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
História: [AB#53432](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53432)
> homolog(53432): Posição em Develop 24//11/2021 às 14:07

- sme_ptrf_apps/users/api/views/login.py
Esse PR:
- Altera o login do sistema para verificar se o usuário está ativo.
História [AB#50812](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50812)
> feat(50812): Altera login para verificar user.active

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/analise_valor_reprogramado_prestacao_conta_viewset.py
- sme_ptrf_apps/core/tests/tests_analise_valor_reprogramado_prestacao_conta/test_analise_valor_reprogramado_prestacao_conta_model.py
- sme_ptrf_apps/core/tests/tests_analise_valor_reprogramado_prestacao_conta/test_analise_valor_reprogramado_prestacao_conta_serializer.py
- sme_ptrf_apps/core/tests/tests_analise_valor_reprogramado_prestacao_conta/test_analise_valor_reprogramado_prestacao_conta_viewset.py
- sme_ptrf_apps/core/tests/tests_api_analise_valor_reprogramado_prestacao_conta/test_api_action_get_analise_valor_reprogramado_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_analise_valor_reprogramado_prestacao_conta/test_api_action_post_analise_valor_reprogramado_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_analise_valor_reprogramado_prestacao_conta/test_api_patch_analise_valor_reprogramado_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_analise_valor_reprogramado_prestacao_conta/test_api_post_analise_valor_reprogramado_prestacao_conta.py
Esse PR:
- Cria action salvar_valores_reprogramados_acao com suas devidas validações
- Inclui testes
> feat(50801) Solicitações de ajustes em valores reprogramados - Parte 02

- sme_ptrf_apps/core/api/serializers/__init__.py
- sme_ptrf_apps/core/api/serializers/acao_associacao_serializer.py
- sme_ptrf_apps/core/api/serializers/analise_valor_reprogramado_prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_ajustes_valores_reprogramados.py
- sme_ptrf_apps/core/tests/tests_api_presentes_ata/test_api_presentes_ata.py
feat(50806) Solicitações de ajustes em valores reprogramados
Esse PR:
- Adiciona endpoint que retorna solicitações de ajustes por conta
- Adiciona endpoint que verifica solicitações de ajustes independente da conta
História: [AB#50806](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50806)
> feat(50806) Solicitações de ajustes em valores reprogramados

- sme_ptrf_apps/core/services/dados_relatorio_acertos_service.py
- sme_ptrf_apps/static/css/pdf-relatorio-dos-acertos.css
- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
feat(53363) Relatorio de devolucao de acertos
Esse PR:
- Adiciona novo bloco ao PDF
- Exibe blocos apenas se tiver ajustes
- Renumera blocos de acordo com blocos que serão exibidos
História: [AB#53363](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53363)
> feat(53363) Relatorio de devolucao de acertos

- sme_ptrf_apps/dre/api/views/membros_comissoes_viewset.py
feat(46226) ajuste api
Esse PR:
- Realiza um pequeno ajuste na API
História: [AB#46226](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46226)
> feat(46226) ajuste api

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_associacoes_verificacao_regularidade_update.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_get_associacoes_verificacao_regularidade.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/regularidade_associacao_service.py
- sme_ptrf_apps/dre/tests/tests_services/test_verificacao_regularidade_associacao_service.py
Esse PR:
- Implementa atualização de regularidade por ano
- Implementa consulta de regularidade por ano
História: [AB#40174](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/40174)
> feat(40174) Análise de Regularidade ano vigente

- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_receitas_conciliacao.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_tabela_valores_pendentes.py
- sme_ptrf_apps/receitas/models/receita.py
- sme_ptrf_apps/receitas/tests/tests_api_receitas/test_get_receitas_com_filtros.py
feat(52339)-parte-2: Retirar creditos conciliação bancaria
Esse PR:
- Adiciona vinculo de periodo ao salvar um crédito
História: AB#52239
> feat(52339)-parte-2: Retirar creditos conciliação bancaria

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_devolucoes_ao_tesouro_relatorio_consolidado_dre.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_execucao_financeira_relatorio_consolidado_dre.py
fix(54919): Relatório consolidado
Esse PR:
- Adiciona filtro por tipo conta a devoluções ao tesouro
História: [AB#54919](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/54919)
> fix(54919): Relatório consolidado

- sme_ptrf_apps/static/css/pdf-demo-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
Esse PR:
- Evita quebra de página em linha da Tabela do Bloco 3 do Demonstrativo Financeiro em PDF
História: [AB#53056](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53056)
> feat(53056): Demonstrativo Financeiro: PDF: Bloco 3 não quebrar página no meio de uma ação

- sme_ptrf_apps/templates/pdf/ata/pdf.html
[AB#56175](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/56175)
> Posição de Develop em 21/01/22 06:49

- sme_ptrf_apps/dre/models/ata_parecer_tecnico.py
- sme_ptrf_apps/dre/tests/conftest.py
feat(46251)-parte-3: Ata de parecer tecnico
Esse PR:
- Cria condição para evitar duplicidade da ata
História: [AB#46251](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/46251)
> feat(46251)-parte-3: Ata de parecer tecnico

- sme_ptrf_apps/dre/api/views/relatorios_consolidados_dre_viewset.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/lauda_service.py
- sme_ptrf_apps/dre/tasks.py
feat(55535): Gerar lauda parecer tecnico txt
Esse PR:
- Adiciona serviço assincrono para gerar ata em txt
- Adiciona serviço para gerar ata em txt
História: [AB#55535](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55535)
> feat(55535): Gerar lauda parecer tecnico txt

- sme_ptrf_apps/dre/api/views/ata_parecer_tecnico_viewset.py
- sme_ptrf_apps/dre/models/ata_parecer_tecnico.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/ata_pdf_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tasks.py
- sme_ptrf_apps/dre/templatetags/formata_valores.py
- sme_ptrf_apps/static/css/ata-parecer-tecnico-pdf.css
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/partials/tabela-aprovada-com-ressalvas.html
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/partials/tabela-rejeitadas.html
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/partials/talela-aprovadas.html
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/pdf.html
Esse PR
- Cria Ata de Parecer Técnico em PDF
História: [AB#50065](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50065)
> feat(50065): Cria Ata de Parecer Técnico em PDF - Parte 01

- sme_ptrf_apps/dre/api/views/ata_parecer_tecnico_viewset.py
- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/static/css/ata-parecer-tecnico-pdf.css
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/pdf.html
Esse PR
- Cria método que retorna presentes na ata de parecer técnico e ajusta pdf html
História: [AB#50065](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50065)
> feat(50065): Ata de parecer técnico:  Ata em PDF - Parte 02

- sme_ptrf_apps/dre/services/lauda_service.py
feat(55535)-parte-2: Ajuste no numero da ordem
Esse PR:
- Ajusta exibição da ordem
História: [AB#55535](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55535)
> feat(55535)-parte-2: Ajuste no numero da ordem

- sme_ptrf_apps/core/api/views/periodos_viewset.py
- sme_ptrf_apps/core/services/periodo_services.py
fix(57486): Data de termino do periodo
Esse PR:
- Remove obrigatoriedade do campo Fim realização de despesas
História: [AB#57486](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57486)
> fix(57486): Data de termino do periodo

- sme_ptrf_apps/core/models/fechamento_periodo.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
- Altera o código de verificação de saldos para a validação de despesas.
História: [AB#57827](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57827)
> feat(57827): Altera cálculo verificação de saldo em despesa

- sme_ptrf_apps/dre/templatetags/formata_valores.py
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/partials/tabela-aprovada-com-ressalvas.html
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/partials/talela-aprovadas.html
fix(59073): Padronização do valor "vazio"
Esse PR:
- Padroniza exibição valor "vazio" (sem valor ou zerado)
História: [AB#59073](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59073)
> fix(59073): Padronização do valor "vazio"

- sme_ptrf_apps/core/services/membro_associacao_service.py
fix(58536): Nao reconhece codigo eol
Esse PR:
- Altera endpoint para buscar informacoes do aluno por codigo eol
História: [AB#58536](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58536)
> fix(58536): Nao reconhece codigo eol

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/static/css/pdf-demo-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(58781): Demonstrativo financeiro, indica estorno
Esse PR:
- Indica no PDF, quando um crédito ou despesa, possui estorno
História: [AB#58781](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58781)
> feat(58781): Demonstrativo financeiro, indica estorno

- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
Esse PR altera os serializers de rateio e créditos para resolver problema de referência cíclica a rateios estornados.
> feat(58666): Créditos referentes a estornos de gastos - parte 4

- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
feat(58666): Creditos da escola referentes ao estorno de gastos
Esse PR:
- Realiza ajuste no serializer RateioDespesaTabelaGastosEscolaSerializer
> feat(58666): Creditos da escola referentes ao estorno de gastos

- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_associacoes_srarus_regularidade_ano.py
- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_transacoes_conciliacao.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/tests_api_lancamentos/test_get_lancamentos.py
- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
Esse PR: 
- Adiciona informação de estorno em Acompanhamento de PC
História: [AB#58775](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58775)
> feat(58775) Acompanhamento de PC: Conferência de Lançamentos: Exibir informação de estorno

- sme_ptrf_apps/dre/models/verificacao_regularidade_associacao.py
- sme_ptrf_apps/dre/tests/tests_verificacao_regularidade_associacao/test_verificacao_regularidade_associacao_model.py
feat(59342)-parte-2: Altera str do modelo VerificacaoRegularidade
Esse PR:
- Altera str do modelo
- Altera teste do str do modelo
História: [AB#59342](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59342)
> feat(59342)-parte-2: Altera str do modelo VerificacaoRegularidade

- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/partials/tabela-aprovada-com-ressalvas.html
- sme_ptrf_apps/templates/pdf/ata_parecer_tecnico/partials/talela-aprovadas.html
Esse PR:
- Altera layout pdf Ata Parecer Técnico, formata valores e alinha campos à direita
História: AB#59433
> feat(59433): Ata de parecer técnico - Tabelas: não quebrar página no meio de uma unidade e exibir os "zeros"

- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_com_filtros.py
Esse PR:
- Altera test_get_despesas_com_filtros
> test(59496): Gastos da Escola: Lançamento de imposto retido na fonte

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
Esse PR:
- Ajusta validação de status em rateios da despesa
História: [AB#59509](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59509)
> feat(59509): Cadastro de despesa sem comprovação fiscal

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_get_despesas_com_filtros.py
História: [AB#59677](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/59677)
> homolog(59677): Posição em Develop 18/03/2022 às 12:06h

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
Esse PR:
- Ajusta status dos rateios da despesa
> feat(58539): Gastos da Escola: Confirmação e justificativa de pagamento antecipado

- sme_ptrf_apps/core/api/views/atas_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/associacoes_service.py
- sme_ptrf_apps/core/services/ata_dados_service.py
- sme_ptrf_apps/core/tests/tests_api_atas_associacao/test_ata_associacao_despesas_com_pagamento_antecipado.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_despesa_motivos_pagamento_antecipado.py
- sme_ptrf_apps/static/css/ata-pdf.css
- sme_ptrf_apps/templates/pdf/ata/partials/tabela-despesas-com-pagamento-antecipado.html
- sme_ptrf_apps/templates/pdf/ata/pdf.html
Esse PR:
- Cria serviço e endpoint para retornar despesas com pagamento antecipado por associacao e periodo
> feat(58564): 

- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
Esse PR:
- Inclui MotivoEstornoSerializer em ReceitaListaSerializer
> feat(60061):  Incluir motivos do estorno

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/templates/pdf/demonstrativo_financeiro/pdf-horizontal.html
feat(60062): Incluir numero nota.
Esse PR:
- Adiciona número da nota a informação de estorno
> feat(60062): Incluir numero nota

- sme_ptrf_apps/receitas/api/views/motivos_estorno_viewset.py
> feat(60953)-parte-2: Parametrização motivos estorno

- sme_ptrf_apps/core/tests/tests_api_presentes_ata/conftest.py
- sme_ptrf_apps/core/tests/tests_api_presentes_ata/test_api_presentes_ata.py
Esse PR altera os testes da API de presentes da ata para que os resultados testados não variem de execução para
execução.
> test(61218): Altera testes api presentes da ata

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_list_prestacoes_conta.py
- sme_ptrf_apps/sme/tests/tests_api_saldos_bancarios/test_saldos_bancarios.py
Esse PR Altera os testes de forma que o testado não varie de execução para execução.
> test(61218): Ajusta testes pcs e saldos

- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
feat(61290): ajustes status
Esse PR:
- Realiza ajuste nos status de despesas impostos
História: [AB#61290](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61290)
> feat(61290): ajustes status

- sme_ptrf_apps/core/services/conciliacao_services.py
Esse PR:
-  Adiciona verificação de status Completo
História: [AB#61150](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61150)
> feat(61150): Exibir informações de retenção de imposto na conciliação bancária - Parte 03

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
Esse PR corrige em pré-produção o bug [AB#62982](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62982)
> fix(62982): Corrige erro prévia demonstrativo financeiro

- sme_ptrf_apps/despesas/api/views/despesas_viewset.py
- sme_ptrf_apps/despesas/services/despesa_service.py
Esse PR:
- Cria ordenação de despesas por imposto
História: [AB#61360](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61360)
> feat(61360): Exibir informações de retenção de imposto nos gastos da escola

- sme_ptrf_apps/core/api/views/presentes_ata_viewset.py
- sme_ptrf_apps/core/models/presentes_ata.py
feat(57132): Revisão da inclusão de presentes
Esse PR:
- Realiza ajuste na API para resposta a não membros servidores
História: [AB#57132](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57132)
> feat(57132): Revisão da inclusão de presentes

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
feat(58447): Ordenar despesas
Esse PR:
- Ordena despesas por data transacao e numero documento
História: [AB#58447](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58447)
> feat(58447): Ordenar despesas

- sme_ptrf_apps/core/services/prestacao_contas_services.py
Esse PR:
- Inclui verificação de conta associacao na exibição
História: [AB#61151](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/61151)
> feat(61151): Exibir informações de retenção de imposto na análise de PC - Parte 04

- sme_ptrf_apps/core/services/prestacao_contas_services.py
Esse PR:
- Valida se despesa é completa antes de incluir na lista de lancamentos
> feat(61151): Exibir informações de retenção de imposto na análise de PC - Parte 05

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
Esse PR:
- Resolve: [AB#63366](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63366)
> hotfix(63366): Sistema não exibe corretamente total dos rateios

- README.md
- sme_ptrf_apps/__init__.py
História: [AB#63585](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63585)
> doc(63585): Release notes - release 4

- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/despesas/api/serializers/rateio_despesa_serializer.py
Esse PR:
- Inclui data_transacao em RateioDespesaEstornoLookupSerializer
História: [AB#63021](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63021)
> feat(63021): Acompanhamento de PC: Rever o tooltip de estorno para exibir data transação

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
- Inclui filtros em Conferência de lançamentos no Acompanhamento PC:
período (intervalo de datas)
número do documento
tipo de documento
tipo de transação/pagamento
História: [AB#55988](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55988)
> feat(55988): Acompanhamento PC: Novos filtros na conferência de lançamentos

- sme_ptrf_apps/dre/admin.py
- sme_ptrf_apps/dre/services/regularidade_associacao_service.py
Resolve: [AB#63533](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63533)
> fix(63533): Regularidade: as listas de verificação de regularidade não são ordenadas pelo id

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_salva_devolucoes_ao_tesouro.py
Corrige: [AB#63574](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63574)
> fix(63574):  Ata de retificação: Duplicação de devolução ao tesouro 

- sme_ptrf_apps/dre/admin.py
- sme_ptrf_apps/dre/services/regularidade_associacao_service.py
Corrige: [AB#63533](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63533)
> fix(63533): Resolve ordenação da lista regularidade por id

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_salva_devolucoes_ao_tesouro.py
- sme_ptrf_apps/dre/admin.py
- sme_ptrf_apps/dre/services/regularidade_associacao_service.py
Corrige os bugs: [AB#63533](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63533) e [AB#63574](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63574)
> hotfix(1.30.1)

- sme_ptrf_apps/core/services/dados_relatorio_acertos_service.py
- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
Esse PR altera o relatório de ajustes em PDF para incluir solicitações de ajustes em informações de extrato.
História: [AB#62550](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62550)
> feat(62550): Alterar relatório de ajustes em PDF

- sme_ptrf_apps/core/api/views/analise_conta_prestacao_conta_viewset.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_conclui_analise_prestacao_conta_como_aprovada.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_salva_analise_prestacao_conta.py
Esse PR:
- Adiciona retrieve de ajustes em saldo e data
História: [AB#62450](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62450)
> feat(62450): Solicitar ajuste de saldo parte-2

- sme_ptrf_apps/dre/services/planilha_relatorio_consolidado_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Corrige exibição de devoluções ao tesouro bloco 4
Corrige: [AB#63850](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63850)
> fix(63850): Demonstrativo financeiro: o cálculo do saldo reprogramado (campo 15) não considera a despesa realizada (campo 14) 

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/api/views/analise_conta_prestacao_conta_viewset.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_serializer.py
feat(62450): Solicitar ajuste de saldo parte-3
Esse PR:
- Cria action para vinculação de ultima analise pc
- Altera retrieve de analise de contas para trazer por analise
História: [AB#62450](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62450)
> feat(62450): Solicitar ajuste de saldo parte-3

- sme_ptrf_apps/core/api/views/analises_prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
Esse PR altera o ViewSet de Análises de Prestações de Contas, incluindo endpoint para retornar as solicitações de ajustes em informações de extrato bancário.
História: [AB#62548](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62548)
> feat(62548): Altera API Análises Prestações de Contas

- sme_ptrf_apps/core/services/notificacao_services/notificacao_comentario_pc_service.py
Corrige o bug: [AB#64387](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64387)
> fix(64387): Corrige notificação de mensagem em PC

- sme_ptrf_apps/core/services/notificacao_services/notificacao_comentario_pc_service.py
Corrige: [AB#64374](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64374)
> fix(64374): Uma notificação de comentário foi disparada para 367 usuários indevidamente 

- sme_ptrf_apps/core/services/dados_relatorio_acertos_service.py
- sme_ptrf_apps/static/css/pdf-relatorio-dos-acertos.css
- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
feat(63347): Altera layout pdf relatorio acertos
Esse PR:
- Realiza mudança de layout
História: [AB#63347](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63347)
> feat(63347): Altera layout pdf relatorio acertos

- sme_ptrf_apps/core/tests/tests_notificacao/test_viewset.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_gerar_relatorio.py
Esse PR:
- Corrige testes que estavam quebrando
História: [AB#63850](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63850)
> test(63850): Demonstrativo financeiro: o cálculo do saldo reprogramado (campo 15) não considera a despesa realizada (campo 14)  - Parte 04

- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
feat(62450): Ajuste pdf
Esse PR:
- Realiza ajuste na condição para mostrar saldo no PDF
> feat(62450): Ajuste pdf

- sme_ptrf_apps/core/services/dados_relatorio_acertos_service.py
- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
História: [AB#63583](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63583)
> homolog(63583): Posição em Develop 13/05/2022 às 13:36

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
feat(57865): Ajuste
Esse PR:
- Realiza ajuste em recomendacoes
História: [AB#57865](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57865)
> feat(57865): Ajuste

- README.md
- sme_ptrf_apps/__init__.py
História: [AB#64695](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64695)
> docs(64695): Atualiza release notes 1.31.0

- hotfixes.md
- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
Corrige o bug: [AB#64921](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64921)
> fix(64921): Quebra de linha e exibição de linhas verticais

- sme_ptrf_apps/core/api/serializers/comentario_analise_prestacao_serializer.py
- sme_ptrf_apps/core/api/views/comentarios_analises_prestacoes_viewset.py
- sme_ptrf_apps/core/models/comentario_analise_prestacao.py
- sme_ptrf_apps/core/tests/tests_api_comentarios_analises_prestacoes/test_action_comentarios_nao_notificados_e_notificados.py
- sme_ptrf_apps/core/tests/tests_api_comentarios_analises_prestacoes/test_comentario_analise_prestacao_delete.py
- sme_ptrf_apps/core/tests/tests_api_comentarios_analises_prestacoes/test_comentario_analise_prestacao_update.py
Esse PR:
- Inclui validações e testes
História: [AB#55961](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/55961)
> feat(55961): Acompanhamento PC: Remoção do bloco Cobrança da PC e revisão do bloco Comentários - Parte 02

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
feat(62580): ata parecer tecnico melhorias em tela
Esse PR:
- Altera listagem de Pcs reprovadas
História: AB#6580
> feat(62580): ata parecer tecnico melhorias em tela

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/dre/services/lauda_service.py
Corrige: [AB#62205](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62205)
> hotfix(1.31.2)

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
Esse PR:
- Corrige PC em análise - despesa sem transação
- Inclui filtros em AnaliseLancamentoPrestacaoConta e AnaliseDocumentoPrestacaoConta
História: [AB#64877](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64877)
> fix(64877): Prestação de contas em processamento - EMEF Maria Aparecida Rodrigues Cintra

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
- sme_ptrf_apps/dre/services/lauda_service.py
Corrige: [AB#64877](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64877)
> hotfix(1.31.3)

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/presentes_ata_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/ata_dados_service.py
- sme_ptrf_apps/core/services/membro_associacao_service.py
- sme_ptrf_apps/core/tests/tests_api_presentes_ata/test_api_presentes_ata.py
Corrige: [AB#64318](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64318)
> hotfix(1.31.4)

- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_associacoes_srarus_regularidade_ano.py
- sme_ptrf_apps/dre/api/views/relatorios_consolidados_dre_viewset.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/dre/services/demo_execucao_fisico_financeiro_pdf_service.py
- sme_ptrf_apps/dre/services/regularidade_associacao_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tasks.py
- sme_ptrf_apps/static/css/pdf-demo-execucao-fisico-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/pdf-horizontal.html
feat(60314): PDF Relatorio consolidado
Esse PR:
- Cria PDF de relatório de acertos
- Cria serviços para geração do PDF
- Adiciona membros da comissão ao campo de assinaturas
História: [AB#60314](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60314)
> feat(60314): PDF Relatorio consolidado

- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_associacoes_srarus_regularidade_ano.py
Agora o relatório consolidado é gerado por PDF
> feat(60314): PDF Relatorio consolidado-parte-2

- sme_ptrf_apps/static/css/pdf-demo-execucao-fisico-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/pdf-horizontal.html
Esse PR:
- Realiza ajuste largura titulos tabelas
História: [AB#60314](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60314)
> feat(60314): ajuste

- README.md
- sme_ptrf_apps/__init__.py
História: [AB#66028](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66028)
> doc(66028): Atualiza release notes 1.32.0

- hotfixes.md
- sme_ptrf_apps/core/services/associacoes_service.py
- sme_ptrf_apps/core/services/implantacao_saldos_services.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_implantacao_saldos.py
Corrige o bug: [AB#64225](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64225)
> fix:(64225): nao habilitacao btn valores reprogramados

- sme_ptrf_apps/core/api/views/conciliacoes_viewset.py
Esse PR:
- Corrige permissão para visualização e download do extrato usuário do grupo DRE_NIVEL_1
Corrige: [AB#64886](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64886)
> fix(64886): Não visualização e não realização do download dos extratos bancários

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/static/css/pdf-demo-execucao-fisico-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/pdf-horizontal.html
Ajuste: [AB#66319](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66319)
> feat(66319) Melhorias PDF relatório consolidado

- hotfixes.md
- sme_ptrf_apps/core/models/periodo.py
Corrige o bug: [AB#66396](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66396)
> fix(66396) Altera lógica de data pertence ao periodo

- sme_ptrf_apps/core/api/serializers/unidade_serializer.py
Esse PR altera o serializer de list de unidades para incluir o campo nome. 
Esse campo é usado pela busca incrementa de unidades no cadastro de usuários.
> feat(52292): Altera o serializer de list de unidades

- sme_ptrf_apps/core/api/serializers/__init__.py
- sme_ptrf_apps/core/api/serializers/unidade_serializer.py
- sme_ptrf_apps/core/api/views/unidades_viewset.py
- sme_ptrf_apps/core/tests/tests_api_unidades/test_list_unidades.py
Altera o serializer de list de unidades para resolver testes quebrando.
> feat(52292): Resolve testes quebrando

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/tasks.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_cria_documentos_relatorios_fisicos_financeiros.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_status_consolidado_dre.py
Esse PR:
- Altera método assincrono para retornar Consolidado Dre com status em processamento
História: [AB#63286](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63286)
> feat(63286): Relatório consolidado: Parte 01 - Publicação - Geração de arquivos para todas as contas ao mesmo tempo e mudança no layout - Parte 02

- sme_ptrf_apps/dre/models/consolidado_dre.py
Esse PR:
- Inclui e configura Auditlog em Consolidado Dre
História: [AB#63286](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63286)
> feat(63286): Relatório consolidado: Parte 01 - Publicação - Geração de arquivos para todas as contas ao mesmo tempo e mudança no layout - Parte 03

- sme_ptrf_apps/dre/tasks.py
Esse PR:
- Altera forma de obter objeto Consolidado Dre em gerar_relatorio_consolidado_dre_async
História:AB#63286
> feat(63286): Relatório consolidado: Parte 01 - Publicação - Geração de arquivos para todas as contas ao mesmo tempo e mudança no layout - Parte 04

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/dre/api/views/valores_reprogramados_viewset.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/valores_reprogramados_dre_service.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/conftest.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_endpoint.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_filtros.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_list.py
Esse PR:
- Altera regra de listagem da API de valores reprogramados
- Adiciona testes relacionados a alteração de regra
- Adiciona action ao admin do modelo Associacao para definir status de valores reprogramados da associacao
História: [AB#60461](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60461)
> feat(60461)-parte-2: altera regra listagem valores reprogramados

- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/tasks.py
Esse PR:
- Altera novamente método de criação e carregamento de objeto do Consolidado DRE
> feat(63286): Relatório consolidado: Parte 01 - Publicação - Geração de arquivos para todas as contas ao mesmo tempo e mudança no layout

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/dre/api/views/valores_reprogramados_viewset.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/valores_reprogramados_dre_service.py
- sme_ptrf_apps/dre/tasks.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/conftest.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_endpoint.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_filtros.py
- sme_ptrf_apps/dre/tests/tests_api_valores_reprogramados_dre/test_valores_reprogramados_list.py
História: [AB#67211](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67211)
> homolog(67211): Posição em Develop 20/06/2022 às 15:59h

- sme_ptrf_apps/users/models.py
- sme_ptrf_apps/users/services/criar_acesso_de_suporte_service.py
Esse PR:
História: [AB#62851](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/62851)
> feat(62851): Suporte às Unidades: Viabilizar acesso de suporte - Parte 3

- sme_ptrf_apps/utils/built_in_custom.py
Ajuste em dois imports que estavam sendo referenciados de maneira deprecada.
> feat(65002) Ajuste em import do built_in_custom.

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
- sme_ptrf_apps/sme/tasks.py
Esse PR:
História: [AB#53051](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/53051)
> feat(53051): Exportações dados gera logs.

- sme_ptrf_apps/core/services/prestacao_contas_services.py
Corrige o bug: [AB#67882](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67882)
> fix(67882): Altera o retorno de data para data documento

- sme_ptrf_apps/users/tests/test_api_user/test_api_encerrar_acesso_suporte_unidade.py
Esse PR corrige teste da api de encerramento de suporte.
> feat(62837): Suporte às Unidades: Encerrar acesso de suporte - ajustes em testes

- sme_ptrf_apps/users/tests/tests_unidades_em_suporte/test_get_unidades_do_usuario_service.py
Esse PR Corrige teste do serviço get_unidades_do_usuario.
> feat(62851): Suporte às Unidades: Viabilizar acesso de suporte - corrige testes

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tasks.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_concluir_prestacao_de_contas_service.py
Corrige o bug: [AB#66548](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66548)
> fix(66548): Altera serviço assincrono de concluir periodo

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tasks.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_concluir_prestacao_de_contas_service.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
Corrige os bugs: 
- [AB#66548](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66548)
- [AB#67689](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67689)
- [AB#67882](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67882)
- [AB#65722](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/65722)
> hotfix(1.32.3)

- sme_ptrf_apps/dre/api/views/ata_parecer_tecnico_viewset.py
- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_informacoes_pcs_do_consolidado_dre.py
Esse PR:
- Altera endpoint /api/ata-parecer-tecnico/info-ata e status-ata para permitir o preenchimento da Ata sem a criação do Consolidado DRE
História: [AB#64958](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64958)
> feat(64958): Relatório consolidado: Parte 03a - Publicação - Geração de ata no momento da publicação - Parte 02

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/services/lauda_service.py
- sme_ptrf_apps/dre/tasks.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/conftest.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_download_consolidado_dre_lauda.py
Esse PR:
- Finaliza a geração da Lauda ao Publicar
História: [AB#64958](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/64958)
> feat(64958): Relatório consolidado: Parte 03b - Publicação - Geração de laudas no momento da publicação - Parte 03

- README.md
- sme_ptrf_apps/__init__.py
[AB#68830](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/68830)
> docs(68830): Release Notes 1.33.0 - Release 5 (Parcial)

- sme_ptrf_apps/core/services/dados_demo_financeiro_service.py
Esse PR:
História: [AB#66375](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66375)
> feat(66375): Adiciona hora atual em roda pé do demonstrativo financeiro.

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
Esse PR:
História: [AB#66387](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66387)
> feat(66387): exibi hora geracao fisico financeiro

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
Esse PR:
História: [AB#66388](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66388)
> feat(66388) Adiciona em ata de parecer horário em data.

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
Esse PR:
Historia:[AB#66388](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/66388)
> feat(66388): Atualiza datetime para não quebrar os imports.

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Implementa informação sobre versão (final/previa) no PDF do Relatório Consolidado da DRE
História: [AB#63315](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63315)
> feat(63315): Relatório consolidado: Parte 04 - Prévias - Geração de prévias dos demonstrativos e ata - Parte 02

- sme_ptrf_apps/core/services/conciliacao_services.py
- PR:
Esse PR:
História: [AB#63013](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63013)
> bugfix(63013) Adiciona campo de informações com retorno de tags.

- sme_ptrf_apps/conftest.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/services/__init__.py
- sme_ptrf_apps/core/services/painel_resumo_recursos_service.py
- sme_ptrf_apps/core/services/resumo_rescursos_service.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_painel_acoes.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_painel_acoes_de_uma_conta.py
- sme_ptrf_apps/core/tests/tests_services/tests_painel_resumo_recursos_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_painel_resumo_recursos_service/test_painel_resumo_recursos_servico_cria_objeto.py
- sme_ptrf_apps/core/tests/tests_services/tests_painel_resumo_recursos_service/test_painel_resumo_recursos_servico_retorna_info_acoes.py
- sme_ptrf_apps/core/tests/tests_services/tests_painel_resumo_recursos_service/test_painel_resumo_recursos_servico_retorna_info_conta.py
- sme_ptrf_apps/core/tests/tests_services/tests_painel_resumo_recursos_service/test_painel_resumo_recursos_servico_retorna_json.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/conftest.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/test_resumo_recursos_cria_objeto_servico.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/test_resumo_recursos_saldo_anterior.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/test_resumo_recursos_saldo_posterior.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/test_resumo_recursos_soma_despesas.py
- sme_ptrf_apps/core/tests/tests_services/tests_resumo_recursos_service/test_resumo_recursos_soma_receitas.py
Esse PR:
História: [AB#60431](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60431)
> feature(60431) Implementa novos serviços para cálculo de resumo de recursos

- sme_ptrf_apps/users/api/views/senha_viewset.py
Esse PR:
- Alterar a view de redefinição de senha para repassar para o front os erros retornados pela API do EOL. O erro de senha igual às 5 últimas não estava sendo repassado.
> feat(66657) Altera senha_viewset para retornar erro da API

- sme_ptrf_apps/core/tests/tests_api_conciliacoes/test_get_transacoes_conciliacao.py
- sme_ptrf_apps/users/api/views/senha_viewset.py
[AB#68749](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/68749)
> Posição de Develop em 19/07/2022 17:44

- sme_ptrf_apps/dre/services/valores_reprogramados_dre_service.py
feat(60462)-parte-2 ajuste total contas
Esse PR:
- Realiza ajuste no calculo de total de contas
História: [AB#60462](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/60462)
> feat(60462)-parte-2 ajuste total contas

- README.md
- sme_ptrf_apps/__init__.py
[AB#70164](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70164)
> docs(1.34): Release Notes

- sme_ptrf_apps/core/admin.py
Esse PR:
História: [AB#65920](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/65920)
> feat(65920) Adiciona filtro por nome e lista frinto por categoria

- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/dre/admin.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tasks.py
- sme_ptrf_apps/dre/templatetags/quantidade_rowspan.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_cria_documentos_relatorios_fisicos_financeiros.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_cria_previa_documentos_relatorios_fisicos_financeiros.py
- sme_ptrf_apps/static/css/pdf-demo-execucao-fisico-financeiro-horizontal.css
Esse PR:
- Implementa geração do relatório consolidado da DRE único para todas as contas
História: [AB#67941](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/67941)
> feat(67941): Relatório consolidado: Parte 07a - Demonstrativo da execução físico-financeira único com todas as contas

- sme_ptrf_apps/dre/admin.py
- sme_ptrf_apps/dre/services/vincular_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_services/tests_vincular_consolidado_service/conftest.py
- sme_ptrf_apps/dre/tests/tests_services/tests_vincular_consolidado_service/test_vincular_recursos_service.py
Altera o admin de relatórios físico-financeiro para incluir uma ação
para integrar os relatórios a um consolidado DRE.
> feat(70111): Cria ação integrar consolidado rel físico-financeiro

- sme_ptrf_apps/static/css/pdf-demo-execucao-fisico-financeiro-horizontal.css
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-execucao-fisica.html
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-execucao-fisico-financeira.html
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-sintese-execucao-financeira.html
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/pdf-horizontal.html
Esse PR:
- Realiza alterações no layout do PDF do demonstrativo da execução físico-financeira
História: [AB#69307](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/69307)
> feat(69307): Relatório consolidado: Parte 07b - Demonstrativo da execução físico-financeira: Alterações no layout do PDF

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
Esse PR:
- Corrige método converte_string_value_formatada_para_float removendo import locale
História: [AB#69307](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/69307)
> feat(69307): Relatório consolidado: Parte 07b - Demonstrativo da execução físico-financeira: Alterações no layout do PDF - Parte 02

- sme_ptrf_apps/dre/admin.py
- sme_ptrf_apps/dre/services/vincular_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_services/tests_vincular_consolidado_service/conftest.py
- sme_ptrf_apps/dre/tests/tests_services/tests_vincular_consolidado_service/test_vincular_recursos_service.py
Esse PR:
- Altera o admin de atas de parecer técnico para incluir uma ação para integrar as atas a um consolidado DRE.
[AB#70112](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70112)
> feat(70112): Cria ação integrar consolidado ata parecer técnico

- sme_ptrf_apps/core/services/tipos_acerto_lancamento_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_tipos_acertos_lancamentos_service/test_service_endpoint_tabelas_lancamentos.py
feat(57620)-parte-2 ajuste agrupamento categorias
Esse PR:
- Adiciona todas as informações de tipo acerto ao agrupamento
História: [AB#57620](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57620)
> feat(57620)-parte-2 ajuste agrupamento categorias

- sme_ptrf_apps/dre/admin.py
- sme_ptrf_apps/dre/tests/tests_services/tests_vincular_consolidado_service/conftest.py
- sme_ptrf_apps/dre/tests/tests_services/tests_vincular_consolidado_service/test_vincular_recursos_service.py
Esse PR:
- Altera o admin de laudas para incluir uma ação para integrar as atas a um consolidado DRE.
História: AB#70
> feat(70113): Cria ação integrar consolidado em Laudas

- sme_ptrf_apps/dre/api/views/ata_parecer_tecnico_viewset.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service-COPIA-FUNCIONANDO.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
Esse PR:
- Altera Ata de Parecer Técnico em tela para exibir apenas PCs do consolidado
História: [AB#70099](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70099)
> feat(70099): Relatório consolidado: Parte 10a - Ata em tela: Eliminar seções por conta e exibir apenas PCs do consolidado

- sme_ptrf_apps/core/api/serializers/tipo_acerto_documento_serializer.py
- sme_ptrf_apps/core/api/serializers/tipo_acerto_lancamento_serializer.py
- sme_ptrf_apps/core/api/views/tipos_acerto_documento_viewset.py
- sme_ptrf_apps/core/models/tipo_acerto_documento.py
- sme_ptrf_apps/core/services/tipos_acerto_documento_service.py
- sme_ptrf_apps/core/tests/tests_services/tests_tipos_acertos_documentos_service/test_service_endpoint_tabelas_documentos.py
feat(65959)-parte-2 ajuste agrupamento categorias
Esse PR:
- Realiza ajuste no agrupamento de categorias de tipos de acertos de documento
História: [AB#65959](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/65959)
> feat(65959)-parte-2 ajuste agrupamento categorias

- sme_ptrf_apps/core/services/tipos_acerto_documento_service.py
- sme_ptrf_apps/core/services/tipos_acerto_lancamento_service.py
feat(57620)-parte-3 ajuste texto categorias
Esse PR:
- Realiza ajuste em textos das categorias
História: [AB#57620](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/57620)
> feat(57620)-parte-3 ajuste texto categorias

- sme_ptrf_apps/core/services/info_por_acao_services.py
Corrige bug [AB#71317](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/71317)
> fix(71317): Altera verificação de saldo para despesa

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/core/services/info_por_acao_services.py
Resolve [AB#71317](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/71317)
> fix(71317): Resolve verificação de saldo de ação no lançamento de gasto

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
[AB#71372](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/71372)
> fix(71372): Corrige cálculo de outros créditos

- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_execucao_financeira_relatorio_consolidado_dre.py
Ajusta testes unitários devido a inclusão de campo tipo_conta_uuid.
> test(70107): Ajusta testes unitátrios

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/tests/tests_api_consolidado_dre/test_action_retornar_status_relatorio_consolidado_de_publicacoes_parciais.py
Esse PR:
- Cria endpoint para retornar status do relatorio do consolidado de publicacoes parciais
História: [AB#63342](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/63342)
> feat(63342): Relatório consolidado: Parte 08 - Consolidado de publicações parciais - Parte 02

- hotfixes.md
- sme_ptrf_apps/__init__.py
- sme_ptrf_apps/despesas/admin.py
História: [AB#71609](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/71609)
> feat(71609) Cria novos filtros no admin de despesas

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Ajusta quantidade de unidades no relatorio consolidado em tela
História: [AB#70107](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70107)
> feat(70107): Relatório consolidado: Parte 11 - Nova consulta do relatório em tela - Parte 02

- sme_ptrf_apps/dre/services/lauda_service.py
feat(72200)-lauda: Relatório consolidado - Lauda
Esse PR:
- Altera valor campos receita
História: [AB#72200](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72200)
> feat(72200)-lauda: Relatório consolidado - Lauda:

- sme_ptrf_apps/dre/services/lauda_service.py
feat(72200)-lauda: Relatório consolidado - Lauda
Esse PR:
- Altera valor campos receita
História: [AB#72200](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72200)
> feat(72200)-lauda: Relatório consolidado - Lauda

- sme_ptrf_apps/dre/tests/tests_api_membros_comissoes/test_membro_comissao_create.py
Remove teste que devera ser refatorado no futuro pois esta quebrando por indisponibilidade de API de terceiros
> feat(72200)-parte-dois:

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_execucao_financeira_relatorio_consolidado_dre.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_trilha_de_status.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela_identificacao.html
Esse PR:
- Realiza melhorias em Relatorio Consolidado apos testes
História: [AB#72198](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72198)
> feat(72198): Relatório consolidado - Demonstrativo: melhorias pós testes

- sme_ptrf_apps/dre/models/consolidado_dre.py
Esse PR:
História: [AB#72288](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72288)
> fix(72288) Ajusta texto do front

- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
- sme_ptrf_apps/dre/services/lauda_service.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
- sme_ptrf_apps/dre/tests/tests_api_relatorios_consolidados_dre/test_get_info_execucao_financeira_relatorio_consolidado_dre.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_trilha_de_status.py
- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela_identificacao.html
Esse PR:
- Ajusta Property referência em consolidado_dre.py
História: [AB#72201](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72201)
> feat(72288) Ajusta texto do front

- sme_ptrf_apps/dre/services/lauda_service.py
feat(72200)-ajuste-calculo-lauda: Ajuste no calculo da lauda
Esse PR:
- Realiza ajuste no calculo da lauda
História: [AB#72200](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72200)
> feat(72200)-ajuste-calculo-lauda: Ajuste no calculo da lauda

- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
Esse PR:
- Resolve valor negativo em Bloco 3 - Não Apresentadas do demonstrativo consolidado
História: [AB#72905](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72905)
> fix(72905): Relatório consolidado: demonstrativo consolidado: campo "não apresentadas" do Bloco 3 exibe valor negativo

- sme_ptrf_apps/core/admin.py
Esse PR:
História: [AB#68839](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/68839)
> feat(68839): Inclui filtros no admin de prestações de contas

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_model.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_serializer.py
Esse PR:
- Retorna Justificativa de Falta de Ajustes em PC
História: [AB#58248](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/58248)
> feat(58248): Acompanhamento de PC: Ver justificativa de falta de ajustes em PC retornada após acertos

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/services/analise_documento_prestacao_conta_service.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_model.py
- sme_ptrf_apps/core/tests/tests_prestacao_conta/test_prestacao_conta_serializer.py
História: [AB#70621](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/70621)
> homolog(70621): Posição em Develop 31/08/2022 às 13:50h

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
Esse PR:
História: [AB#72908](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72908)
> fix(72908) Ajusta cabeçalho e rodapé ata parecer técnico.

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/models/valores_reprogramados.py
História: [AB#73629](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73629)
> feat(73629)-migrar-valores-reprogramados: Migrar valores reprogramados

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
Corrige: [AB#72992](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/72992)
> fix(72992)-fechamentos-duplicados

- sme_ptrf_apps/despesas/models/rateio_despesa.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/conftest.py
- sme_ptrf_apps/despesas/tests/tests_api_despesas/test_delete_despesas.py
Esse PR:
- Altera a desativação de despesas para desativar também estornos vinculados.
História: [AB#73234](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73234)
> feat(73234): Implementa desativação de estorno de gasto

- sme_ptrf_apps/core/models/prestacao_conta.py
Corrige [AB#71660](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/71660)
> fix(71660): Inclui tratamento de erros de notificação na conclusão de PC

- sme_ptrf_apps/despesas/models/rateio_despesa.py
esse PR:
História [AB#73291](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73291)
> Feature(73291) ajusta teste completas

- sme_ptrf_apps/sme/services/exporta_dados_creditos_service.py
Esse PR:
História: [AB#73295](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73295)
> Feat(73295)extracao status creditos

- README.md
- sme_ptrf_apps/__init__.py
História: [AB#74909](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74909)
> feat(74909): Atualiza release notes 1.34.0

- sme_ptrf_apps/contrib/scripts_diversos/dev_tesouro.sql
- sme_ptrf_apps/core/services/carga_devolucoes_tesouro_service.py
História: [AB#74103](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74103)
> fix(74103): Altera carga dev-tesouro para datas vazias

- sme_ptrf_apps/core/admin.py
Permite selecionar solicitações de devolução sem uma devolução ao tesouro vinculada e vincula-las a devoluções ao tesouro existentes.
> fix(74103): Cria ação para vincular solicitações órfãs

- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
Esse PR:
- Resolve duplicação total devoluções ao tesouro
História: [AB#74632](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74632)
> feat(74632): Relatório consolidado: Demonstrativo - Alterar exibição do valor de devolução ao tesouro

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
Esse PR:
- Inclui verificação de data e página de publicação preenchidas
História: [AB#74811](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74811)
> feat(74811): Relatório Consolidado: Incluir verificação da data e página da publicação

- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
- sme_ptrf_apps/core/services/dados_relatorio_apos_acertos_service.py
- sme_ptrf_apps/core/tasks.py
feat(73288): Relatorio apos acertos final
Esse PR:
- Chama serviço de geração do relatório após acertos ao concluir um periodo
- Altera texto do rodapé do PDF quando versão final
História: [AB#73288](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/73288)
> feat(73288): Relatorio apos acertos final

- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/api/views/relacao_bens_viewset.py
História [AB#74391](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74391)
> feat(74391): Altera info relatórios no caso de prévias

- sme_ptrf_apps/core/services/dados_relatorio_apos_acertos_service.py
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/pdf.html
- sme_ptrf_apps/templates/pdf/relatorio_dos_acertos/pdf.html
> feat(73288)-parte-2: Ajuste rodape

- sme_ptrf_apps/dre/models/lauda.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/services/lauda_service.py
- sme_ptrf_apps/dre/tasks.py
feat(75110): Gerar lauda unica
Esse PR:
- Altera serviço de geração da lauda, para gerar lauda unica
- Altera endpoint para adicionar informação de tipo conta None
História: [AB#75110](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/75110)
> feat(75110): Gerar lauda unica

- sme_ptrf_apps/core/admin.py
[AB#75743](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/75743)
> feat(75743) Melhorias no admin de informações de conciliação

- sme_ptrf_apps/core/admin.py
Esse PR altera o admin 16.1) Análises de lançamentos
> feat(55129): Altera admin 16.1-Análises Lancto

- sme_ptrf_apps/core/admin.py
Esse PR altera o admin 16.3) Solicitações de acertos em lançamentos
> feat(55129): Altera admin 16.3-Solicitacao acertos lancto

- sme_ptrf_apps/core/admin.py
feat(31473): Admin Arquivo carga
Esse PR:
- Adiciona filtros ao admin de arquivos de carga
História: [AB#31473](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/31473)
> feat(31473): Admin Arquivo carga

- sme_ptrf_apps/core/api/views/analise_lancamento_prestacao_conta_viewset.py
- sme_ptrf_apps/core/models/analise_lancamento_prestacao_conta.py
- sme_ptrf_apps/core/services/analise_lancamento_prestacao_conta_service.py
[AB#75777](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/75777)
> feat(75777): Cria endpoint passar dev tesouro para ñ atualizada

- sme_ptrf_apps/core/admin.py
Em 16.7) Análises de documentos de PC
> feat(55129): Altera admin de solicit ajuste docs

- sme_ptrf_apps/core/admin.py
feat(52175): Admin Parametros
Esse PR:
- Altera listagem
- Agrupa campos na edição
História: [AB#52175](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52175)
> feat(52175): Admin Parametros

- sme_ptrf_apps/core/admin.py
feat(52176): Admin Associacao
Esse PR:
- Adiciona filtros ao admin de associacao
História: [AB#52176](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52176)
> feat(52176): Admin Associacao

- sme_ptrf_apps/core/admin.py
> feat(55129): Altera admin presentes ata

- sme_ptrf_apps/core/admin.py
> feat(55129): Altera admin vrs reprogramados

- sme_ptrf_apps/core/admin.py
feat(50189): Admin MembroAssociacao
Esse PR:
- Adiciona filtros ao admin de membro associacao
História: [AB#50189](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/50189)
> feat(50189): Admin MembroAssociacao

- sme_ptrf_apps/core/admin.py
feat(52177): Admin Conta Associacao e Acao Associacao
Esse PR:
- Adiciona filtros ao admin de ContaAssociacao
- Adiciona filtros ao admin de AcaoAssociacao
História: [AB#52177](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52177)
> feat(52177): Admin Conta Associacao e Acao Associacao

- sme_ptrf_apps/core/admin.py
16.8) Solicitações de dev. tesouro
> feat(55129): Altera admin Solicitações de Dev Tesouro

- sme_ptrf_apps/users/admin.py
Altera titulo do filtro por unidade
> feat(61545)-parte-2: Altera admin usuarios

- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/despesas/api/serializers/despesa_serializer.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- sme_ptrf_apps/receitas/models/receita.py
Esse PR:
História [AB#76642](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76642)
> feat(76642): Ajusta mensagem de retorno que foi mocada em protótipo UX.

- sme_ptrf_apps/core/services/dados_relatorio_acertos_service.py
Esse PR:
-[x] Alterar o termo "Rascunho" para "Prévia”
História [AB#76337](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76337)
> feat(76337): Ajusta texto para prévia no lugar do rascunho

- sme_ptrf_apps/dre/services/ata_parecer_tecnico_service.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
- sme_ptrf_apps/dre/tests/tests_services/test_consolidado_dre_trilha_de_status.py
Esse PR:
História: [AB#76653](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76653)
> Feat(76653) nomenclaturas referente ao relatorio consolidado back

- sme_ptrf_apps/core/admin.py
Esse PR:
-[x] aplicar um filtro que exiba todos os registros de determinada DRE;
-[x] busca (search) pelo nome da associação;
-[x] lista uma coluna com o nome da associação.
História [AB#52179](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/52179)
> feat(52179) Ajuste em associao e consolidado dre

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/services/periodo_services.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Altera regra para bloquear geração e edicao das atas da associacao
História: [AB#76272](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/76272)
> fix(76272): Bloqueio edição atas associação

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/services/periodo_services.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_status_periodo.py
Esse PR:
- Altera regra para bloquear botoes de geração e edicao das atas da associacao
> (fix)r6.76272 bloqueio edicao atas associacao

- sme_ptrf_apps/core/admin.py
> feat(72222) Adiciona raw_id_fields para melhorar o processo de indexa… (homolog)

- sme_ptrf_apps/dre/api/serializers/consolidado_dre_serializer.py
Esse PR:
- Implementa Status Devolvido Para Acerto em Analise dos Relatórios Consolidados
História: [AB#74209](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74209)
> feat(74209): Análise dos Relatórios Consolidados das DRE's: Visualizar Relatório Consolidado - Status: Devolvido para acerto

- sme_ptrf_apps/core/services/analise_prestacao_conta_service.py
fix(r6.77736): Copia de analises
Esse PR:
- Altera método de cópia de analises para não copiar status de realização
História: [AB#77736](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77736)
> fix(r6.77736): Copia de analises

- sme_ptrf_apps/dre/api/serializers/consolidado_dre_serializer.py
Esse PR:
- Ajusta comportamento botão Concluir Analise
> feat(74208): Análise dos Relatórios Consolidados das DRE's: Visualizar Relatório Consolidado - Status: Em análise

- sme_ptrf_apps/core/services/prestacao_contas_services.py
Esse PR resolve o bug [AB#78548](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/78548)
> fix(78548): Corrige bug de classificação de lançamentos no acompanhamento de PCs

- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
Corrige testes que estavam quebrando.
> test(78548): Corrige testes

- sme_ptrf_apps/core/admin.py
Esse PR:
- Melhora o cadastro de devolução ao tesouro (admin)
> fix(77339): Melhoria admin

- sme_ptrf_apps/dre/services/lauda_service.py
feat(r6.77638): Alterar titulo lauda
Esse PR:
- Altera titulo da lauda
História: [AB#77638](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77638)
> feat(r6.77638): Alterar titulo lauda

- sme_ptrf_apps/templates/pdf/demonstrativo_execucao_fisico_financeiro/partials/tabela-sintese-execucao-financeira.html
[AB#79686](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79686)
> fix(hf.79686) Erro no layout do relatório consolidado

- sme_ptrf_apps/dre/tests/tests_api_membros_comissoes/test_membro_comissao_create.py
[AB#79395](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79395)
> tec(79395): Desacopla teste membro comissão de API externa

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
Corrige [AB#80480](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80480)
> Fix(hf.80480) Erro de cálculo na execução físico financeira do consolidado DRE

- sme_ptrf_apps/core/api/views/associacoes_viewset.py
- sme_ptrf_apps/core/tests/tests_api_associacoes/test_action_contas_com_acertos_em_lancamentos.py
Esse PR:
- Cria Endpoint para retornar contas com analises de lançamentos
História: [AB#77703](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/77703)
> feat(77703): Análise DRE: Ajustar mensagem exibida em Acertos dos lançamentos e documentos quando não existe acerto

- sme_ptrf_apps/core/models/analise_prestacao_conta.py
feat(r6.78327)-geracao-documentos-validacao-acerto
Esse PR:
[x] Altera regras de "tem_ajustes_pendetes" no retorno de Endpoint status-periodo 
História: [AB#78327](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/78327)
> feat(r6.78327)-geracao-documentos-validacao-acerto

- sme_ptrf_apps/core/admin.py
- sme_ptrf_apps/dre/services/dados_demo_execucao_fisico_financeira_service.py
[AB#80480](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80480)
> Fix(hf.80480) Erro cálculo execução físico financeira consolidado DRE

- sme_ptrf_apps/users/tests/test_api_user/test_api_update_user.py
[AB#79488](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/79488)
> Update homolog 05 dez manha

- sme_ptrf_apps/core/services/dados_relatorio_acertos_service.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
fix(80937): Relatorio de acertos
Esse PR:
- Adiciona flag para agrupar por solicitacoes ao metodo de lancamentos_da_prestacao
História: [AB#80937](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80937)
> fix(80937): Relatorio de acertos

- sme_ptrf_apps/core/models/analise_lancamento_prestacao_conta.py
fix(80956): Status realizacao dev. tesouro
Esse PR:
Adiciona regra para alterar status realizacao ao desfazer devolução ao tesouro
> fix(80956): Status realizacao dev. tesou

- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/partials/tabela-acertos-em-documentos.html
Corrige [AB#74315](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74315)
> fix(74315): Corrige tabela de acertos em documentos em relatório após acertos

- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/partials/tabela-acertos-em-documentos.html
Corrige: [AB#80961](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80961)
> Fix/r6.80961 Bug bloco3 rel após acertos corrige sequencia

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard_sme.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
feature(28853): Resumo por dre detalhe
Esse PR:
- Adiciona flag de status ao retorno da API
História: [AB#28853](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/28853)
> feature(28853): Resumo por dre detalhe

- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_dashboard_sme.py
- sme_ptrf_apps/dre/services/relatorio_consolidado_service.py
História: [AB#80734](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80734)
> Posição do back em 14/12/2022 11:30

- sme_ptrf_apps/core/services/dados_relatorio_apos_acertos_service.py
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/partials/tabela-acertos-em-extratos-bancarios.html
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/pdf.html
fix(81540): Relatorio após acertos
Esse PR:
- Adiciona bloco de extratos bancarios ao relatório
História: [AB#81540](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/81540)
> fix(81540): Relatorio após acertos

- sme_ptrf_apps/core/services/dados_relatorio_apos_acertos_service.py
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/partials/tabela-acertos-em-extratos-bancarios.html
- sme_ptrf_apps/templates/pdf/relatorio_apos_acertos/pdf.html
fix(81540): Relatorio após acertos
Esse PR:
Adiciona bloco de extratos bancarios ao relatório
> Resolve conflito 81540

- sme_ptrf_apps/core/tests/tests_api_associacoes/test_list_associacoes_status_regularidade_ano.py
[AB#80684](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80684)
> test(80684): Altera teste de list regularidade

- sme_ptrf_apps/core/tests/tests_api_analises_prestacoes_contas/test_list_lancamentos.py
- sme_ptrf_apps/despesas/models/despesa.py
- sme_ptrf_apps/despesas/tests/tests_despesas/test_despesa_tags_informacoes.py
- sme_ptrf_apps/receitas/api/serializers/receita_serializer.py
- sme_ptrf_apps/receitas/models/receita.py
- sme_ptrf_apps/receitas/tests/test_receita/test_receita_tags_informacoes.py
[x] Alterar texto da mensagem no modelo de Despesa
[x] Alterar texto da mensagem no modelo de Receita
HístoriaAB#81543
> feat(81543) Ajusta alteração de texto lançamentos

- sme_ptrf_apps/core/api/serializers/prestacao_conta_serializer.py
- sme_ptrf_apps/core/models/prestacao_conta.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_retrieve_prestacao_conta.py
feat(74494): Incluir property em retificacao
Esse PR:
- Adiciona property ao modelo de PrestacaoContas
- Adiciona property ao serializer
História: [AB#74494](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74494)
> feat(74494): Incluir property em retificacao

- sme_ptrf_apps/core/admin.py
[AB#82321](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82321)
> fix(r6.82321) - Admin corrige tempo de abertura do edit

- sme_ptrf_apps/core/admin.py
Corrige o tempo excessivo de abertura do formulário de edição.
[AB#82341](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82341)
> fix(82341): Corrige admin 9.9-Devoluções ao tesouro PC

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
feat(80607): Consolidado dre, incluir qtde pcs
Esse PR:
- Adiciona quantidade de PCs ao retorno da API
- Adiciona quantidade de PCs ao titulo da publicacao
História: [AB#80607](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80607)
> feat(80607): Consolidado dre, incluir qtde pcs

- sme_ptrf_apps/core/tests/tests_api_unidades/test_list_unidades.py
Corrige testes de list unidades que apresentavam resultados errados.
[AB#80686](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/80686)
> fix(80686): Corrige testes list_unidades

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/consolidado_dre_service.py
feat(80660): Incluir referencia retificação
Esse PR:
- Adiciona tipo relatorio retificacao ao filtro
- Adiciona o termo de retificacao a listagem de relatorios
- Altera property dre referencia do consolidado
História: AB#80660
> feat(80660): Incluir referencia retificação

- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/test_lista_prestacoes_de_conta_todos_os_status.py
História [AB#28859](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/28859)
> feat(28859) Criação de filtro devolucao em prestao de conta

- sme_ptrf_apps/dre/api/validation_serializers/analise_consolidado_dre_serializer.py
- sme_ptrf_apps/dre/api/views/analises_consolidado_dre_viewset.py
- sme_ptrf_apps/dre/models/analise_consolidado_dre.py
- sme_ptrf_apps/dre/services/__init__.py
- sme_ptrf_apps/dre/services/analise_consolidado_dre_service.py
- sme_ptrf_apps/dre/services/dados_relatorio_devolucao_acertos_sme_service.py
- sme_ptrf_apps/dre/services/relatorio_devolucao_acertos_sme_service.py
- sme_ptrf_apps/dre/tests/tests_api_analise_consolidado_dre/test_action_gerar_previa_devolucao_acertos.py
- sme_ptrf_apps/sme/tasks.py
- sme_ptrf_apps/static/css/pdf-relatorio-devolucao-acertos-sme.css
- sme_ptrf_apps/templates/pdf/relatorio_devolucao_acertos_sme/partials/bloco-acertos-nos-documentos.html
- sme_ptrf_apps/templates/pdf/relatorio_devolucao_acertos_sme/partials/bloco-comentarios-notificados.html
- sme_ptrf_apps/templates/pdf/relatorio_devolucao_acertos_sme/partials/bloco-identificacao-dre.html
- sme_ptrf_apps/templates/pdf/relatorio_devolucao_acertos_sme/partials/bloco-responsavel-analise.html
- sme_ptrf_apps/templates/pdf/relatorio_devolucao_acertos_sme/pdf.html
feat(74212): Gerar previa relatorio sme
Esse PR:
[x] Cria serviço que obtém os dados
[x] Cria template do PDF
[x] Cria endpoint de geração do PDF
[x] Cria endpoint com informações de status do relatório 
História: [AB#74212](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74212)
> feat(74212): Gerar previa relatorio sme

- sme_ptrf_apps/core/api/serializers/validation_serializers/prestacoes_contas_lancamentos_validate_serializer.py
- sme_ptrf_apps/core/api/views/prestacoes_contas_viewset.py
- sme_ptrf_apps/core/services/prestacao_contas_services.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/conftest.py
- sme_ptrf_apps/core/tests/tests_api_prestacoes_contas/test_prestacoes_contas_lancamentos_endpoint.py
- sme_ptrf_apps/core/tests/tests_services/tests_prestacao_de_contas_services/tests_lancamento_da_prestacao_service/test_get_lancamentos.py
Corrige [AB#82433](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82433)
> fix(r6.82433) Erro em filtros de lançamento no acompanhamento de PC

- sme_ptrf_apps/dre/api/views/consolidados_dre_viewset.py
- sme_ptrf_apps/dre/models/consolidado_dre.py
- sme_ptrf_apps/dre/services/dados_relatorio_devolucao_acertos_sme_service.py
feat(74213): Gerar relatorio sme final
Esse PR:
- Adiciona seviço que gera relatorio versão final ao serviço de devolução para dre
História: [AB#74213](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/74213)
> feat(74213): Gerar relatorio sme final

- sme_ptrf_apps/core/services/solicitacao_acerto_documento_service.py
feat(82977): Ajuste marcar como realizado
Esse PR:
- Realiza ajuste para marcar realizado em lote
História: [AB#82977](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82977)
> feat(82977): Ajuste marcar como realizado

- sme_ptrf_apps/core/services/info_por_acao_services.py
Corrige [AB#83785](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83785)
> fix(83785): Erro verificação de saldos em contas

- sme_ptrf_apps/dre/services/consolidado_dre_service.py
[AB#82970](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/82970)
> Update homolog 12 jan23

- sme_ptrf_apps/core/api/views/demonstrativo_financeiro_viewset.py
- sme_ptrf_apps/core/api/views/relacao_bens_viewset.py
Esse PR:
- Implementa prévia de documentos em Reabertura Seletiva do Período
História: [AB#83760](https://dev.azure.com/amcomgov/df80ad90-407b-4f58-8a29-430604912a37/_workitems/edit/83760)
> feat(83760): Prestação de contas: Geração de documentos: Geração da prévia e do documento final
